// packages/docs/site/src/demos/grid/grid-offset.vue
<template>
  <div>
    <Row
      class="grid-demo"
      style="marginBottom: 16px; backgroundColor: var(--color-fill-2);"
    >
      <Col :span="8">col - 8</Col>
      <Col :span="8" :offset="8"> col - 8 | offset - 8 </Col>
    </Row>
    <Row
      class="grid-demo"
      style="marginBottom: 16px; backgroundColor: var(--color-fill-2);"
    >
      <Col :span="6" :offset="8"> col - 6 | offset - 8 </Col>
      <Col :span="6" :offset="4"> col - 6 | offset - 4 </Col>
    </Row>
    <Row class="grid-demo" style="backgroundColor: var(--color-fill-2)">
      <Col :span="12" :offset="8"> col - 12 | offset - 8 </Col>
    </Row>
  </div>
</template>

<style scoped>
.grid-demo .arco-col {
  height: 48px;
  line-height: 48px;
  color: var(--color-white);
  text-align: center;
}
.grid-demo .arco-col:nth-child(2n) {
  background-color: rgba(var(--arcoblue-6), 0.9);
}
.grid-demo .arco-col:nth-child(2n + 1) {
  background-color: var(--color-primary-light-4);
}
</style>

// packages/docs/site/src/demos/grid/grid-offset.tsx
import { Grid } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div style={{ width: '100%' }}>
      <Grid.Row
        className="grid-demo"
        style={{ marginBottom: 16, backgroundColor: 'var(--color-fill-2)' }}
      >
        <Grid.Col span={8}>col - 8</Grid.Col>
        <Grid.Col span={8} offset={8}>
          col - 8 | offset - 8
        </Grid.Col>
      </Grid.Row>
      <Grid.Row
        className="grid-demo"
        style={{ marginBottom: 16, backgroundColor: 'var(--color-fill-2)' }}
      >
        <Grid.Col span={6} offset={8}>
          col - 6 | offset - 8
        </Grid.Col>
        <Grid.Col span={6} offset={4}>
          col - 6 | offset - 4
        </Grid.Col>
      </Grid.Row>
      <Grid.Row className="grid-demo" style={{ backgroundColor: 'var(--color-fill-2)' }}>
        <Grid.Col span={12} offset={8}>
          col - 12 | offset - 8
        </Grid.Col>
      </Grid.Row>
    </div>
  );
}
