// packages/docs/site/src/demos/alert/tip-type.tsx
import { Alert, Grid } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Grid.Row gutter={40}>
        <Grid.Col span={12}>
          <Alert style={{ marginBottom: 20 }} type="info" content="Here is an info text" />
          <Alert type="warning" content="Here is a warning text" />
        </Grid.Col>
        <Grid.Col span={12}>
          <Alert style={{ marginBottom: 20 }} type="success" content="Here is a success text" />
          <Alert type="error" content="Here is an error text" />
        </Grid.Col>
      </Grid.Row>
    </div>
  );
}

// packages/docs/site/src/demos/alert/tip-type.vue
<template>
  <Row :gutter="[40, 20]">
    <Col :span="12">
      <Alert>This is an info alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="success">This is an success alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="warning">This is an warning alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="error">This is an error alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="normal">
        <template #icon>
          <icon-exclamation-circle-fill />
        </template>
        This is an normal alert.
      </Alert>
    </Col>
  </Row>
</template>

<script setup lang="ts">
import { IconExclamationCircleFill } from '@sbux/starbucks-design-vue/icon';
</script>
