// packages/docs/site/src/demos/menu/dark-nav.tsx
import { Menu } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div className="menu-demo">
      <Menu mode="horizontal" theme="dark" defaultSelectedKeys={['1']}>
        <Menu.Item key="0" style={{ padding: 0, marginRight: 38 }} disabled>
          <div
            style={{
              width: 80,
              height: 30,
              background: 'var(--color-fill-3)',
              cursor: 'text',
            }}
          />
        </Menu.Item>
        <Menu.Item key="1">Home</Menu.Item>
        <Menu.Item key="2">Solution</Menu.Item>
        <Menu.Item key="3">Cloud Service</Menu.Item>
        <Menu.Item key="4">Cooperation</Menu.Item>
      </Menu>
    </div>
  );
}

// packages/docs/site/src/demos/menu/dark-nav.vue
<template>
  <div class="menu-demo">
    <Menu mode="horizontal" theme="dark" :default-selected-keys="['1']">
      <MenuItem
        key="0"
        :style="{ padding: 0, marginRight: '38px' }"
        disabled
      >
        <div
          :style="{
            width: '80px',
            height: '30px',
            background: 'var(--color-fill-3)',
            cursor: 'text',
          }"
        />
      </MenuItem>
      <MenuItem key="1">Home</MenuItem>
      <MenuItem key="2">Solution</MenuItem>
      <MenuItem key="3">Cloud Service</MenuItem>
      <MenuItem key="4">Cooperation</MenuItem>
    </Menu>
  </div>
</template>
<style scoped>
.menu-demo {
  box-sizing: border-box;
  width: 100%;
  padding: 40px;
  background-color: var(--color-neutral-2);
}
</style>
