// packages/docs/vue/components/data-entry/demos/input/search-box-loading.vue
<template>
  <Space direction="vertical" size="large">
    <InputSearch
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      loading
    />
    <InputSearch
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      search-button
      loading
    />
  </Space>
</template>

// packages/docs/site/src/demos/input/search-box-loading.tsx
import { Input, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space wrap>
      <Input.Search loading placeholder="Enter keyword to search" style={{ width: 350 }} />
      <Input.Search
        searchButton
        loading
        defaultValue="Search content"
        placeholder="Enter keyword to search"
        style={{ width: 350 }}
      />
      <Input.Search
        searchButton="Search"
        loading
        defaultValue="Search content"
        placeholder="Enter keyword to search"
        style={{ width: 350 }}
      />
    </Space>
  );
}
