// packages/docs/vue/components/data-entry/demos/date-picker/custom-date-cell.vue
<template>
  <DatePicker>
    <template #cell="{ date }">
      <div class="arco-picker-date">
        <div class="arco-picker-date-value" :style="getCellStyle(date)">
          {{ date.getDate() }}
        </div>
      </div>
    </template>
  </DatePicker>
</template>
<script setup lang="ts">
const highlightDates = [6, 14, 22];
const highlightStyle = {
  border: '1px solid rgb(var(--arcoblue-6))',
};

const getCellStyle = (date) => {
  return highlightDates.includes(date.getDate()) ? highlightStyle : {};
};
</script>

// packages/docs/site/src/demos/date-picker/custom-date-cell.tsx
import { DatePicker } from '@sbux/starbucks-design-react';

export default function Demo() {
  const highlightStyle = {
    border: '1px solid rgb(var(--arcoblue-6))',
  };

  return (
    <DatePicker
      dateRender={(current) => {
        const date = current.date();
        const highlightDates = [6, 14, 22];
        return (
          <div className="arco-picker-date">
            <div
              className="arco-picker-date-value"
              style={highlightDates.indexOf(date) > -1 ? highlightStyle : {}}
            >
              {current.date()}
            </div>
          </div>
        );
      }}
      style={{ width: 200 }}
    />
  );
}
