// packages/docs/vue/components/data-entry/demos/date-picker/datetime-picker.vue
<template>
  <DatePicker
    style="width: 220px; margin: 0 24px 24px 0;"
    show-time
    :time-picker-props="{ defaultValue: '09:09:06' }"
    format="YYYY-MM-DD HH:mm:ss"
    @change="handleChange"
    @select="handleSelect"
    @ok="handleOk"
  />
  <DatePicker
    style="width: 220px; margin: 0 24px 24px 0;"
    show-time
    format="YYYY-MM-DD hh:mm"
    @change="handleChange"
    @select="handleSelect"
    @ok="handleOk"
  />
  <RangePicker
    style="width: 360px; margin: 0 24px 24px 0;"
    show-time
    :time-picker-props="{ defaultValue: ['00:00:00', '09:09:06'] }"
    format="YYYY-MM-DD HH:mm"
    @change="handleChange"
    @select="handleSelect"
    @ok="handleOk"
  />
</template>
<script setup lang="ts">
function handleSelect(dateString, date) {
  console.log('handleSelect', dateString, date);
}

function handleChange(dateString, date) {
  console.log('handleChange: ', dateString, date);
}

function handleOk(dateString, date) {
  console.log('handleOk: ', dateString, date);
}
</script>

// packages/docs/site/src/demos/date-picker/datetime-picker.tsx
import { DatePicker } from '@sbux/starbucks-design-react';

export default function Demo() {
  const style = {
    width: 220,
    margin: '0 24px 24px 0',
  };

  function onSelect(dateString, date) {
    console.log('onSelect', dateString, date);
  }

  function onChange(dateString, date) {
    console.log('onChange: ', dateString, date);
  }

  function onOk(dateString, date) {
    console.log('onOk: ', dateString, date);
  }

  return (
    <div>
      <DatePicker
        style={style}
        showTime={{
          defaultValue: '04:05:06',
        }}
        format="YYYY-MM-DD HH:mm:ss"
        onChange={onChange}
        onSelect={onSelect}
        onOk={onOk}
      />
      <DatePicker
        style={style}
        showTime
        format="YYYY-MM-DD hh:mm A"
        onChange={onChange}
        onSelect={onSelect}
        onOk={onOk}
      />
      <DatePicker.RangePicker
        style={{ ...style, width: 360 }}
        showTime={{
          defaultValue: ['00:00', '04:05'],
          format: 'HH:mm',
        }}
        format="YYYY-MM-DD HH:mm"
        onChange={onChange}
        onSelect={onSelect}
        onOk={onOk}
      />
    </div>
  );
}
