// packages/docs/vue/components/data-entry/demos/date-picker/hide-gray-dates.vue
<template>
  <Space direction="vertical">
    <Space>
      <DatePicker style="width: 260px" />
      <DatePicker style="width: 260px" hide-not-in-view-dates />
    </Space>
    <Space>
      <RangePicker style="width: 360px" />
      <RangePicker style="width: 360px" hide-not-in-view-dates />
    </Space>
  </Space>
</template>

// packages/docs/site/src/demos/date-picker/hide-gray-dates.tsx
import { DatePicker, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space direction="vertical">
      <Space>
        <DatePicker style={{ width: 260 }} />
        <DatePicker style={{ width: 260 }} hideNotInViewDates />
      </Space>
      <Space>
        <DatePicker.RangePicker style={{ width: 360 }} />
        <DatePicker.RangePicker style={{ width: 360 }} hideNotInViewDates />
      </Space>
    </Space>
  );
}
