// packages/docs/site/src/demos/date-picker/prefix.vue
<template>
  <div>
    <div>
      <DatePicker style="width: 300px;">
        <template #prefix>
          <IconInfoCircle />
        </template>
      </DatePicker>
    </div>
    <RangePicker
      showTime
      :defaultValue="['2019-08-08 00:00:00', '2019-08-18 00:00:00']"
      :style="{ width: '400px', marginTop: '20px' }"
    >
      <template #prefix>
        <IconInfoCircle />
      </template>
    </RangePicker>
  </div>
</template>

<script setup lang="ts">
import { IconInfoCircle } from '@sbux/starbucks-design-vue/icon';
</script>

// packages/docs/site/src/demos/date-picker/prefix.tsx
import { DatePicker, Space } from '@sbux/starbucks-design-react';
import { IconInfoCircle } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <Space>
      <DatePicker style={{ width: 200 }} prefix={<IconInfoCircle />}/>
      <DatePicker.RangePicker style={{ width: 350 }} prefix={<IconInfoCircle />}/>
    </Space>
  );
}
