// packages/docs/site/src/demos/date-picker/v-model.vue
<template>
  <Space>
    <DatePicker v-model="value" style="width: 200px;" />
    <RangePicker v-model="rangeValue" style="width: 300px;" />
  </Space>
</template>
<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const state = reactive({
  value: Date.now(),
  rangeValue: [Date.now(), Date.now()],
});

const { value, rangeValue } = toRefs(state);
</script>

// packages/docs/site/src/demos/date-picker/v-model.tsx
import { useState, useEffect } from 'react';
import { DatePicker, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [value, setValue] = useState();
  const [valueRange, setValueRange] = useState();
  useEffect(() => {
    setValue(Date.now());
    setValueRange([Date.now(), Date.now()]);
  }, []);
  return (
    <Space>
      <DatePicker
        showTime
        value={value}
        onChange={(v) => setValue(v)}
        style={{ width: 200 }}
      />
      <DatePicker.RangePicker
        showTime
        value={valueRange}
        onChange={(v) => setValueRange(v)}
        style={{ width: 380 }}
      />
    </Space>
  );
}
