// packages/docs/site/src/demos/config-provider/custom-empty.tsx
import { ConfigProvider, Space, Cascader, Select, TreeSelect, List, Table, Empty, Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  function renderEmpty(componentName) {
    switch (componentName) {
      case 'Cascader':
        return <Typography.Text>Cascader no data!</Typography.Text>;

      case 'Select':
        return <Typography.Text>Select no data!</Typography.Text>;

      case 'TreeSelect':
        return <Typography.Text>TreeSelect no data!</Typography.Text>;

      case 'List':
        return <Empty description="List no data!" />;

      case 'Table':
        return <Empty description="Table no data!" />;

      default:
        return <Empty />;
    }
  }
  return (
    <ConfigProvider renderEmpty={renderEmpty}>
      <Space>
        <Cascader style={{ width: 200 }} placeholder="Cascader" />
        <Select style={{ width: 200 }} placeholder="Select" />
        <TreeSelect style={{ width: 200 }} placeholder="TreeSelect" />
      </Space>
      <List header="Empty List" style={{ marginTop: 20 }}/>
      <Table
        data={[]}
        columns={[
          {
            title: 'Name',
            key: 'name',
          },
          {
            title: 'Age',
            key: 'age',
          },
        ]}
        style={{ marginTop: 20 }} />
    </ConfigProvider>
  );
}

// packages/docs/site/src/demos/config-provider/custom-empty.vue
<template>
  <ConfigProvider>
    <template #empty="scope">
      <Empty
        v-if="scope?.component === 'cascader'"
        description="cascader no data!"
        in-config-provider
      >
      </Empty>
      <Empty
        v-else-if="scope?.component === 'select'"
        description="select no data!"
        in-config-provider
      ></Empty>
      <Empty
        v-else-if="scope?.component === 'tree-select'"
        description="tree-select no data!"
        in-config-provider
      ></Empty>
      <Empty
        v-else-if="scope?.component === 'list'"
        description="list no data!"
        in-config-provider
      ></Empty>
      <Empty
        v-else-if="scope?.component === 'table'"
        description="table no data!"
        in-config-provider
      ></Empty>
      <div v-else class="my-empty">
        <icon-trophy />
      </div>
    </template>
    <Space direction="vertical" fill>
      <Cascader :options="[]" placeholder="cascader" allow-search />
      <Select placeholder="select" allow-search />
      <TreeSelect placeholder="tree-select" />
      <List>
        <template #header> Empty List </template>
      </List>
      <Table :columns="columns" :data="[]" />
      <Empty></Empty>
    </Space>
  </ConfigProvider>
</template>

<script setup lang="ts">
import { IconTrophy } from '@sbux/starbucks-design-vue/icon';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
  {
    title: 'Email',
    dataIndex: 'email',
  },
];
</script>

<style>
.my-empty {
  padding: 20px;
  width: 100%;
  text-align: center;
  box-sizing: border-box;
}
</style>
