// packages/docs/site/src/demos/typography/title.vue
<template>
  <Typography>
    <TypographyTitle> H1. Starbucks Design </TypographyTitle>
    <TypographyTitle :heading="2"> H2. 品牌体验设计 </TypographyTitle>
    <TypographyTitle :heading="3"> H3. 组件资产沉淀 </TypographyTitle>
    <TypographyTitle :heading="4"> H4. 门店运营场景 </TypographyTitle>
    <TypographyTitle :heading="5"> H5. 交付链路协作 </TypographyTitle>
    <TypographyTitle :heading="6"> H6. 内容说明标题 </TypographyTitle>
  </Typography>
</template>

// packages/docs/site/src/demos/typography/title.tsx
import { Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Typography>
      <Typography.Title>H1. Starbucks Design</Typography.Title>
      <Typography.Title heading={2}>H2. 品牌体验设计</Typography.Title>
      <Typography.Title heading={3}>H3. 组件资产沉淀</Typography.Title>
      <Typography.Title heading={4}>H4. 门店运营场景</Typography.Title>
      <Typography.Title heading={5}>H5. 交付链路协作</Typography.Title>
      <Typography.Title heading={6}>H6. 内容说明标题</Typography.Title>
    </Typography>
  );
}
