// packages/docs/vue/components/general/demos/typography/title.vue
<template>
  <Typography>
    <TypographyTitle> H1. The Pragmatic Romanticism </TypographyTitle>
    <TypographyTitle :heading="2">
      H2. The Pragmatic Romanticism
    </TypographyTitle>
    <TypographyTitle :heading="3">
      H3. The Pragmatic Romanticism
    </TypographyTitle>
    <TypographyTitle :heading="4">
      H4. The Pragmatic Romanticism
    </TypographyTitle>
    <TypographyTitle :heading="5">
      H5. The Pragmatic Romanticism
    </TypographyTitle>
    <TypographyTitle :heading="6">
      H6. The Pragmatic Romanticism
    </TypographyTitle>
  </Typography>
</template>

// packages/docs/site/src/demos/typography/title.tsx
import { Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Typography>
      <Typography.Title>H1. The Pragmatic Romanticism</Typography.Title>
      <Typography.Title heading={2}>H2. The Pragmatic Romanticism</Typography.Title>
      <Typography.Title heading={3}>H3. The Pragmatic Romanticism</Typography.Title>
      <Typography.Title heading={4}>H4. The Pragmatic Romanticism</Typography.Title>
      <Typography.Title heading={5}>H5. The Pragmatic Romanticism</Typography.Title>
      <Typography.Title heading={6}>H6. The Pragmatic Romanticism</Typography.Title>
    </Typography>
  );
}
