// packages/docs/vue/components/data-display/demos/tag/bordered-tag.vue
<template>
  <Space wrap>
    <Tag bordered>default</Tag>
    <Tag
      v-for="(color, index) of colors"
      :key="index"
      :color="color"
      bordered
      >{{ color }}</Tag
    >
  </Space>
</template>

<script setup lang="ts">
const colors = [
  'orangered',
  'orange',
  'gold',
  'lime',
  'green',
  'cyan',
  'blue',
  'arcoblue',
  'purple',
  'pinkpurple',
  'magenta',
  'gray',
];
</script>

// packages/docs/site/src/demos/tag/bordered-tag.tsx
import { Space, Tag } from '@sbux/starbucks-design-react';

export default function Demo() {
  const COLORS = [
    'red',
    'orangered',
    'orange',
    'gold',
    'lime',
    'green',
    'cyan',
    'blue',
    'arcoblue',
    'purple',
    'pinkpurple',
    'magenta',
    'gray',
  ];

  return (
    <Space wrap>
      <Tag bordered>Default</Tag>
      {COLORS.map((color, i) => (
        <Tag key={i} color={color} bordered>
          {color}
        </Tag>
      ))}
    </Space>
  );
}
