// packages/docs/site/src/demos/tag/dynamic-edit-tag.tsx
import { useState } from 'react';
import { Input, Space, Tag } from '@sbux/starbucks-design-react';
import { IconPlus } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const [tags, setTags] = useState(['Tag 1', 'Tag 2', 'Tag 3']);
  const [showInput, setShowInput] = useState(false);
  const [inputValue, setInputValue] = useState('');

  function addTag() {
    if (inputValue) {
      tags.push(inputValue);
      setTags(tags);
      setInputValue('');
    }

    setShowInput(false);
  }

  function removeTag(removeTag) {
    const newTags = tags.filter((tag) => tag !== removeTag);
    setTags(newTags);
  }

  return (
    <Space size={20}>
      {tags.map((tag, index) => {
        return (
          <Tag
            key={tag}
            closable={index !== 0}
            onClose={() => removeTag(tag)}
          >
            {tag}
          </Tag>
        );
      })}
      {showInput ? (
        <Input
          autoFocus
          size="mini"
          value={inputValue}
          style={{ width: 84 }}
          onPressEnter={addTag}
          onBlur={addTag}
          onChange={setInputValue}
        />
      ) : (
        <Tag
          icon={<IconPlus />}
          style={{
            width: 84,
            backgroundColor: 'var(--color-fill-2)',
            border: '1px dashed var(--color-fill-3)',
            cursor: 'pointer',
          }}
          className="add-tag"
          tabIndex={0}
          onClick={() => setShowInput(true)}
          onKeyDown={e => {
            const keyCode = e.keyCode || e.which;
            if (keyCode === 13) { // enter
              setShowInput(true)
            }
          }}
        >
          Add Tag
        </Tag>
      )}
    </Space>
  );
}

// packages/docs/site/src/demos/tag/dynamic-edit-tag.vue
<template>
  <Space wrap>
    <Tag
      v-for="(tag, index) of tags"
      :key="tag"
      :closable="index !== 0"
      @close="handleRemove(tag)"
    >
      {{ tag }}
    </Tag>

    <Input
      v-if="showInput"
      ref="inputRef"
      :style="{ width: '90px' }"
      size="mini"
      v-model.trim="inputVal"
      @keyup.enter="handleAdd"
      @blur="handleAdd"
    />
    <Tag
      v-else
      :style="{
        width: '90px',
        backgroundColor: 'var(--color-fill-2)',
        border: '1px dashed var(--color-fill-3)',
        cursor: 'pointer',
      }"
      @click="handleEdit"
    >
      <template #icon>
        <icon-plus />
      </template>
      Add Tag
    </Tag>
  </Space>
</template>

<script setup lang="ts">
import { ref, nextTick } from 'vue';
import { IconPlus } from '@sbux/starbucks-design-vue/icon';

const tags = ref(['Tag 1', 'Tag 2', 'Tag 3']);
const inputRef = ref(null);
const showInput = ref(false);
const inputVal = ref('');

const handleEdit = () => {
  showInput.value = true;

  nextTick(() => {
    if (inputRef.value) {
      inputRef.value.focus();
    }
  });
};

const handleAdd = () => {
  if (inputVal.value) {
    tags.value.push(inputVal.value);
    inputVal.value = '';
  }
  showInput.value = false;
};

const handleRemove = (key) => {
  tags.value = tags.value.filter((tag) => tag !== key);
};
</script>
