// packages/docs/site/src/demos/layout/responsive-sidebar.tsx
import React from 'react';
import { Layout, Menu, Message, Breadcrumb } from '@sbux/starbucks-design-react';
import { IconHome, IconCalendar } from '@sbux/starbucks-design-react/icon';

export default class Demo extends React.Component {
  state = {
    collapsed: false,
  };
  onCollapse = (collapsed, type) => {
    const content = type === 'responsive' ? '触发响应式收缩' : '点击触发收缩';
    Message.info({
      content,
      duration: 2000,
    });
    this.setState({
      collapsed,
    });
  };

  render() {
    function BaseMenu(props) {
      return (
        <Menu defaultOpenKeys={['1']} defaultSelectedKeys={['0_2']} {...props}>
          <Menu.Item key="0_1" disabled>
            <IconHome />
            Menu 1
          </Menu.Item>
          <Menu.Item key="0_2">
            <IconCalendar />
            Menu 2
          </Menu.Item>
          <Menu.SubMenu
            key="1"
            title={
              <span>
                <IconCalendar />
                Navigation 1
              </span>
            }
          >
            <Menu.Item key="1_1">Menu 1</Menu.Item>
            <Menu.Item key="1_2">Menu 2</Menu.Item>
            <Menu.SubMenu key="2" title="Navigation 2">
              <Menu.Item key="2_1">Menu 1</Menu.Item>
              <Menu.Item key="2_2">Menu 2</Menu.Item>
            </Menu.SubMenu>
            <Menu.SubMenu key="3" title="Navigation 3">
              <Menu.Item key="3_1">Menu 1</Menu.Item>
              <Menu.Item key="3_2">Menu 2</Menu.Item>
              <Menu.Item key="3_3">Menu 3</Menu.Item>
            </Menu.SubMenu>
          </Menu.SubMenu>
          <Menu.SubMenu
            key="4"
            title={
              <span>
                <IconCalendar />
                Navigation 4
              </span>
            }
          >
            <Menu.Item key="4_1">Menu 1</Menu.Item>
            <Menu.Item key="4_2">Menu 2</Menu.Item>
            <Menu.Item key="4_3">Menu 3</Menu.Item>
          </Menu.SubMenu>
        </Menu>
      );
    }
    return (
      <Layout className="layout-collapse-demo">
        <Layout.Sider
          theme="dark"
          breakpoint="lg"
          onCollapse={this.onCollapse}
          collapsed={this.state.collapsed}
          width={220}
          collapsible
        >
          <div className="logo" />
          <BaseMenu
            onClickMenuItem={(key) =>
              Message.info({
                content: `You select ${key}`,
                showIcon: true,
              })
            }
            theme="dark"
            style={{ width: '100%' }}
          />
        </Layout.Sider>
        <Layout>
          <Layout.Header>
            <BaseMenu mode="horizontal" />
          </Layout.Header>
          <Layout style={{ padding: '0 24px' }}>
            <Breadcrumb style={{ margin: '16px 0' }}>
              <Breadcrumb.Item>Home</Breadcrumb.Item>
              <Breadcrumb.Item>List</Breadcrumb.Item>
              <Breadcrumb.Item>App</Breadcrumb.Item>
            </Breadcrumb>
            <Layout.Content>Content</Layout.Content>
            <Layout.Footer>Footer</Layout.Footer>
          </Layout>
        </Layout>
      </Layout>
    );
  }
}

// packages/docs/vue/components/layout/demos/layout/responsive-sidebar.vue
<template>
  <Layout class="layout-demo">
    <LayoutSider
      theme="dark"
      breakpoint="lg"
      :width="220"
      collapsible
      :collapsed="collapsed"
      @collapse="handleCollapse"
    >
      <div class="logo" />
      <Menu
        :defaultOpenKeys="['1']"
        :defaultSelectedKeys="['0_2']"
        @menuItemClick="handleClickMenuItem"
      >
        <MenuItem key="0_1" disabled>
          <IconHome />
          Menu 1
        </MenuItem>
        <MenuItem key="0_2">
          <IconCalendar />
          Menu 2
        </MenuItem>
        <SubMenu key="1">
          <template #title>
            <span><IconCalendar />Navigation 1</span>
          </template>
          <MenuItem key="1_1">Menu 1</MenuItem>
          <MenuItem key="1_2">Menu 2</MenuItem>
          <SubMenu key="2" title="Navigation 2">
            <MenuItem key="2_1">Menu 1</MenuItem>
            <MenuItem key="2_2">Menu 2</MenuItem>
          </SubMenu>
          <SubMenu key="3" title="Navigation 3">
            <MenuItem key="3_1">Menu 1</MenuItem>
            <MenuItem key="3_2">Menu 2</MenuItem>
            <MenuItem key="3_3">Menu 3</MenuItem>
          </SubMenu>
        </SubMenu>
        <SubMenu key="4">
          <template #title>
            <span><IconCalendar />Navigation 4</span>
          </template>
          <MenuItem key="4_1">Menu 1</MenuItem>
          <MenuItem key="4_2">Menu 2</MenuItem>
          <MenuItem key="4_3">Menu 3</MenuItem>
        </SubMenu>
      </Menu>
    </LayoutSider>
    <Layout>
      <LayoutHeader>
        <Menu :openKeys="['1']" :selectedKeys="['0_2']" mode="horizontal">
          <MenuItem key="0_1" disabled>
            <IconHome />
            Menu 1
          </MenuItem>
          <MenuItem key="0_2">
            <IconCalendar />
            Menu 2
          </MenuItem>
          <SubMenu key="1">
            <template #title>
              <span><IconCalendar />Navigation 1</span>
            </template>
            <MenuItem key="1_1">Menu 1</MenuItem>
            <MenuItem key="1_2">Menu 2</MenuItem>
            <SubMenu key="2" title="Navigation 2">
              <MenuItem key="2_1">Menu 1</MenuItem>
              <MenuItem key="2_2">Menu 2</MenuItem>
            </SubMenu>
            <SubMenu key="3" title="Navigation 3">
              <MenuItem key="3_1">Menu 1</MenuItem>
              <MenuItem key="3_2">Menu 2</MenuItem>
              <MenuItem key="3_3">Menu 3</MenuItem>
            </SubMenu>
          </SubMenu>
          <SubMenu key="4">
            <template #title>
              <span><IconCalendar />Navigation 4</span>
            </template>
            <MenuItem key="4_1">Menu 1</MenuItem>
            <MenuItem key="4_2">Menu 2</MenuItem>
            <MenuItem key="4_3">Menu 3</MenuItem>
          </SubMenu>
        </Menu>
      </LayoutHeader>
      <Layout style="padding: 0 24px">
        <Breadcrumb :style="{ margin: '16px 0' }">
          <BreadcrumbItem>Home</BreadcrumbItem>
          <BreadcrumbItem>List</BreadcrumbItem>
          <BreadcrumbItem>App</BreadcrumbItem>
        </Breadcrumb>
        <LayoutContent>Content</LayoutContent>
        <LayoutFooter>Footer</LayoutFooter>
      </Layout>
    </Layout>
  </Layout>
</template>
<script setup lang="ts">
import { defineComponent, ref } from 'vue';
import { Message } from '@arco-design/web-vue';
import {
  IconHome,
  IconCalendar,
} from '@arco-design/web-vue/es/icon';

const collapsed = ref(false);
const handleCollapse = (val, type) => {
  const content = type === 'responsive' ? '触发响应式收缩' : '点击触发收缩';
  Message.info({
    content,
    duration: 2000,
  });
  collapsed.value = val;
};

const handleClickMenuItem = (key: string) => {
  Message.info({ content: `You select ${key}`, showIcon: true });
};
</script>
<style scoped>
.layout-demo {
  height: 500px;
  background: var(--color-fill-2);
  border: 1px solid var(--color-border);
}
.layout-demo :deep(.arco-layout-sider) .logo {
  height: 32px;
  margin: 12px 8px;
  background: rgba(255, 255, 255, 0.2);
}
.layout-demo :deep(.arco-layout-sider-light) .logo {
  background: var(--color-fill-2);
}
.layout-demo :deep(.arco-layout-header) {
  height: 64px;
  line-height: 64px;
  background: var(--color-bg-3);
}
.layout-demo :deep(.arco-layout-footer) {
  height: 48px;
  color: var(--color-text-2);
  font-weight: 400;
  font-size: 14px;
  line-height: 48px;
}
.layout-demo :deep(.arco-layout-content) {
  color: var(--color-text-2);
  font-weight: 400;
  font-size: 14px;
  background: var(--color-bg-3);
}
.layout-demo :deep(.arco-layout-footer),
.layout-demo :deep(.arco-layout-content) {
  display: flex;
  flex-direction: column;
  justify-content: center;
  color: var(--color-white);
  font-size: 16px;
  font-stretch: condensed;
  text-align: center;
}
</style>
