// packages/docs/vue/components/data-entry/demos/verification-code/status-variants.vue
<template>
  <Space direction="vertical">
    <Space>
      <TypographyText style="width: 80px">Disabled:</TypographyText>
      <VerificationCode
        defaultValue="123456"
        style="width: 300px"
        disabled
      />
    </Space>
    <Space>
      <TypographyText style="width: 80px">Readonly:</TypographyText>
      <VerificationCode
        defaultValue="123456"
        style="width: 300px"
        readonly
      />
    </Space>
    <Space>
      <TypographyText style="width: 80px">Error:</TypographyText>
      <VerificationCode defaultValue="123456" style="width: 300px" error />
    </Space>
  </Space>
</template>

// packages/docs/site/src/demos/verification-code/status-variants.tsx
import { Space, Typography, VerificationCode } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Space>
        <div style={{width: 80}}>
          <Typography.Text >Disabled</Typography.Text>
        </div>
        <VerificationCode defaultValue={'123456'} disabled style={{width: 300}}/>
      </Space>
      <br/>
      <br/>
      <Space>
        <div style={{width: 80}}>
          <Typography.Text>ReadOnly</Typography.Text>
        </div>
        <VerificationCode defaultValue={'123456'} readOnly style={{width: 300}}/>
      </Space>
      <br/>
      <br/>
      <Space>
        <div style={{width: 80}}>
          <Typography.Text>Error</Typography.Text>
        </div>
        <VerificationCode status="error" style={{width: 300}}/>
      </Space>
    </div>
  );
}
