// packages/docs/site/src/demos/tooltip/custom-bg-color.tsx
import { Tooltip, Button } from '@sbux/starbucks-design-react';

export default function Demo() {
  const colors = ['#3491FA', '#165DFF', '#722ED1'];

  return (
    <div>
      {colors.map((color) => {
        return (
          <Tooltip key={color} color={color} content="tooltip text">
            <Button
              style={{
                marginRight: 20,
                background: color,
                color: '#fff',
              }}
            >
              {color}
            </Button>
          </Tooltip>
        );
      })}
    </div>
  );
}

// packages/docs/site/src/demos/tooltip/custom-bg-color.vue
<template>
  <Space>
    <Tooltip content="This is tooltip content" background-color="#3491FA">
      <Button>#3491FA</Button>
    </Tooltip>
    <Tooltip content="This is tooltip content" background-color="#165DFF">
      <Button>#165DFF</Button>
    </Tooltip>
    <Tooltip content="This is tooltip content" background-color="#722ED1">
      <Button>#722ED1</Button>
    </Tooltip>
  </Space>
</template>
