// packages/docs/site/src/demos/time-picker/size.tsx
import { useState } from 'react';
import { Radio, TimePicker } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [size, setSize] = useState('default');
  return (
    <div>
      <Radio.Group
        value={size}
        options={['large', 'default', 'small', 'mini']}
        onChange={(value) => setSize(value)}
        type="button"
        style={{ marginBottom: 24 }}
      />
      <br />
      <TimePicker style={{ width: 194 }} size={size} placeholder="请选择时间" />
    </div>
  );
}

// packages/docs/vue/components/data-entry/demos/time-picker/size.vue
<template>
  <div style="marginBottom: 20px">
    <RadioGroup v-model="size" type="button">
      <Radio value="mini">mini</Radio>
      <Radio value="small">small</Radio>
      <Radio value="medium">medium</Radio>
      <Radio value="large">large</Radio>
    </RadioGroup>
  </div>
  <TimePicker style="width: 194px;" :size="size" />
</template>
<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const state = reactive({
  size: 'small',
});

const { size } = toRefs(state);
</script>
