// packages/docs/site/src/demos/result/custom-status.tsx
import { Result, Button } from '@sbux/starbucks-design-react';
import { IconFaceSmileFill } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <div>
      <Result
        status={null}
        icon={<IconFaceSmileFill style={{ color: 'rgb(var(--arcoblue-6))' }} />}
        title="Your operation has been performed."
        extra={<Button type="primary">Back</Button>}
      ></Result>
    </div>
  );
}

// packages/docs/site/src/demos/result/custom-status.vue
<template>
  <Result
    :status="null"
    title="This is title content"
    subtitle="This is subtitle content"
  >
    <template #icon>
      <IconFaceSmileFill />
    </template>
    <template #extra>
      <Space>
        <Button type="secondary">Again</Button>
        <Button type="primary">Back</Button>
      </Space>
    </template>
  </Result>
</template>
<script setup lang="ts">
import { IconFaceSmileFill } from '@sbux/starbucks-design-vue/icon';
</script>
