// packages/docs/vue/components/feedback/demos/result/full-featured.vue
<template>
  <Result status="error" title="No internet ">
    <template #icon>
      <IconFaceFrownFill />
    </template>
    <template #subtitle> DNS_PROBE_FINISHED_NO_INTERNET </template>

    <template #extra>
      <Button type="primary">Refresh</Button>
    </template>
    <Typography style="background: var(--color-fill-2); padding: 24px;">
      <TypographyParagraph>Try:</TypographyParagraph>
      <ul>
        <li> Checking the network cables, modem, and router </li>
        <li> Reconnecting to Wi-Fi </li>
      </ul>
    </Typography>
  </Result>
</template>

<script setup lang="ts">
import { IconFaceFrownFill } from '@arco-design/web-vue/es/icon';
</script>

// packages/docs/site/src/demos/result/full-featured.tsx
import { Result, Button, Typography } from '@sbux/starbucks-design-react';
import { IconFaceFrownFill } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <div>
      <Result
        status="error"
        icon={<IconFaceFrownFill />}
        title="No internet"
        subTitle="DNS_PROBE_FINISHED_NO_INTERNET"
        extra={<Button type="primary">Refresh</Button>}
      >
        <Typography className="result-content" style={{ background: 'var(--color-fill-2)', padding: 24 }}>
          <Typography.Paragraph>Try:</Typography.Paragraph>
          <ul>
            <li> Checking the network cables, modem, and router </li>
            <li> Reconnecting to Wi-Fi </li>
          </ul>
        </Typography>
      </Result>
    </div>
  );
}
