// packages/docs/site/src/demos/auto-complete/custom-filter.vue
<template>
  <AutoComplete
    :data="data"
    @search="handleSearch"
    :filter-option="false"
    :style="{ width: '360px' }"
    placeholder="please enter something"
  />
</template>

<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const state = reactive({
  data: [],
});

const { data } = toRefs(state);

const handleSearch = (value) => {
  if (value) {
    data.value = [...Array(5)].map(() => Math.random().toFixed(10).slice(2));
  } else {
    data.value = [];
  }
};
</script>

// packages/docs/site/src/demos/auto-complete/custom-filter.tsx
import { useState } from 'react';
import { AutoComplete } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [data, setData] = useState([]);

  const handleSearch = (inputValue) => {
    // or fetch options from server
    setData(inputValue ? new Array(5).fill(null).map(() => Math.random().toFixed(10).slice(2)) : []);
  };

  return (
    <AutoComplete
      placeholder="Please Enter"
      onSearch={handleSearch}
      data={data}
      filterOption={false}
      style={{ width: 154, marginRight: 20 }}
    />
  );
}
