// packages/docs/site/src/demos/mentions/custom-trigger-char.vue
<template>
  <Space direction="vertical" size="large" style="width: 100%">
    <Mention
      :data="['Nink', 'Zero', 'Kevin']"
      placeholder="输入 @Nink"
    />
    <Mention
      :data="['Nink', 'Zero', 'Kevin']"
      prefix="#"
      placeholder="input #"
    />
    <Mention
      :data="['Nink', 'Zero', 'Kevin']"
      prefix="$"
      placeholder="input $"
    />
  </Space>
</template>

// packages/docs/site/src/demos/mentions/custom-trigger-char.tsx
import { Mentions, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space size={40}>
      <Mentions
        style={{ width: 154, marginBottom: 10 }}
        placeholder="输入 @Nink"
        options={['Nink', 'Zero', 'Kevin']}
      />
      <Mentions
        style={{ width: 154, marginBottom: 10 }}
        prefix="#"
        placeholder="Input #"
        options={['Nink', 'Zero', 'Kevin']}
      />
      <Mentions
        style={{ width: 154, marginBottom: 10 }}
        prefix="*"
        placeholder="Input *"
        options={['Nink', 'Zero', 'Kevin']}
      />
      <Mentions
        style={{ width: 154, marginBottom: 10 }}
        prefix="${"
        placeholder="Input ${"
        options={['Nink', 'Zero', 'Kevin']}
      />
    </Space>
  );
}
