// packages/docs/site/src/demos/popconfirm/popup-position.vue
<template>
  <div :style="{ position: 'relative', width: '440px', height: '280px' }">
    <Popconfirm content="This is a Popconfirm" position="tl">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '0', left: '70px' }"
        >TL</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="top">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '0', left: '180px' }"
        >TOP</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="tr">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '0', left: '290px' }"
        >TR</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="bl">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '240px', left: '70px' }"
        >BL</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="bottom">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '240px', left: '180px' }"
        >BOTTOM</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="br">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '240px', left: '290px' }"
        >BR</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="lt">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '60px', left: '10px' }"
        >LT</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="left">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '120px', left: '10px' }"
        >LEFT</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="lb">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '180px', left: '10px' }"
        >LB</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="rt">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '60px', left: '350px' }"
        >RT</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="right">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '120px', left: '350px' }"
        >RIGHT</Button
      >
    </Popconfirm>
    <Popconfirm content="This is a Popconfirm" position="rb">
      <Button
        class="button"
        :style="{ position: 'absolute', top: '180px', left: '350px' }"
        >RB</Button
      >
    </Popconfirm>
  </div>
</template>

<style scoped>
.button {
  width: 100px;
}
</style>

// packages/docs/site/src/demos/popover/popup-position.tsx
import { Button, Popover } from '@sbux/starbucks-design-react';

export default function Demo() {
  const style = {
    margin: 0,
  };

  function getStyle(top, left) {
    return {
      position: 'absolute',
      width: 80,
      top,
      left,
    };
  }

  const content = (
    <span>
      <p style={style}>Here is the text content</p>
      <p style={style}>Here is the text content</p>
    </span>
  );

  return (
    <div
      style={{
        position: 'relative',
        width: 440,
        height: 280,
      }}
    >
      <Popover position="tl" title="Title" content={content}>
        <Button style={getStyle(0, 70)}>TL</Button>
      </Popover>
      <Popover position="top" title="Title" content={content}>
        <Button style={getStyle(0, 180)}>Top</Button>
      </Popover>
      <Popover position="tr" title="Title" content={content}>
        <Button style={getStyle(0, 290)}>TR</Button>
      </Popover>
      <Popover position="lt" title="Title" content={content}>
        <Button style={getStyle(60, 10)}>LT</Button>
      </Popover>
      <Popover position="left" title="Title" content={content}>
        <Button style={getStyle(120, 10)}>Left</Button>
      </Popover>
      <Popover position="lb" title="Title" content={content}>
        <Button style={getStyle(180, 10)}>LB</Button>
      </Popover>
      <Popover position="rt" title="Title" content={content}>
        <Button style={getStyle(60, 350)}>RT</Button>
      </Popover>
      <Popover position="right" title="Title" content={content}>
        <Button style={getStyle(120, 350)}>Right</Button>
      </Popover>
      <Popover position="rb" title="Title" content={content}>
        <Button style={getStyle(180, 350)}>RB</Button>
      </Popover>
      <Popover position="bl" title="Title" content={content}>
        <Button style={getStyle(240, 70)}>BL</Button>
      </Popover>
      <Popover position="bottom" title="Title" content={content}>
        <Button style={getStyle(240, 180)}>Bottom</Button>
      </Popover>
      <Popover position="br" title="Title" content={content}>
        <Button style={getStyle(240, 290)}>BR</Button>
      </Popover>
    </div>
  );
}
