// packages/docs/site/src/demos/dropdown/trigger.vue
<template>
  <Space size="large">
    <Dropdown>
      <Button>Click Me</Button>
      <template #content>
        <Doption>Option 1</Doption>
        <Doption>Option 2</Doption>
        <Doption>Option 3</Doption>
      </template>
    </Dropdown>
    <Dropdown trigger="hover">
      <Button>Hover Me</Button>
      <template #content>
        <Doption>Option 1</Doption>
        <Doption>Option 2</Doption>
        <Doption>Option 3</Doption>
      </template>
    </Dropdown>
  </Space>
</template>

// packages/docs/site/src/demos/popover/trigger.tsx
import { Button, Popover, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  const style = {
    margin: 0,
  };

  return (
    <Space size={40}>
      <Popover
        trigger="hover"
        title="Title"
        content={
          <span>
            <p style={style}>Here is the text content</p>
            <p style={style}>Here is the text content</p>
          </span>
        }
      >
        <Button>Hover</Button>
      </Popover>
      <Popover
        trigger="click"
        title="Title"
        content={
          <span>
            <p style={style}>Here is the text content</p>
            <p style={style}>Here is the text content</p>
          </span>
        }
      >
        <Button>Click</Button>
      </Popover>
      <Popover
        trigger="focus"
        title="Title"
        content={
          <span>
            <p style={style}>Here is the text content</p>
            <p style={style}>Here is the text content</p>
          </span>
        }
      >
        <Button>Focus</Button>
      </Popover>
    </Space>
  );
}
