// packages/docs/site/src/demos/notification/update-notification.tsx
import { Button, Notification } from '@sbux/starbucks-design-react';

export default function Demo() {
  function updateNotification() {
    Notification.warning({
      id: 'need_update',
      title: 'Ready to update',
      content: 'Will update after 2 seconds...'
    });
    setTimeout(() => {
      Notification.success({
        id: 'need_update',
        title: 'Success',
        content: 'Update success!'
      });
    }, 2000);
  }

  return (
    <Button onClick={updateNotification} type="primary">
      Update Notification
    </Button>
  );
}

// packages/docs/vue/components/feedback/demos/notification/update-notification.vue
<template>
  <Button type="primary" @click="handleNotification">
    Open Notification
  </Button>
</template>

<script setup lang="ts">
import { Notification } from '@arco-design/web-vue';

const handleNotification = () => {
  Notification.warning({
    id: 'your_id',
    title: 'Ready to update',
    content: 'Will update after 2 seconds...',
  });

  setTimeout(() => {
    Notification.success({
      id: 'your_id',
      title: 'Success',
      content: 'Update success!',
    });
  }, 2000);
};
</script>
