// packages/docs/site/src/demos/space/alignment.tsx
import { useState } from 'react';
import { Space, Button, Radio, Typography, Card } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [align, setAlign] = useState('center');
  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <Radio.Group
          options={['start', 'center', 'end', 'baseline']}
          value={align}
          onChange={(value) => setAlign(value)}
          type="button"
        />
      </div>
      <Space
        align={align}
        style={{ backgroundColor: 'var(--color-fill-2)', padding: 10 }}
      >
        <Typography.Text>Space:</Typography.Text>
        <Button type="primary">Item2</Button>
        <Card title="Card">Card content</Card>
      </Space>
    </div>
  );
}

// packages/docs/site/src/demos/space/alignment.vue
<template>
  <div>
    <div style="marginBottom: 20px">
      <RadioGroup v-model="align" type="button">
        <Radio value="start">start</Radio>
        <Radio value="center">center</Radio>
        <Radio value="end">end</Radio>
        <Radio value="baseline">baseline</Radio>
      </RadioGroup>
    </div>
    <Space
      :align="align"
      style="backgroundColor: var(--color-fill-2);padding: 10px;"
    >
      <TypographyText>Space:</TypographyText>
      <Button type="primary">Item2</Button>
      <Card title="Card"> Card content </Card>
    </Space>
  </div>
</template>
<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const state = reactive({
  align: 'center',
});

const { align } = toRefs(state);
</script>
