// packages/docs/site/src/demos/breadcrumb/show-ellipsis.tsx
import { Breadcrumb } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Breadcrumb maxCount="3">
        <Breadcrumb.Item>Home</Breadcrumb.Item>
        <Breadcrumb.Item>Sub Home</Breadcrumb.Item>
        <Breadcrumb.Item>All Channel</Breadcrumb.Item>
        <Breadcrumb.Item>Channel</Breadcrumb.Item>
        <Breadcrumb.Item>News</Breadcrumb.Item>
      </Breadcrumb>
    </div>
  );
}

// packages/docs/site/src/demos/breadcrumb/show-ellipsis.vue
<template>
  <Space direction="vertical">
    <Breadcrumb :max-count="3">
      <BreadcrumbItem>Home</BreadcrumbItem>
      <BreadcrumbItem>Sub Home</BreadcrumbItem>
      <BreadcrumbItem>All Channel</BreadcrumbItem>
      <BreadcrumbItem>Channel</BreadcrumbItem>
      <BreadcrumbItem>News</BreadcrumbItem>
      <BreadcrumbItem>Post</BreadcrumbItem>
    </Breadcrumb>
    <Breadcrumb :max-count="3">
      <template #more-icon>
        <Tooltip content="more routes a/b/c">
          <icon-more />
        </Tooltip>
      </template>
      <BreadcrumbItem>Home</BreadcrumbItem>
      <BreadcrumbItem>Sub Home</BreadcrumbItem>
      <BreadcrumbItem>All Channel</BreadcrumbItem>
      <BreadcrumbItem>Channel</BreadcrumbItem>
      <BreadcrumbItem>News</BreadcrumbItem>
      <BreadcrumbItem>Post</BreadcrumbItem>
    </Breadcrumb>
  </Space>
</template>

<script setup lang="ts">
import { IconMore } from '@sbux/starbucks-design-vue/icon';
</script>
