// packages/docs/vue/components/data-entry/demos/form/async-validation.vue
<template>
  <Form ref="formRef" :model="form" :style="{ width: '600px' }">
    <FormItem field="name" label="Username" :rules="rules">
      <Input
        v-model="form.name"
        placeholder="please enter your username..."
      />
    </FormItem>
    <FormItem field="post" label="Post">
      <Input v-model="form.post" placeholder="please enter your post..." />
    </FormItem>
    <FormItem field="isRead">
      <Checkbox v-model="form.isRead"> I have read the manual </Checkbox>
    </FormItem>
    <FormItem>
      <Button @click="handleClick">Set Status</Button>
    </FormItem>
  </Form>
  {{ form }}
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';

const formRef = ref();
const form = reactive({
  name: '',
  post: '',
  isRead: false,
});
const rules = [
  {
    validator: (value, cb) => {
      return new Promise((resolve) => {
        window.setTimeout(() => {
          if (value !== 'admin') {
            cb('name must be admin');
          }
          resolve();
        }, 2000);
      });
    },
  },
];
const handleClick = () => {
  formRef.value.setFields({
    name: {
      status: 'error',
      message: 'async name error',
    },
    post: {
      status: 'error',
      message: 'valid post',
    },
  });
};
</script>

// packages/docs/site/src/demos/form/async-validation.tsx
import { Form, Input, Button, Message } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [form] = Form.useForm();
  return (
    <Form
      form={form}
      autoComplete="off"
      style={{
        width: 600,
      }}

    >
      <Form.Item
        label="Username"
        field="name"
        required
        hasFeedback
        rules={[
          {
            validator: async (value, callback) => {
              return new Promise((resolve) => {
                if (value !== 'admin') {
                  setTimeout(() => {
                    callback('Name must be admin');
                    resolve();
                  }, 1000);
                } else {
                  resolve();
                }
              });
            },
          },
        ]}
      >
        <Input placeholder="please enter your username"  />
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 5 }}>
        <Button
          type="primary"
          htmlType="submit"
          style={{ marginRight: 24 }}
        >
          Submit
        </Button>
        <Button
          style={{ marginRight: 24 }}
          onClick={() => {
            form.resetFields();
          }}
        >
          Reset
        </Button>
      </Form.Item>
    </Form>
  );
}
