// packages/docs/site/src/demos/form/async-validation.tsx
import { Form, Input, Button, Message, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [form] = Form.useForm();
  return (
    <Form
      form={form}
      autoComplete="off"
      style={{
        width: '100%',
      }}

    >
      <Form.Item
        label="门店名称"
        field="name"
        required
        hasFeedback
        rules={[
          {
            validator: async (value, callback) => {
              return new Promise((resolve) => {
                if (value !== '上海烘焙工坊') {
                  setTimeout(() => {
                    callback('门店名称必须为上海烘焙工坊');
                    resolve();
                  }, 1000);
                } else {
                  resolve();
                }
              });
            },
          },
        ]}
      >
        <Input placeholder="请输入门店名称"  />
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 5 }}>
        <Space size={16}>
          <Button type="primary" htmlType="submit">
            提交
          </Button>
          <Button
            onClick={() => {
              form.resetFields();
            }}
          >
            重置
          </Button>
        </Space>
      </Form.Item>
    </Form>
  );
}

// packages/docs/site/src/demos/form/async-validation.vue
<template>
  <Form ref="formRef" :model="form" :style="{ width: '100%' }">
    <FormItem field="name" label="门店名称" :rules="rules">
      <Input
        v-model="form.name"
        placeholder="请输入门店名称..."
      />
    </FormItem>
    <FormItem field="post" label="岗位">
      <Input v-model="form.post" placeholder="请输入岗位..." />
    </FormItem>
    <FormItem field="isRead">
      <Checkbox v-model="form.isRead"> 我已确认门店信息准确 </Checkbox>
    </FormItem>
    <FormItem>
      <Button @click="handleClick">设置状态</Button>
    </FormItem>
  </Form>
  {{ form }}
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue';

const formRef = ref();
const form = reactive({
  name: '',
  post: '',
  isRead: false,
});
const rules = [
  {
    validator: (value, cb) => {
      return new Promise((resolve) => {
        window.setTimeout(() => {
          if (value !== '上海烘焙工坊') {
            cb('门店名称必须为上海烘焙工坊');
          }
          resolve();
        }, 2000);
      });
    },
  },
];
const handleClick = () => {
  formRef.value.setFields({
    name: {
      status: 'error',
      message: '门店名称异步校验失败',
    },
    post: {
      status: 'error',
      message: '请确认岗位信息',
    },
  });
};
</script>
