// packages/docs/site/src/demos/table/expand-row.tsx
import { Table } from '@sbux/starbucks-design-react';
import { IconDownCircle, IconRightCircle } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
    },
    {
      title: 'Salary',
      dataIndex: 'salary',
    },
    {
      title: 'Address',
      dataIndex: 'address',
    },
    {
      title: 'Email',
      dataIndex: 'email',
    },
  ];
  const data = [
    {
      key: '1',
      name: 'Jane Doe',
      salary: 23000,
      address: '32 Park Road, London',
      email: 'jane.doe@example.com',
    },
    {
      key: '2',
      name: 'Alisa Ross',
      salary: 25000,
      address: '35 Park Road, London',
      email: 'alisa.ross@example.com',
    },
    {
      key: '3',
      name: 'Kevin Sandra',
      salary: 22000,
      address: '31 Park Road, London',
      email: 'kevin.sandra@example.com',
    },
    {
      key: '4',
      name: 'Ed Hellen',
      salary: 17000,
      address: '42 Park Road, London',
      email: 'ed.hellen@example.com',
    },
    {
      key: '5',
      name: 'William Smith',
      salary: 27000,
      address: '62 Park Road, London',
      email: 'william.smith@example.com',
    },
  ];

  return (
    <Table
      columns={columns}
      data={data}
      expandedRowRender={(record) => {
        return `This is No.${record.key} description.`;
      }}
      onExpand={(detail, expanded) => {
        console.log(detail, expanded);
      }}
      onExpandedRowsChange={(expandedRows) => {
        console.log(expandedRows);
      }}
      expandProps={{
        icon: ({ expanded }) =>
          expanded ? <IconDownCircle /> : <IconRightCircle />,
        expandRowByClick: true,
        rowExpandable: (record) => record.key !== '4',
      }}
    />
  );
}

// packages/docs/site/src/demos/table/expand-row.vue
<template>
  <Table :columns="columns" :data="data" :expandable="expandable" />
</template>

<script setup lang="ts">
import { h, reactive } from 'vue';
import { IconDownCircle, IconRightCircle } from '@sbux/starbucks-design-vue/icon';

const expandable = reactive({
  icon: (expanded: boolean) => h(expanded ? IconDownCircle : IconRightCircle),
  title: 'Expand',
  width: 80,
  expandedRowRender: (record) => {
    if (record.key === '3') {
      return `My Name is ${record.name}`;
    }
  },
});

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
  {
    title: 'Email',
    dataIndex: 'email',
  },
];

const data = reactive([
  {
    key: '1',
    name: 'Jane Doe',
    salary: 23000,
    address: '32 Park Road, London',
    email: 'jane.doe@example.com',
    expand: 'Expand Data',
  },
  {
    key: '2',
    name: 'Alisa Ross',
    salary: 25000,
    address: '35 Park Road, London',
    email: 'alisa.ross@example.com',
  },
  {
    key: '3',
    name: 'Kevin Sandra',
    salary: 22000,
    address: '31 Park Road, London',
    email: 'kevin.sandra@example.com',
  },
  {
    key: '4',
    name: 'Ed Hellen',
    salary: 17000,
    address: '42 Park Road, London',
    email: 'ed.hellen@example.com',
  },
  {
    key: '5',
    name: 'William Smith',
    salary: 27000,
    address: '62 Park Road, London',
    email: 'william.smith@example.com',
  },
]);
</script>
