// packages/docs/site/src/demos/table/fixed-column.tsx
import { Table } from '@sbux/starbucks-design-react';
import { IconDownCircle, IconRightCircle } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      fixed: 'left',
      width: 140,
    },
    {
      title: 'Address',
      dataIndex: 'address',
    },
    {
      title: 'Email',
      dataIndex: 'email',
    },
    {
      title: 'Other',
      dataIndex: 'other',
      render: () => 'Other',
    },
    {
      title: 'Other 1',
      dataIndex: 'other1',
      render: () => 'Other 1',
    },
    {
      title: 'Other 2',
      dataIndex: 'other2',
      render: () => 'Other 2',
    },
    {
      title: 'Salary',
      dataIndex: 'salary',
      fixed: 'right',
      width: 120,
    },
  ];
  const data = [
    {
      key: '1',
      name: 'Jane Doe',
      salary: 23000,
      address: '32 Park Road, London',
      email: 'jane.doe@example.com',
    },
    {
      key: '2',
      name: 'Alisa Ross',
      salary: 25000,
      address: '35 Park Road, London',
      email: 'alisa.ross@example.com',
    },
    {
      key: '3',
      name: 'Kevin Sandra',
      salary: 22000,
      address: '31 Park Road, London',
      email: 'kevin.sandra@example.com',
    },
    {
      key: '4',
      name: 'Ed Hellen',
      salary: 17000,
      address: '42 Park Road, London',
      email: 'ed.hellen@example.com',
    },
    {
      key: '5',
      name: 'William Smith',
      salary: 27000,
      address: '62 Park Road, London',
      email: 'william.smith@example.com',
    },
  ];

  return (
    <Table
      columns={columns}
      data={data}
      expandedRowRender={(record) => `${record.name}'s address is ${record.address}`}
      expandProps={{
        icon: ({ expanded }) =>
          expanded ? <IconDownCircle /> : <IconRightCircle />,
      }}
      rowSelection={{}}
      scroll={{
        x: 1600,
        y: 400,
      }}
    />
  );
}

// packages/docs/site/src/demos/table/fixed-column.vue
<template>
  <Table
    :columns="columns"
    :data="data"
    :scroll="scroll"
    :expandable="expandable"
  />
</template>

<script setup lang="ts">
import { h, reactive } from 'vue';
import { IconDownCircle, IconRightCircle } from '@sbux/starbucks-design-vue/icon';

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    fixed: 'left',
    width: 140,
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
  {
    title: 'Email',
    dataIndex: 'email',
    fixed: 'right',
    width: 200,
  },
];

const expandable = {
  icon: (expanded: boolean) => h(expanded ? IconDownCircle : IconRightCircle),
  title: 'Expand',
  width: 80,
};

const scroll = {
  x: 2000,
  y: 200,
};

const data = reactive([
  {
    key: '1',
    name: 'Jane Doe',
    salary: 23000,
    address: '32 Park Road, London',
    email: 'jane.doe@example.com',
    expand: 'Expand Content',
  },
  {
    key: '2',
    name: 'Alisa Ross',
    salary: 25000,
    address: '35 Park Road, London',
    email: 'alisa.ross@example.com',
  },
  {
    key: '3',
    name: 'Kevin Sandra',
    salary: 22000,
    address: '31 Park Road, London',
    email: 'kevin.sandra@example.com',
  },
  {
    key: '4',
    name: 'Ed Hellen',
    salary: 17000,
    address: '42 Park Road, London',
    email: 'ed.hellen@example.com',
  },
  {
    key: '5',
    name: 'William Smith',
    salary: 27000,
    address: '62 Park Road, London',
    email: 'william.smith@example.com',
  },
]);
</script>
