// packages/docs/vue/components/data-display/demos/table/sort-filter.vue
<template>
  <Space direction="vertical" size="large" fill>
    <Space>
      <Switch v-model="alignLeft" />
      <span>Filter icon align left: {{ alignLeft }}</span>
    </Space>
    <Table
      :columns="columns"
      :data="data"
      :filter-icon-align-left="alignLeft"
      @change="handleChange"
    />
  </Space>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue';

const alignLeft = ref(false);

const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    sortable: {
      sortDirections: ['ascend', 'descend'],
    },
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
    sortable: {
      sortDirections: ['ascend'],
    },
    filterable: {
      filters: [
        {
          text: '> 20000',
          value: '20000',
        },
        {
          text: '> 30000',
          value: '30000',
        },
      ],
      filter: (value, record) => record.salary > value,
      multiple: true,
    },
  },
  {
    title: 'Address',
    dataIndex: 'address',
    filterable: {
      filters: [
        {
          text: 'London',
          value: 'London',
        },
        {
          text: 'Paris',
          value: 'Paris',
        },
      ],
      filter: (value, row) => row.address.includes(value),
    },
  },
  {
    title: 'Email',
    dataIndex: 'email',
  },
];
const data = reactive([
  {
    key: '1',
    name: 'Jane Doe',
    salary: 23000,
    address: '32 Park Road, London',
    email: 'jane.doe@example.com',
  },
  {
    key: '2',
    name: 'Alisa Ross',
    salary: 25000,
    address: '35 Park Road, London',
    email: 'alisa.ross@example.com',
  },
  {
    key: '3',
    name: 'Kevin Sandra',
    salary: 22000,
    address: '31 Park Road, London',
    email: 'kevin.sandra@example.com',
  },
  {
    key: '4',
    name: 'Ed Hellen',
    salary: 17000,
    address: '42 Park Road, London',
    email: 'ed.hellen@example.com',
  },
  {
    key: '5',
    name: 'William Smith',
    salary: 27000,
    address: '62 Park Road, London',
    email: 'william.smith@example.com',
  },
]);

const handleChange = (data, extra, currentDataSource) => {
  console.log('change', data, extra, currentDataSource);
};
</script>

// packages/docs/site/src/demos/table/sort-filter.tsx
import { Table } from '@sbux/starbucks-design-react';

export default function Demo() {
  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      sorter: (a, b) => a.name.length - b.name.length,
    },
    {
      title: 'Salary',
      dataIndex: 'salary',
      sorter: (a, b) => a.salary - b.salary,
      filters: [
        {
          text: '> 20000',
          value: '20000',
        },
        {
          text: '> 30000',
          value: '30000',
        },
      ],
      defaultFilters: ['20000'],
      onFilter: (value, row) => row.salary > value,
      sortDirections: ['ascend'],
      defaultSortOrder: 'ascend',
    },
    {
      title: 'Address',
      dataIndex: 'address',
      filters: [
        {
          text: 'London',
          value: 'London',
        },
        {
          text: 'Paris',
          value: 'Paris',
        },
      ],
      onFilter: (value, row) => row.address.indexOf(value) > -1,
      filterMultiple: false,
    },
    {
      title: 'Email',
      dataIndex: 'email',
      sorter: (a, b) => a.email.length - b.email.length,
    },
  ];
  const data = [
    {
      key: '1',
      name: 'Jane Doe',
      salary: 23000,
      address: '32 Park Road, London',
      email: 'jane.doe@example.com',
    },
    {
      key: '2',
      name: 'Alisa Ross',
      salary: 25000,
      address: '35 Park Road, Paris',
      email: 'alisa.ross@example.com',
    },
    {
      key: '3',
      name: 'Kevin Sandra',
      salary: 22000,
      address: '31 Park Road, London',
      email: 'kevin.sandra@example.com',
    },
    {
      key: '4',
      name: 'Ed Hellen',
      salary: 17000,
      address: '42 Park Road, Paris',
      email: 'ed.hellen@example.com',
    },
    {
      key: '5',
      name: 'William Smith',
      salary: 27000,
      address: '62 Park Road, London',
      email: 'william.smith@example.com',
    },
  ];

  return <Table columns={columns} data={data} />;
}
