// packages/docs/site/src/demos/table/summary-row.tsx
import { Button, Table, Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      fixed: 'left',
      width: 200,
    },
    {
      title: 'Salary',
      dataIndex: 'salary',
    },
    {
      title: 'Count',
      dataIndex: 'count',
    },
    {
      title: 'Stars',
      dataIndex: 'stars',
    },
  ];
  const data = [
    {
      key: '1',
      name: 'Jane Doe',
      salary: 23000,
      count: 66,
      stars: 5,
    },
    {
      key: '2',
      name: 'Alisa Ross',
      salary: 25000,
      count: 55,
      stars: 8,
    },
    {
      key: '3',
      name: 'Kevin Sandra',
      salary: 22000,
      count: 100,
      stars: 2,
    },
    {
      key: '4',
      name: 'Ed Hellen',
      salary: 17000,
      count: 88,
      stars: 10,
    },
    {
      key: '5',
      name: 'William Smith',
      salary: 27000,
      count: 120,
      stars: 4,
    },
  ];

  function summary(currentData) {
    return (
      <Table.Summary.Row>
        <Table.Summary.Cell>Total</Table.Summary.Cell>
        <Table.Summary.Cell
          style={{
            backgroundColor: 'rgb(var(--success-1))',
          }}
        >
          <Typography.Text type="success" bold>
            {currentData.reduce((prev, next) => prev + next.salary, 0)}
          </Typography.Text>
        </Table.Summary.Cell>
        <Table.Summary.Cell>
          {currentData.reduce((prev, next) => prev + next.count, 0)}
        </Table.Summary.Cell>
        <Table.Summary.Cell>
          {currentData.reduce((prev, next) => prev + next.stars, 0)}
        </Table.Summary.Cell>
      </Table.Summary.Row>
    );
  }

  return (
    <div>
      <Table
        columns={columns}
        data={data}
        border={{
          wrapper: true,
          cell: true,
        }}
        summary={summary}
      />
      <Table
        style={{
          marginTop: 20,
        }}
        columns={columns.concat({
          title: 'Operation',
          dataIndex: 'operation',
          render: () => (
            <Button type="primary" size="mini">
              Confirm
            </Button>
          ),
          fixed: 'right',
          width: 100,
        })}
        data={data}
        scroll={{
          x: 1200,
        }}
        border={{
          wrapper: true,
          cell: true,
        }}
        summary={(currentData) => (
          <Table.Summary>
            <Table.Summary.Row>
              <Table.Summary.Cell>Total</Table.Summary.Cell>
              <Table.Summary.Cell>
                <Typography.Text type="error">
                  {currentData.reduce((prev, next) => prev + next.salary, 0)}
                </Typography.Text>
              </Table.Summary.Cell>
              <Table.Summary.Cell>
                {currentData.reduce((prev, next) => prev + next.count, 0)}
              </Table.Summary.Cell>
              <Table.Summary.Cell>
                {currentData.reduce((prev, next) => prev + next.stars, 0)}
              </Table.Summary.Cell>
              <Table.Summary.Cell />
            </Table.Summary.Row>
            <Table.Summary.Row>
              <Table.Summary.Cell>Avarage</Table.Summary.Cell>
              <Table.Summary.Cell colSpan={3}>
                <Typography.Text type="success">
                  {currentData.reduce((prev, next) => prev + next.salary, 0) / 5}
                </Typography.Text>
              </Table.Summary.Cell>
              <Table.Summary.Cell />
            </Table.Summary.Row>
          </Table.Summary>
        )}
      />
      <Table
        style={{ marginTop: 20 }}
        columns={columns}
        data={data}
        scroll={{
          x: 1200,
          y: 150,
        }}
        border={{
          wrapper: true,
          cell: true,
        }}
        summary={(currentData) => (
          <Table.Summary fixed="bottom">{summary(currentData)}</Table.Summary>
        )}
      />
    </div>
  );
}

// packages/docs/site/src/demos/table/summary-row.vue
<template>
  <Table
    :columns="columns"
    :data="data"
    :summary="true"
    :summary-span-method="spanMethod"
  />
  <Table
    :columns="columns"
    :data="data"
    :scroll="scroll"
    :expandable="expandable"
    :summary="summary"
  >
    <template #summary-cell="{ column, record, rowIndex }">
      <div :style="getColorStyle(column, record)">{{record[column.dataIndex]}}</div>
    </template>
  </Table>
</template>

<script setup lang="ts">
import { h, reactive } from 'vue';
import { IconDownCircle, IconRightCircle } from '@sbux/starbucks-design-vue/icon';

const expandable = {
  icon: (expanded: boolean) => h(expanded ? IconDownCircle : IconRightCircle),
  title: 'Expand',
  width: 80,
};

const scroll = {
  x: 2000,
  y: 200,
};

const columns = reactive([
  {
    title: 'Name',
    dataIndex: 'name',
    fixed: 'left',
    width: 140,
  },
  {
    title: 'Salary',
    dataIndex: 'salary',
    summaryCellStyle: (record) => {
      if (record.salary > 100000) {
        return {
          backgroundColor: 'rgb(var(--arcoblue-6))',
          color: '#fff',
        };
      }
      return undefined;
    },
  },
  {
    title: 'Data1',
    dataIndex: 'data1',
  },
  {
    title: 'Data2',
    dataIndex: 'data2',
  },
]);

const data = reactive([
  {
    key: '1',
    name: 'Jane Doe',
    salary: 23000,
    data1: 10,
    data2: 8,
    expand: 'Expand Content',
  },
  {
    key: '2',
    name: 'Alisa Ross',
    salary: 25000,
    data1: 9,
    data2: -12,
  },
  {
    key: '3',
    name: 'Kevin Sandra',
    salary: 22000,
    data1: 15,
    data2: -2,
  },
  {
    key: '4',
    name: 'Ed Hellen',
    salary: 17000,
    data1: 2,
    data2: 3,
  },
  {
    key: '5',
    name: 'William Smith',
    salary: 27000,
    data1: 11,
    data2: 0,
  },
]);

const summary = ({ columns, data }) => {
  const countData = {
    salary: 0,
    data1: 0,
    data2: 0,
  };

  data.forEach((record) => {
    countData.salary += record.salary;
    countData.data1 += record.data1;
    countData.data2 += record.data2;
  });

  return [
    {
      name: 'Avg',
      salary: countData.salary / data.length,
      data1: countData.data1 / data.length,
      data2: countData.data2 / data.length,
    },
    {
      name: 'Sum',
      salary: countData.salary,
      data1: countData.data1,
      data2: countData.data2,
    },
  ];
};

const getColorStyle = (column, record) => {
  if (['data1', 'data2'].includes(column.dataIndex)) {
    return { color: record[column.dataIndex] > 0 ? 'red' : 'green' };
  }
  return undefined;
};

const spanMethod = ({ rowIndex, columnIndex }) => {
  if (rowIndex === 0 && columnIndex === 1) {
    return {
      colspan: 2,
    };
  }
  return undefined;
};
</script>
