// packages/docs/site/src/demos/input-tag/input-status.tsx
import { InputTag, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space direction="vertical" size="large">
      <InputTag
        defaultValue={['test']}
        style={{ width: 320 }}
        placeholder="Please Enter"
        disabled
      />
      <InputTag
        defaultValue={['test']}
        style={{ width: 320 }}
        placeholder="Please Enter"
        readOnly
      />
      <InputTag
        defaultValue={['test']}
        style={{ width: 320 }}
        placeholder="Please Enter"
        status="error"
      />
    </Space>
  );
}

// packages/docs/site/src/demos/input-tag/input-status.vue
<template>
  <Space direction="vertical" size="large">
    <InputTag
      :default-value="['test']"
      :style="{ width: '320px' }"
      placeholder="Please Enter"
      disabled
    />
    <InputTag
      :default-value="['test']"
      :style="{ width: '320px' }"
      placeholder="Please Enter"
      readonly
    />
    <InputTag
      :default-value="['test']"
      :style="{ width: '320px' }"
      placeholder="Please Enter"
      error
    />
  </Space>
</template>
