// packages/docs/vue/components/feedback/demos/notification/custom-style.vue
<template>
  <Button type="primary" @click="handleNotification">
    Open Notification
  </Button>
</template>

<script setup lang="ts">
import { Notification } from '@arco-design/web-vue';

const handleNotification = () => {
  Notification.info({
    title: 'Notification',
    content: 'This is a notification!',
    closable: true,
    style: { width: '500px' },
  });
};
</script>

// packages/docs/site/src/demos/notification/custom-style.tsx
import { Button, Notification } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Button
      onClick={() =>
        Notification.info({
          style: { width: 500 },
          title: 'Notification',
          content: 'This is a notification! This is a notification! This is a notification! This is a notification! '
        })
      }
      type="primary"
    >
      Open Notification
    </Button>
  );
}
