// packages/docs/vue/components/feedback/demos/notification/message-type.vue
<template>
  <Space>
    <Button type="primary" @click="handleShowInfoNotification">
      Info
    </Button>
    <Button
      type="primary"
      status="success"
      @click="handleShowSuccessNotification"
    >
      Success
    </Button>
    <Button
      type="primary"
      status="warning"
      @click="handleShowWarningNotification"
    >
      Warning
    </Button>
    <Button
      type="primary"
      status="danger"
      @click="handleShowErrorNotification"
    >
      Error
    </Button>
    <Button type="secondary" @click="handleShowNormalNotification">
      Normal
    </Button>
  </Space>
</template>

<script setup lang="ts">
import { Notification } from '@arco-design/web-vue';

const handleShowInfoNotification = () =>
  Notification.info('This is an info message!');
const handleShowSuccessNotification = () =>
  Notification.success('This is a success message!');
const handleShowWarningNotification = () =>
  Notification.warning('This is a warning message!');
const handleShowErrorNotification = () =>
  Notification.error('This is an error message!');
const handleShowNormalNotification = () =>
  Notification.info({
    content: 'This is an error message!',
    showIcon: false,
  });
</script>

// packages/docs/site/src/demos/notification/message-type.tsx
import { Button, Space, Notification } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space size="large">
      <Button
        onClick={() =>
          Notification.info({
            title: 'Normal',
            content: 'This is an error Notification!'
          })
        }
        type="primary"
      >
        Info
      </Button>
      <Button
        onClick={() =>
          Notification.success({
            title: 'Success',
            content: 'This is a success Notification!'
          })
        }
        type="primary"
        status="success"
      >
        Success
      </Button>
      <Button
        onClick={() =>
          Notification.warning({
            title: 'Warning',
            content: 'This is a warning Notification!'
          })
        }
        type="primary"
        status="warning"
      >
        Warning
      </Button>
      <Button
        onClick={() =>
          Notification.error({
            title: 'Error',
            content: 'This is an error Notification!'
          })
        }
        type="primary"
        status="danger"
      >
        Error
      </Button>
      <Button
        onClick={() =>
          Notification.normal({
            title: 'Normal',
            content: 'This is an normal  Notification!'
          })
        }
        type="secondary"
      >
        Normal
      </Button>
    </Space>
  );
}
