// packages/docs/site/src/demos/notification/update-delay.vue
<template>
  <Button type="primary" @click="handleNotification">
    Open Notification
  </Button>
</template>

<script setup lang="ts">
import { getCurrentInstance } from 'vue';
import { Notification } from '@sbux/starbucks-design-vue';

const appContext = getCurrentInstance()!.appContext;

const handleNotification = () => {
  Notification.warning({
    id: 'your_id',
    title: 'Ready to update',
    content: 'Will update after 2 seconds...',
    duration: 0,
  }, appContext);

  setTimeout(() => {
    Notification.success({
      id: 'your_id',
      title: 'Success',
      content: 'Update success!',
      duration: 3000,
    }, appContext);
  }, 2000);
};
</script>

// packages/docs/site/src/demos/notification/update-delay.tsx
import { Button, Notification } from '@sbux/starbucks-design-react';

export default function Demo() {
  function updateNotification() {
    Notification.warning({
      id: 'need_update_duration',
      title: 'Ready to update',
      content: 'Will update after 2 seconds...',
      duration: 3000
    });
    setTimeout(() => {
      Notification.success({
        id: 'need_update_duration',
        title: 'Success',
        content: 'Will close after 3 seconds!',
        duration: 3000
      });
    }, 2000);
  }

  return (
    <Button onClick={updateNotification} type="primary">
      Update Notification
    </Button>
  );
}
