// packages/docs/vue/components/data-display/demos/card/borderless-card.vue
<template>
  <div
    :style="{
      display: 'flex',
      width: '100%',
      boxSizing: 'border-box',
      padding: '40px',
      backgroundColor: 'var(--color-fill-2)',
    }"
  >
    <Card :style="{ width: '360px' }" title="Arco Card" :bordered="false">
      <template #extra>
        <Link>More</Link>
      </template>
      Card content
      <br />
      Card content
    </Card>
    <Card
      :style="{ width: '360px', marginLeft: '24px' }"
      title="Hover me"
      hoverable
      :bordered="false"
    >
      <template #extra>
        <Link>More</Link>
      </template>
      Card content
      <br />
      Card content
    </Card>
  </div>
</template>

// packages/docs/site/src/demos/card/borderless-card.tsx
import { Card, Link, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space
      style={{
        padding: 40,
        backgroundColor: 'var(--color-fill-2)'
      }}
      size="large"
    >
      <Card style={{ width: 360 }} title="Arco Card" extra={<Link>More</Link>} bordered={false}>
        Card content
        <br />
        Card content
      </Card>
      <Card style={{ width: 360 }} title="Hover me" hoverable extra={<Link>More</Link>} bordered={false}>
        Card content
        <br />
        Card content
      </Card>
    </Space>
  );
}
