// packages/docs/site/src/demos/card/hover-style.vue
<template>
  <div :style="{ display: 'flex' }">
    <Card :style="{ width: '360px' }" title="Arco Card" hoverable>
      <template #extra>
        <Link>More</Link>
      </template>
      Card content <br />
      Card content
    </Card>
    <Card class="card-demo" title="Custom hover style" hoverable>
      <template #extra>
        <Link>More</Link>
      </template>
      Card content <br />
      Card content
    </Card>
  </div>
</template>
<style scoped>
.card-demo {
  width: 360px;
  margin-left: 24px;
  transition-property: all;
}
.card-demo:hover {
  transform: translateY(-4px);
}
</style>

// packages/docs/site/src/demos/card/hover-style.tsx
import { Card, Link, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space>
      <Card style={{ width: 360 }} title="Arco Card" hoverable extra={<Link>More</Link>}>
        Card content
        <br />
        Card content
      </Card>
      <Card
        style={{ width: 360 }}
        className="card-custom-hover-style"
        title="Custom hover style"
        hoverable
        extra={<Link>More</Link>}
      >
        Card content <br /> Card content
      </Card>
    </Space>
  );
}
