// packages/docs/site/src/demos/card/network-card.vue
<template>
  <Card :bordered="false" :style="{ width: '100%' }">
    <CardGrid
      v-for="(_, index) in new Array(7)"
      :key="index"
      :hoverable="index % 2 === 0"
      :style="{ width: '25%' }"
    >
      <Card class="card-demo" title="Arco Card" :bordered="false">
        <template #extra>
          <Link>More</Link>
        </template>
        <p :style="{ margin: 0 }">
          {{ index % 2 === 0 ? 'Card allow to hover' : 'Card content' }}
        </p>
      </Card>
    </CardGrid>
  </Card>
</template>
<style scoped>
.card-demo {
  width: 100%;
}
.card-demo :deep(.arco-card-header) {
  border: none;
}
</style>

// packages/docs/site/src/demos/card/network-card.tsx
import { Card, Link } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Card bordered={false} style={{ width: '100%' }}>
      {new Array(7).fill(null).map((_, index) => {
        const hoverable = index % 2 === 0;
        return (
          <Card.Grid
            key={index}
            hoverable={hoverable}
            style={{
              width: '25%'
            }}
          >
            <Card
              className="card-demo-in-grid"
              style={{ width: '100%' }}
              title="Arco Card"
              extra={<Link>More</Link>}
              bordered={false}
            >
              {new Array(2).fill(null).map((_, index) => (
                <p style={{ margin: 0 }} key={index}>
                  {hoverable ? 'Card allow to hover' : 'Card content'}
                </p>
              ))}
            </Card>
          </Card.Grid>
        );
      })}
    </Card>
  );
}
