// packages/docs/site/src/demos/upload/manual-upload.tsx
import React from 'react';
import { Upload, Space, Button } from '@sbux/starbucks-design-react';

export default function Demo() {
  const uploadRef = React.useRef();
  const [disabled, setDisabled] = React.useState(false);
  const [fileList, setFileList] = React.useState([]);

  const onSubmit = (e, isFirst) => {
    e.stopPropagation();
    const file = isFirst ? fileList.filter((x) => x.status === 'init')[0] : null;
    uploadRef.current && uploadRef.current.submit(file);
  };

  const onChange = (files) => {
    setFileList(files);
    setDisabled(!files.some((x) => x.status === 'init'));
  };

  const onProgress = (file) => {
    setFileList((files) => {
      return files.map((x) => (x.uid === file.uid ? file : x));
    });
  };

  return (
    <Upload
      ref={uploadRef}
      multiple
      autoUpload={false}
      action="/"
      onChange={onChange}
      onProgress={onProgress}
      fileList={fileList}
    >
      <Space size="large">
        <Button>选择文件</Button>
        <Button type="primary" onClick={onSubmit} disabled={disabled}>
          开始上传
        </Button>
        <Button
          type="primary"
          onClick={(e) => {
            onSubmit(e, true);
          }}
          disabled={disabled}
        >
          仅上传一个
        </Button>
      </Space>
    </Upload>
  );
}

// packages/docs/vue/components/data-entry/demos/upload/manual-upload.vue
<template>
  <div>
    <Upload
      action="/"
      :auto-upload="false"
      ref="uploadRef"
      @change="handleChange"
      multiple
    >
      <template #upload-button>
        <Space>
          <Button> select file</Button>
          <Button type="primary" @click="handleSubmit">
            start upload</Button
          >
          <Button type="primary" @click="handleSubmitOne">
            only upload one
          </Button>
        </Space>
      </template>
    </Upload>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const uploadRef = ref();
const files = ref([]);

const handleSubmitOne = (e) => {
  e.stopPropagation();
  console.log(files.value);
  uploadRef.value.handleSubmit(files.value.find((x) => x.status === 'init'));
};

const handleSubmit = (e) => {
  e.stopPropagation();
  uploadRef.value.handleSubmit();
};

const handleChange = (fileList) => {
  files.value = fileList;
};
</script>
