// packages/docs/site/src/demos/layout/collapsible-sidebar.vue
<template>
  <div class="sb-layout-demo sb-layout-demo--stack">
    <Layout class="sb-layout-demo__frame sb-layout-demo__frame--compact">
      <LayoutHeader>Header</LayoutHeader>
      <Layout>
        <LayoutSider
          :resize-directions="['right']"
          :style="{ minWidth: '150px', maxWidth: '500px', height: '200px' }"
        >
          Sider
        </LayoutSider>
        <LayoutContent>Content</LayoutContent>
      </Layout>
      <LayoutFooter>Footer</LayoutFooter>
    </Layout>
  </div>
</template>

// packages/docs/site/src/demos/layout/collapsible-sidebar.tsx
import { Layout } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div className="sb-layout-demo sb-layout-demo--stack">
      <Layout className="sb-layout-demo__frame sb-layout-demo__frame--compact">
        <Layout.Header>Header</Layout.Header>
        <Layout>
          <Layout.Sider
            resizeDirections={['right']}
            style={{
              minWidth: 150,
              maxWidth: 500,
              height: 200,
            }}
          >
            Sider
          </Layout.Sider>
          <Layout.Content>Content</Layout.Content>
        </Layout>
        <Layout.Footer>Footer</Layout.Footer>
      </Layout>
    </div>
  );
}
