// packages/docs/site/src/demos/calendar/calendar-content.tsx
import { Badge, Calendar } from '@sbux/starbucks-design-react';

export default function Demo() {
  const badgeStyle = {
    width: '100%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis'
  };

  return (
    <div style={{ width: '100%', overflow: 'auto' }}>
      <Calendar
        defaultValue="2020-03-04"
        dateInnerContent={(currentDate) => {
          switch (currentDate.format('YYYY-MM-DD')) {
            case '2020-03-07':
              return (
                <div
                  style={{
                    padding: '0 10px'
                  }}
                >
                  <Badge style={badgeStyle} status="processing" text="Cooking" />
                  <br />
                  <Badge style={badgeStyle} status="success" text="Reading" />
                  <br />
                  <Badge style={badgeStyle} status="warning" text="Sleeping" />
                </div>
              );

            case '2020-03-17':
              return (
                <div style={{ padding: '0 10px' }}>
                  <Badge style={badgeStyle} status="default" text="Coding" />
                  <br />
                  <Badge style={badgeStyle} status="processing" text="Runing" />
                  <br />
                  <Badge style={badgeStyle} status="success" text="Eating" />
                  <br />
                  <Badge style={badgeStyle} status="warning" text="Play games" />
                  <br />
                  <Badge style={badgeStyle} status="error" text="Sleeping" />
                </div>
              );

            default:
              return;
          }
        }}
      />
    </div>
  );
}

// packages/docs/site/src/demos/calendar/calendar-content.vue
<template>
  <div style="width: 100%; overflow: auto">
    <Calendar
      :default-value="new Date('2020-03-04')"
      :date-inner-content="dateInnerContent"
    />
  </div>
</template>

<script setup lang="ts">
import { h, resolveComponent } from 'vue';

const badgeStyle = {
  width: '100%',
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
};

function renderItems(items) {
  const Badge = resolveComponent('a-badge');
  return h(
    'div',
    { style: { padding: '0 10px' } },
    items.flatMap((item) => [
      h(Badge, { style: badgeStyle, status: item.status, text: item.text }),
      h('br'),
    ])
  );
}

const dateInnerContent = (currentDate) => {
  const date = currentDate.format('YYYY-MM-DD');
  if (date === '2020-03-07') {
    return renderItems([
      { status: 'processing', text: 'Cooking' },
      { status: 'success', text: 'Reading' },
      { status: 'warning', text: 'Sleeping' },
    ]);
  }
  if (date === '2020-03-17') {
    return renderItems([
      { status: 'processing', text: 'Coding' },
      { status: 'processing', text: 'Running' },
      { status: 'success', text: 'Eating' },
      { status: 'warning', text: 'Play games' },
      { status: 'danger', text: 'Sleeping' },
    ]);
  }
  return null;
};
</script>
