// packages/docs/site/src/demos/tree-select/custom-fill-mode.tsx
import { useState } from 'react';
import { Radio, TreeSelect } from '@sbux/starbucks-design-react';

export default function Demo() {
  const treeData = [
    {
      title: 'Trunk 0-0',
      value: 'Trunk 0-0',
      key: '0-0',
      children: [
        {
          title: 'Leaf 0-0-1',
          value: 'Leaf 0-0-1',
          key: '0-0-1',
        },
        {
          title: 'Branch 0-0-2',
          value: 'Branch 0-0-2',
          key: '0-0-2',
          children: [
            {
              title: 'Leaf 0-0-2-1',
              value: 'Leaf 0-0-2-1',
              key: '0-0-2-1',
            },
          ],
        },
      ],
    },
    {
      title: 'Trunk 0-1',
      value: 'Trunk 0-1',
      key: '0-1',
      children: [
        {
          title: 'Branch 0-1-1',
          value: 'Branch 0-1-1',
          key: '0-1-1',
          checkable: false,
          children: [
            {
              title: 'Leaf 0-1-1-1',
              value: 'Leaf 0-1-1-1',
              key: '0-1-1-1',
            },
            {
              title: 'Leaf 0-1-1-2',
              value: 'Leaf 0-1-1-2',
              key: '0-1-1-2',
              disabled: true,
            },
          ],
        },
        {
          title: 'Leaf 0-1-2',
          value: 'Leaf 0-1-2',
          key: '0-1-2',
        },
      ],
    },
  ];

  const [treeCheckedStrategy, setTreeCheckedStrategy] = useState(TreeSelect.SHOW_CHILD);
  const [value, setValue] = useState(['0-0']);
  return (
    <div>
      <div
        style={{ marginBottom: 20, }}
      >
        <Radio.Group
          type="button"
          value={treeCheckedStrategy}
          onChange={setTreeCheckedStrategy}
          options={[
            {
              value: TreeSelect.SHOW_ALL,
              label: 'show all',
            },
            {
              value: TreeSelect.SHOW_PARENT,
              label: 'show parent',
            },
            {
              value: TreeSelect.SHOW_CHILD,
              label: 'show child',
            },
          ]}
        />
      </div>
      <TreeSelect
        showSearch
        allowClear
        treeCheckable
        treeData={treeData}
        value={value}
        treeCheckedStrategy={treeCheckedStrategy}
        onChange={(value) => {
          console.log(value);
          setValue(value);
        }}
        style={{ width: 300, }}
      />
    </div>
  );
}

// packages/docs/site/src/demos/tree-select/custom-fill-mode.vue
<template>
  <div style="margin-bottom: 24px;">
    <RadioGroup
      type="button"
      v-model="treeCheckedStrategy"
      @change="
        (value) => {
          selected = [];
        }
      "
    >
      <Radio
        v-for="item in strategyOptions"
        :key="item?.value"
        :value="item?.value"
      >
        {{ item?.label }}
      </Radio>
    </RadioGroup>
  </div>
  <TreeSelect
    v-model="selected"
    :allow-search="true"
    :allow-clear="true"
    :tree-checkable="true"
    :tree-checked-strategy="treeCheckedStrategy"
    :data="treeData"
    placeholder="Please select ..."
    style="width: 300px;"
  ></TreeSelect>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const strategyOptions = [
  {
    value: 'all',
    label: 'show all',
  },
  {
    value: 'parent',
    label: 'show parent',
  },
  {
    value: 'child',
    label: 'show child',
  },
];

const treeData = [
  {
    title: 'Trunk 0-0',
    value: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Leaf 0-0-1',
        value: 'Leaf 0-0-1',
        key: '0-0-1',
      },
      {
        title: 'Branch 0-0-2',
        value: 'Branch 0-0-2',
        key: '0-0-2',
        children: [
          {
            title: 'Leaf 0-0-2-1',
            value: 'Leaf 0-0-2-1',
            key: '0-0-2-1',
          },
        ],
      },
    ],
  },
  {
    title: 'Trunk 0-1',
    value: 'Trunk 0-1',
    key: '0-1',
    children: [
      {
        title: 'Branch 0-1-1',
        value: 'Branch 0-1-1',
        key: '0-1-1',
        checkable: false,
        children: [
          {
            title: 'Leaf 0-1-1-1',
            value: 'Leaf 0-1-1-1',
            key: '0-1-1-1',
          },
          {
            title: 'Leaf 0-1-1-2',
            value: 'Leaf 0-1-1-2',
            key: '0-1-1-2',
            disabled: true,
          },
        ],
      },
      {
        title: 'Leaf 0-1-2',
        value: 'Leaf 0-1-2',
        key: '0-1-2',
      },
    ],
  },
];

const selected = ref([]);
const treeCheckedStrategy = ref('all');
</script>
