// packages/docs/site/src/demos/tree-select/dynamic-load.tsx
import { useState } from 'react';
import { TreeSelect } from '@sbux/starbucks-design-react';

export default function Demo() {
  const defaultData = [
    {
      key: 'node1',
      value: 'node1',
      title: 'node1',
      children: [
        {
          key: 'node2',
          value: 'node2',
          title: 'node2',
        },
      ],
    },
    {
      key: 'node3',
      value: 'node3',
      title: 'node3',
      children: [
        {
          key: 'node4',
          value: 'node4',
          title: 'node4',
          isLeaf: true,
        },
        {
          key: 'node5',
          value: 'node5',
          title: 'node5',
          isLeaf: true,
        },
      ],
    },
  ];

  const [treeData, setTreeData] = useState(defaultData);
  const [value, setValue] = useState('node2');

  const loadMore = (node, dataRef) => {
    const { title, _key: key } = node.props;
    const children = [
      {
        title: `${title}-0`,
        value: `${title}-0`,
        key: `${key}-0`,
      },
      {
        title: `${title}-1`,
        value: `${title}-1`,
        key: `${key}-1`,
      },
    ];
    return new Promise((resolve) => {
      setTimeout(() => {
        dataRef.children = children;
        setTreeData([...treeData]);
        resolve();
      }, 1000);
    });
  };

  return (
    <TreeSelect
      showSearch
      placeholder="请选择..."
      treeData={treeData}
      value={value}
      onChange={setValue}
      loadMore={loadMore}
      triggerProps={{
        popupStyle: {
          maxHeight: 300,
        },
      }}
      style={{ width: 300 }}
    />
  );
}

// packages/docs/site/src/demos/tree-select/dynamic-load.vue
<template>
  <TreeSelect
    :data="treeData"
    :load-more="loadMore"
    placeholder="Please select ..."
    style="width: 300px"
  ></TreeSelect>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const defaultTreeData = [
  {
    key: 'node1',
    title: 'node1',
    disabled: true,
    children: [
      {
        key: 'node2',
        title: 'node2',
      },
    ],
  },
  {
    key: 'node3',
    title: 'node3',
    children: [
      {
        key: 'node4',
        title: 'node4',
        isLeaf: true,
      },
      {
        key: 'node5',
        title: 'node5',
        isLeaf: true,
      },
    ],
  },
];

const treeData = ref(defaultTreeData);
const loadMore = (nodeData) => {
  const { title, key } = nodeData;
  const children = [
    { title: `${title}-0`, value: `${title}-0`, key: `${key}-0` },
    { title: `${title}-1`, value: `${title}-1`, key: `${key}-1` },
  ];

  return new Promise((resolve) => {
    setTimeout(() => {
      nodeData.children = children;
      resolve();
    }, 1000);
  });
};
</script>
