// packages/docs/vue/components/data-entry/demos/tree-select/remote-search.vue
<template>
  <TreeSelect
    :allow-search="true"
    :allow-clear="true"
    :disable-filter="true"
    :data="treeData"
    :loading="loading"
    style="width: 300px"
    placeholder="Please select ..."
    @search="handleSearch"
  ></TreeSelect>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const defaultTreeData = [
  {
    title: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Branch 0-0-1',
        key: '0-0-1',
        children: [
          {
            title: 'Leaf 0-0-1-1',
            key: '0-0-1-1',
          },
          {
            title: 'Leaf 0-0-1-2',
            key: '0-0-1-2',
          },
        ],
      },
    ],
  },
  {
    title: 'Trunk 0-1',
    key: '0-1',
    children: [
      {
        title: 'Branch 0-1-1',
        key: '0-1-1',
        children: [
          {
            title: 'Leaf 0-1-1-0',
            key: '0-1-1-0',
          },
        ],
      },
      {
        title: 'Branch 0-1-2',
        key: '0-1-2',
        children: [
          {
            title: 'Leaf 0-1-2-0',
            key: '0-1-2-0',
          },
        ],
      },
    ],
  },
];

const treeData = ref(defaultTreeData);
const loading = ref(false);

function searchData(keyword) {
  const loop = (data) => {
    const result = [];
    data.forEach((item) => {
      if (item.title.toLowerCase().indexOf(keyword.toLowerCase()) > -1) {
        result.push({ ...item });
      } else if (item.children) {
        const filterData = loop(item.children);
        if (filterData.length) {
          result.push({
            ...item,
            children: filterData,
          });
        }
      }
    });
    return result;
  };

  return loop(defaultTreeData);
}

const handleSearch = (searchKey) => {
  loading.value = true;
  setTimeout(() => {
    loading.value = false;
    treeData.value = searchData(searchKey);
  }, 200);
};
</script>

// packages/docs/site/src/demos/tree-select/remote-search.tsx
import React from 'react';
import { Spin, TreeSelect } from '@sbux/starbucks-design-react';

export default function Demo() {
  const TreeData = [
    {
      title: 'Trunk 0-0',
      key: '0-0',
      children: [
        {
          title: 'Branch 0-0-1',
          key: '0-0-1',
          children: [
            {
              title: 'Leaf 0-0-1-1',
              key: '0-0-1-1',
            },
            {
              title: 'Leaf 0-0-1-2',
              key: '0-0-1-2',
            },
          ],
        },
      ],
    },
    {
      title: 'Trunk 0-1',
      key: '0-1',
      children: [
        {
          title: 'Branch 0-1-1',
          key: '0-1-1',
          children: [
            {
              title: 'Leaf 0-1-1-0',
              key: '0-1-1-0',
            },
          ],
        },
        {
          title: 'Branch 0-1-2',
          key: '0-1-2',
          children: [
            {
              title: 'Leaf 0-1-2-0',
              key: '0-1-2-0',
            },
          ],
        },
      ],
    },
  ];

  function searchData(inputValue) {
    const loop = (data) => {
      const result = [];
      data.forEach((item) => {
        if (item.title.toLowerCase().indexOf(inputValue.toLowerCase()) > -1) {
          result.push({ ...item });
        } else if (item.children) {
          const filterData = loop(item.children);

          if (filterData.length) {
            result.push({ ...item, children: filterData });
          }
        }
      });
      return result;
    };

    return loop(TreeData);
  }

  const [treeData, setTreeData] = React.useState(TreeData);
  const [loading, setLoading] = React.useState(false);
  const [value, setValue] = React.useState([]);
  return (
    <TreeSelect
      treeCheckable
      value={value}
      onChange={setValue}
      showSearch={true}
      allowClear={true}
      notFoundContent={loading ? <Spin /> : undefined}
      placeholder="please select..."
      treeData={loading ? [] : treeData}
      onSearch={(inputValue) => {
        setLoading(true);
        setTimeout(() => {
          setLoading(false);
          setTreeData(searchData(inputValue));
        }, 200);
      }}
      style={{ width: 300 }}
    />
  );
}
