// packages/docs/site/src/demos/tree-select/sizes.vue
<template>
  <div style="margin-bottom: 20px;">
    <RadioGroup v-model="size" type="button">
      <Radio value="mini">mini</Radio>
      <Radio value="small">small</Radio>
      <Radio value="medium">medium</Radio>
      <Radio value="large">large</Radio>
    </RadioGroup>
  </div>
  <TreeSelect
    defaultValue="node1"
    :size="size"
    :data="treeData"
    placeholder="Please select ..."
    style="width: 300px;"
  ></TreeSelect>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const treeData = [
  {
    key: 'node1',
    title: 'node1',
    disabled: true,
    children: [
      {
        key: 'node2',
        title: 'node2',
      },
    ],
  },
  {
    key: 'node3',
    title: 'node3',
    children: [
      {
        key: 'node4',
        title: 'node4',
        isLeaf: true,
      },
      {
        key: 'node5',
        title: 'node5',
        isLeaf: true,
      },
    ],
  },
];

const size = ref('medium');
</script>

// packages/docs/site/src/demos/tree-select/sizes.tsx
import { useState } from 'react';
import { Radio, TreeSelect } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [size, setSize] = useState('default');
  return (
    <div>
      <Radio.Group
        type="button"
        name="size"
        value={size}
        onChange={setSize}
        style={{ marginBottom: 20, }}
      >
        <Radio value="mini">mini</Radio>
        <Radio value="small">small</Radio>
        <Radio value="default">default</Radio>
        <Radio value="large">large</Radio>
      </Radio.Group>
      <div>
        <TreeSelect
          size={size}
          defaultValue="node1"
          style={{ width: 300, }}
        >
          <TreeSelect.Node key="node1" title="Trunk">
            <TreeSelect.Node key="node2" title="Leaf" />
          </TreeSelect.Node>
          <TreeSelect.Node key="node3" title="Trunk2">
            <TreeSelect.Node key="node4" title="Leaf" />
            <TreeSelect.Node key="node5" title="Leaf" />
          </TreeSelect.Node>
        </TreeSelect>
      </div>
    </div>
  );
}
