// packages/starbucks-design-react/src/pro/page-footer-bar/PageFooterBar.tsx
import type { PageFooterBarProps } from './interface'

export function PageFooterBar(props: PageFooterBarProps) {
  const { align = 'left', bordered = true, children, className, style } = props

  const cls = [
    'sbux-pro-page-footer-bar',
    `sbux-pro-page-footer-bar-align-${align}`,
    bordered ? 'sbux-pro-page-footer-bar-bordered' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div className={cls} style={style}>
      {children}
    </div>
  )
}

// packages/starbucks-design-vue/src/pro/page-footer-bar/PageFooterBar.vue
<script setup lang="ts">
import type { PageFooterBarProps } from './interface'

defineOptions({ name: 'PageFooterBar' })

withDefaults(defineProps<PageFooterBarProps>(), { align: 'left', bordered: true })
</script>

<template>
  <div
    class="sbux-pro-page-footer-bar"
    :class="[
      `sbux-pro-page-footer-bar-align-${align}`,
      { 'sbux-pro-page-footer-bar-bordered': bordered },
    ]"
  >
    <slot />
  </div>
</template>
