// packages/docs/site/src/demos/time-picker/prefix.vue
<template>
  <div>
    <div>
      <TimePicker style="width: 194px;">
        <template #prefix>
          <IconInfoCircle />
        </template> </TimePicker
    ></div>
    <div>
      <TimePicker type="time-range" style="width: 252px; margin-top: 20px">
        <template #prefix>
          <IconInfoCircle />
        </template>
      </TimePicker>
    </div>
  </div>
</template>

<script setup lang="ts">
import { IconInfoCircle } from '@sbux/starbucks-design-vue/icon';
</script>

// packages/docs/site/src/demos/time-picker/prefix.tsx
import { Space, TimePicker } from '@sbux/starbucks-design-react';
import { IconInfoCircle } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <Space>
      <TimePicker prefix={<IconInfoCircle />} style={{ width: 200 }} />
      <TimePicker.RangePicker prefix={<IconInfoCircle />} style={{ width: 250 }} />
    </Space>
  );
}
