// packages/docs/site/src/demos/tree/custom-extra-node.tsx
import { useState } from 'react';
import { Button, Tree } from '@sbux/starbucks-design-react';
import { IconPlus } from '@sbux/starbucks-design-react/icon';
import './custom-extra-node.css';

export default function Demo() {
  const generatorTreeNodes = (treeData) => {
    return treeData.map((item) => {
      const { children, key, ...rest } = item;
      return (
        <Tree.Node key={key} {...rest} dataRef={item}>
          {children ? generatorTreeNodes(item.children) : null}
        </Tree.Node>
      );
    });
  };

  const TreeData = [
    {
      title: 'Trunk',
      key: '0-0',
      children: [
        {
          title: 'Leaf',
          key: '0-0-1',
        },
        {
          title: 'Branch',
          key: '0-0-2',
          children: [
            {
              title: 'Leaf',
              key: '0-0-2-1',
            },
          ],
        },
      ],
    },
    {
      title: 'Trunk',
      key: '0-1',
      children: [
        {
          title: 'Branch',
          key: '0-1-1',
          children: [
            {
              title: 'Leaf',
              key: '0-1-1-1',
            },
            {
              title: 'Leaf',
              key: '0-1-1-2',
            },
          ],
        },
        {
          title: 'Leaf',
          key: '0-1-2',
        },
      ],
    },
  ];

  const [treeData, setTreeData] = useState(TreeData);
  return (
    <div className="tree-extra-demo" style={{ width: 500, padding: 2, overflow: 'auto' }}>
      <Tree
        blockNode
        checkable
        renderExtra={(node) => {
          return (
            <Button
              aria-label={`为 ${node.dataRef.title} 添加子节点`}
              className="tree-node-add-button"
              icon={<IconPlus />}
              shape="square"
              size="mini"
              type="text"
              onClick={(event) => {
                event.stopPropagation();
                const dataChildren = node.dataRef.children || [];
                dataChildren.push({
                  title: 'new tree node',
                  key: node._key + '-' + (dataChildren.length + 1),
                });
                node.dataRef.children = dataChildren;
                setTreeData([...treeData]);
              }}
            />
          );
        }}
      >
        {generatorTreeNodes(treeData)}
      </Tree>
    </div>
  );
}

// packages/docs/vue/components/data-display/demos/tree/custom-extra-node.vue
<template>
  <div style="width: 500px; padding: 2px; overflow: auto">
    <Tree :blockNode="true" :checkable="true" :data="treeData">
      <template #extra="nodeData">
        <IconPlus
          style="position: absolute; right: 8px; font-size: 12px; top: 10px; color: #3370ff;"
          @click="() => onIconClick(nodeData)"
        />
      </template>
    </Tree>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { IconPlus } from '@arco-design/web-vue/es/icon';

function onIconClick(nodeData) {
  const children = nodeData.children || [];
  children.push({
    title: 'new tree node',
    key: nodeData.key + '-' + (children.length + 1),
  });
  nodeData.children = children;

  treeData.value = [...treeData.value];
}

const treeData = ref([
  {
    title: 'Trunk',
    key: '0-0',
    children: [
      {
        title: 'Leaf',
        key: '0-0-1',
      },
      {
        title: 'Branch',
        key: '0-0-2',
        children: [
          {
            title: 'Leaf',
            key: '0-0-2-1',
          },
        ],
      },
    ],
  },
  {
    title: 'Trunk',
    key: '0-1',
    children: [
      {
        title: 'Branch',
        key: '0-1-1',
        children: [
          {
            title: 'Leaf',
            key: '0-1-1-1',
          },
          {
            title: 'Leaf',
            key: '0-1-1-2',
          },
        ],
      },
      {
        title: 'Leaf',
        key: '0-1-2',
      },
    ],
  },
]);
</script>
