// packages/docs/site/src/demos/tree/node-full-row.tsx
import { Tree } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Tree blockNode>
      <Tree.Node title="Trunk 0-0" key="0-0">
        <Tree.Node title="Branch 0-0-0" key="0-0-0" disabled>
          <Tree.Node title="Leaf 0-0-0-0" key="0-0-0-0" />
          <Tree.Node title="Leaf 0-0-0-1" key="0-0-0-1" />
        </Tree.Node>
        <Tree.Node title="Branch 0-0-1" key="0-0-1">
          <Tree.Node title="Leaf 0-0-1-0" key="0-0-1-0" />
        </Tree.Node>
      </Tree.Node>
    </Tree>
  );
}

// packages/docs/vue/components/data-display/demos/tree/node-full-row.vue
<template>
  <Tree blockNode :data="treeData" />
</template>
<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const treeData = [
  {
    title: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Branch 0-0-0',
        key: '0-0-0',
        children: [
          {
            title: 'Leaf',
            key: '0-0-0-0',
          },
          {
            title: 'Leaf',
            key: '0-0-0-1',
          },
        ],
      },
      {
        title: 'Branch 0-0-1',
        key: '0-0-1',
        children: [
          {
            title: 'Leaf',
            key: '0-0-1-0',
          },
        ],
      },
    ],
  },
];

const state = reactive({
  treeData,
});
</script>
