// packages/docs/site/src/demos/tabs/extra-content.vue
<template>
  <Tabs>
    <template #extra>
      <Button>Action</Button>
    </template>
    <TabPane key="1" title="Tab 1"> Content of Tab Panel 1 </TabPane>
    <TabPane key="2" title="Tab 2"> Content of Tab Panel 2 </TabPane>
    <TabPane key="3" title="Tab 3"> Content of Tab Panel 3 </TabPane>
  </Tabs>
</template>

// packages/docs/site/src/demos/tabs/extra-content.tsx
import { Button, Tabs, Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  const style = {
    textAlign: 'center',
    marginTop: 20,
  };

  return (
    <Tabs
      defaultActiveTab="1"
      extra={
        <Button size="small" type="secondary">
          Action
        </Button>
      }
    >
      <Tabs.TabPane key="1" title="Tab 1">
        <Typography.Paragraph style={style}>Content of Tab Panel 1</Typography.Paragraph>
      </Tabs.TabPane>
      <Tabs.TabPane key="2" title="Tab 2" disabled>
        <Typography.Paragraph style={style}>Content of Tab Panel 2</Typography.Paragraph>
      </Tabs.TabPane>
      <Tabs.TabPane key="3" title="Tab 3">
        <Typography.Paragraph style={style}>Content of Tab Panel 3</Typography.Paragraph>
      </Tabs.TabPane>
    </Tabs>
  );
}
