// packages/docs/site/src/demos/anchor/change-hash.tsx
import { Anchor } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Anchor affix={false} hash={false}>
      <Anchor.Link href="#Basic" title="Basic" />
      <Anchor.Link href="#Static" title="Static" />
      <Anchor.Link href="#Lineless-mode" title="Lineless mode" />
      <Anchor.Link href="#Affix" title="Affix" />
      <Anchor.Link href="#Scroll-boundary" title="Scroll boundary" />
      <Anchor.Link href="#Hash-mode" title="Hash mode" />
    </Anchor>
  );
}

// packages/docs/vue/components/other/demos/anchor/change-hash.vue
<template>
  <Anchor :change-hash="false">
    <AnchorLink href="#basic">Basic</AnchorLink>
    <AnchorLink href="#line-less">LineLess Mode</AnchorLink>
    <AnchorLink href="#affix">
      Affix
      <template #sublist>
        <AnchorLink href="#boundary">Scroll Boundary</AnchorLink>
        <AnchorLink href="#hash">Hash mode</AnchorLink>
      </template>
    </AnchorLink>
  </Anchor>
</template>
