// packages/docs/site/src/demos/progress/circle-progress.vue
<template>
  <Space size="large">
    <Progress type="circle" :percent="percent" />
    <Progress type="circle" status="warning" :percent="percent" />
    <Progress type="circle" status="danger" :percent="percent" />
    <Progress type="circle" status="success" :percent="percent" />
  </Space>
  <div :style="{ marginTop: '20px' }">
    <Slider
      v-model="percent"
      :max="1"
      :step="0.1"
      :style="{ width: '150px' }"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const percent = ref(0.2);
</script>

// packages/docs/site/src/demos/progress/circle-progress.tsx
import React from 'react';
import { Progress, Slider } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [value, setValue] = React.useState(20);
  return (
    <div>
      <Progress type="circle" percent={value} style={{ marginRight: 80 }} />
      <Progress type="circle" percent={value} status="warning" style={{ marginRight: 80 }} />
      <Progress type="circle" percent={value} status="error" style={{ marginRight: 80 }} />
      <Progress type="circle" percent={value} status="success" style={{ marginRight: 80 }} />
      <div style={{ marginTop: 40 }}>
        <Slider value={value} onChange={setValue} style={{ width: 100 }}></Slider>
      </div>
    </div>
  );
}
