// packages/docs/vue/components/feedback/demos/progress/mini-progress.vue
<template>
  <Space size="large" :style="{ width: '100%' }">
    <Progress size="mini" :percent="percent" />
    <Progress size="mini" status="warning" :percent="percent" />
    <Progress size="mini" status="danger" :percent="percent" />
    <Progress size="mini" status="success" :percent="percent" />
  </Space>
  <Space size="large" :style="{ width: '100%', marginTop: '20px' }">
    <Progress type="circle" size="mini" :percent="percent" />
    <Progress type="circle" size="mini" status="warning" :percent="percent" />
    <Progress type="circle" size="mini" status="danger" :percent="percent" />
    <Progress type="circle" size="mini" status="success" :percent="percent" />
  </Space>
  <div :style="{ marginTop: '20px' }">
    <Slider
      v-model="percent"
      :max="1"
      :step="0.1"
      :style="{ width: '150px' }"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const percent = ref(0.2);
</script>

// packages/docs/site/src/demos/progress/mini-progress.tsx
import { Progress } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <div>
        <Progress
          size="mini"
          percent={0}
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          percent={40}
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          percent={70}
          status="error"
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          percent={100}
          status="success"
          style={{
            marginRight: 80
          }}
        />
      </div>
      <div
        style={{
          marginTop: 20
        }}
      >
        <Progress
          size="mini"
          type="circle"
          percent={0}
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          type="circle"
          percent={40}
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          type="circle"
          percent={70}
          status="error"
          style={{
            marginRight: 80
          }}
        />
        <Progress
          size="mini"
          type="circle"
          percent={100}
          status="success"
          style={{
            marginRight: 80
          }}
        />
      </div>
    </div>
  );
}
