// packages/docs/site/src/demos/avatar/group.tsx
import { Avatar } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Avatar.Group size={32} style={{ margin: 10 }}>
        <Avatar style={{ backgroundColor: 'var(--color-primary)' }}>A</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-success)' }}>B</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-warning)' }}>C</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-danger)' }}>Nink</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-primary-active)' }}>Starbucks</Avatar>
      </Avatar.Group>
      <br />
      <Avatar.Group size={24} style={{ margin: 10 }}>
        <Avatar style={{ backgroundColor: 'var(--color-primary)' }}>A</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-success)' }}>B</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-warning)' }}>C</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-danger)' }}>Nink</Avatar>
        <Avatar style={{ backgroundColor: 'var(--color-primary-active)' }}>Starbucks</Avatar>
      </Avatar.Group>
    </div>
  );
}

// packages/docs/site/src/demos/avatar/group.vue
<template>
  <Space :size="32">
    <AvatarGroup>
      <Avatar :style="{ backgroundColor: 'var(--color-primary)' }">A</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-success)' }">B</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-warning)' }">C</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-danger)' }">Nink</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-primary-active)' }">Starbucks</Avatar>
    </AvatarGroup>

    <AvatarGroup :size="24">
      <Avatar :style="{ backgroundColor: 'var(--color-primary)' }">A</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-success)' }">B</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-warning)' }">C</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-danger)' }">Nink</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-primary-active)' }">Starbucks</Avatar>
    </AvatarGroup>

    <AvatarGroup :size="24" :max-count="3">
      <Avatar :style="{ backgroundColor: 'var(--color-primary)' }">A</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-success)' }">B</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-warning)' }">C</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-danger)' }">Nink</Avatar>
      <Avatar :style="{ backgroundColor: 'var(--color-primary-active)' }">Starbucks</Avatar>
    </AvatarGroup>
  </Space>
</template>
