// packages/docs/vue/components/data-display/demos/avatar/size-shape.vue
<template>
  <Space size="large" direction="vertical">
    <Space size="large">
      <Avatar :size="64">Arco</Avatar>
      <Avatar :size="40">Arco</Avatar>
      <Avatar :size="32">Arco</Avatar>
      <Avatar :size="24">Arco</Avatar>
    </Space>
    <Space size="large">
      <Avatar :size="64" shape="square">Arco</Avatar>
      <Avatar :size="40" shape="square">Arco</Avatar>
      <Avatar :size="32" shape="square">Arco</Avatar>
      <Avatar :size="24" shape="square">Arco</Avatar>
    </Space>
  </Space>
</template>

// packages/docs/site/src/demos/avatar/size-shape.tsx
import { Avatar, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space size="large" direction="vertical">
      <Space size="large">
        <Avatar size={64}>Arco</Avatar>
        <Avatar size={40}>Arco</Avatar>
        <Avatar size={32}>Arco</Avatar>
        <Avatar size={24}>Arco</Avatar>
      </Space>
      <Space size="large">
        <Avatar size={64} shape="square">
          Arco
        </Avatar>
        <Avatar size={40} shape="square">
          Arco
        </Avatar>
        <Avatar size={32} shape="square">
          Arco
        </Avatar>
        <Avatar size={24} shape="square">
          Arco
        </Avatar>
      </Space>
    </Space>
  );
}
