// packages/docs/site/src/demos/avatar/size-shape.tsx
import { Avatar, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space size="large" direction="vertical">
      <Space size="large">
        <Avatar size={64}>Nink</Avatar>
        <Avatar size={40}>Nink</Avatar>
        <Avatar size={32}>Nink</Avatar>
        <Avatar size={24}>Nink</Avatar>
      </Space>
      <Space size="large">
        <Avatar size={64} shape="square">
          Nink
        </Avatar>
        <Avatar size={40} shape="square">
          Nink
        </Avatar>
        <Avatar size={32} shape="square">
          Nink
        </Avatar>
        <Avatar size={24} shape="square">
          Nink
        </Avatar>
      </Space>
    </Space>
  );
}

// packages/docs/site/src/demos/avatar/size-shape.vue
<template>
  <Space size="large" direction="vertical">
    <Space size="large">
      <Avatar :size="64">Nink</Avatar>
      <Avatar :size="40">Nink</Avatar>
      <Avatar :size="32">Nink</Avatar>
      <Avatar :size="24">Nink</Avatar>
    </Space>
    <Space size="large">
      <Avatar :size="64" shape="square">Nink</Avatar>
      <Avatar :size="40" shape="square">Nink</Avatar>
      <Avatar :size="32" shape="square">Nink</Avatar>
      <Avatar :size="24" shape="square">Nink</Avatar>
    </Space>
  </Space>
</template>
