// packages/docs/site/src/demos/list/extra-actions.tsx
import { useState } from 'react';
import { List, Avatar } from '@sbux/starbucks-design-react';
import { IconLoading, IconDown, IconEdit, IconDelete } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const dataSource = new Array(4).fill({
    title: 'Beijing Bytedance Technology Co., Ltd.',
    description: 'Beijing ByteDance Technology Co., Ltd. is an enterprise located in China.',
  });
  const [loading, setLoading] = useState(false);

  const render = (actions, item, index) => (
    <List.Item key={index} actions={actions}>
      <List.Item.Meta
        avatar={<Avatar shape="square">A</Avatar>}
        title={item.title}
        description={item.description}
      />
    </List.Item>
  );

  const footer = (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
      }}
      onClick={() => setLoading(!loading)}
      onKeyDown={e => {
        const keyCode = e.keyCode || e.which;
        if (keyCode === 13) { // enter
          setLoading(!loading)
        }
      }}
    >
      {loading ? (
        <span style={{ color: 'var(--color-text-3)' }}>
          <IconLoading style={{ marginRight: 8, color: 'rgb(var(--arcoblue-6))' }} />
          loading...
        </span>
      ) : (
        <span className="list-demo-actions-button" tabIndex={0} >
          More
          <IconDown style={{ marginLeft: 8 }} />
        </span>
      )}
    </div>
  );
  return (
    <>
      <List
        className="list-demo-actions"
        style={{ width: 700, marginBottom: 48 }}
        dataSource={dataSource}
        render={render.bind(null, [
          <span className="list-demo-actions-icon">
            <IconEdit />
          </span>,
          <span className="list-demo-actions-icon">
            <IconDelete />
          </span>,
        ])}
        footer={footer}
      />
      <List
        className="list-demo-actions"
        style={{ width: 700 }}
        dataSource={dataSource}
        render={render.bind(null, [
          <span className="list-demo-actions-button">Edit</span>,
          <span className="list-demo-actions-button">Delete</span>,
        ])}
      />
    </>
  );
}

// packages/docs/site/src/demos/list/extra-actions.vue
<template>
  <List>
    <ListItem v-for="idx in 4" :key="idx">
      <ListItemMeta
        title="Beijing Bytedance Technology Co., Ltd."
        description="Beijing ByteDance Technology Co., Ltd. is an enterprise located in China."
      >
        <template #avatar>
          <Avatar shape="square">
            <img
              alt="avatar"
              src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/3ee5f13fb09879ecb5185e440cef6eb9.png~tplv-uwbnlip3yd-webp.webp"
            />
          </Avatar>
        </template>
      </ListItemMeta>
      <template #actions>
        <icon-edit />
        <icon-delete />
      </template>
    </ListItem>
  </List>
</template>

<script setup lang="ts">
import { IconEdit, IconDelete } from '@sbux/starbucks-design-vue/icon';
</script>
