// packages/docs/site/src/demos/list/list-item.vue
<template>
  <List>
    <ListItem v-for="idx in 4" :key="idx">
      <ListItemMeta
        title="Beijing Bytedance Technology Co., Ltd."
        description="Beijing ByteDance Technology Co., Ltd. is an enterprise located in China."
      >
        <template #avatar>
          <Avatar shape="square">
            <img
              alt="avatar"
              src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/3ee5f13fb09879ecb5185e440cef6eb9.png~tplv-uwbnlip3yd-webp.webp"
            />
          </Avatar>
        </template>
      </ListItemMeta>
    </ListItem>
  </List>
</template>

// packages/docs/site/src/demos/list/list-item.tsx
import { List, Avatar } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <List
      style={{ width: 600 }}
      dataSource={new Array(4).fill({
        title: 'Beijing Bytedance Technology Co., Ltd.',
        description: 'Beijing ByteDance Technology Co., Ltd. is an enterprise located in China.',
      })}
      render={(item, index) => (
        <List.Item key={index}>
          <List.Item.Meta
            avatar={<Avatar shape="square">A</Avatar>}
            title={item.title}
            description={item.description}
          />
        </List.Item>
      )}
    />
  );
}
