// packages/docs/site/src/demos/list/sizes.vue
<template>
  <Space direction="vertical" size="large">
    <RadioGroup v-model="size" type="button">
      <Radio value="small">Small</Radio>
      <Radio value="medium">Medium</Radio>
      <Radio value="large">Large</Radio>
    </RadioGroup>
    <List :size="size">
      <template #header> List title </template>
      <ListItem>Beijing Bytedance Technology Co., Ltd.</ListItem>
      <ListItem>Bytedance Technology Co., Ltd.</ListItem>
      <ListItem>Beijing Toutiao Technology Co., Ltd.</ListItem>
      <ListItem>Beijing Volcengine Technology Co., Ltd.</ListItem>
      <ListItem>China Beijing Bytedance Technology Co., Ltd.</ListItem>
    </List>
  </Space>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const size = ref('medium');
</script>

// packages/docs/site/src/demos/list/sizes.tsx
import { useState } from 'react';
import { List, Radio } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [size, setSize] = useState('default');
  return (
    <>
      <Radio.Group
        type="button"
        name="size"
        value={size}
        onChange={(value) => setSize(value)}
        style={{ marginBottom: 20, borderRadius: 4 }}
      >
        <Radio value="small">small</Radio>
        <Radio value="default">default</Radio>
        <Radio value="large">large</Radio>
      </Radio.Group>
      <List
        style={{ width: 622 }}
        size={size}
        header="List title"
        dataSource={[
          'Beijing Bytedance Technology Co., Ltd.',
          'Bytedance Technology Co., Ltd.',
          'Beijing Toutiao Technology Co., Ltd.',
          'Beijing Volcengine Technology Co., Ltd.',
          'China Beijing Bytedance Technology Co., Ltd.',
        ]}
        render={(item, index) => <List.Item key={index}>{item}</List.Item>}
      />
    </>
  );
}
