// packages/docs/site/src/demos/cascader/basic-usage.tsx
import { Cascader, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  const options = [
    {
      value: 'beijing',
      label: 'Beijing',
      children: [
        {
          value: 'Beijing',
          label: 'Beijing',
          children: [
            {
              value: 'chaoyang',
              label: 'Chaoyang',
              children: [
                {
                  value: 'datunli',
                  label: 'Datunli',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      value: 'shanghai',
      label: 'Shanghai',
      children: [
        {
          value: 'shanghaishi',
          label: 'Shanghai',
          children: [
            {
              value: 'huangpu',
              label: 'Huangpu',
            },
          ],
        },
      ],
    },
  ];

  return (
    <div>
      <Space size="large">
        <Cascader
          placeholder="Please select ..."
          style={{ width: 300, marginBottom: 20 }}
          options={options}
        />
        <Cascader
          placeholder="Hover to expand"
          expandTrigger="hover"
          style={{ width: 300, marginBottom: 20 }}
          options={options}
        />
      </Space>
      <br/>
      <Space size="large">
        <Cascader
          status="error"
          allowClear
          placeholder="Please select ..."
          style={{ width: 300, marginBottom: 20 }}
          options={options}
        />
        <Cascader
          status="warning"
          allowClear
          placeholder="Hover to expand"
          expandTrigger="hover"
          style={{ width: 300, marginBottom: 20 }}
          options={options}
        />
      </Space>
    </div>
  );
}

// packages/docs/vue/components/data-entry/demos/cascader/basic-usage.vue
<template>
  <Space direction="vertical" size="large">
    <Cascader
      :options="options"
      :style="{ width: '320px' }"
      placeholder="Please select ..."
    />
    <Cascader
      :options="options"
      default-value="datunli"
      expand-trigger="hover"
      :style="{ width: '320px' }"
      placeholder="Please select ..."
    />
  </Space>
</template>

<script setup lang="ts">
const options = [
  {
    value: 'beijing',
    label: 'Beijing',
    children: [
      {
        value: 'chaoyang',
        label: 'ChaoYang',
        children: [
          {
            value: 'datunli',
            label: 'Datunli',
          },
        ],
      },
      {
        value: 'haidian',
        label: 'Haidian',
      },
      {
        value: 'dongcheng',
        label: 'Dongcheng',
      },
      {
        value: 'xicheng',
        label: 'Xicheng',
        children: [
          {
            value: 'jinrongjie',
            label: 'Jinrongjie',
          },
          {
            value: 'tianqiao',
            label: 'Tianqiao',
          },
        ],
      },
    ],
  },
  {
    value: 'shanghai',
    label: 'Shanghai',
    children: [
      {
        value: 'huangpu',
        label: 'Huangpu',
      },
    ],
  },
];
</script>
