// packages/docs/site/src/demos/color-picker/color-format.tsx
import { useState } from 'react';
import { ColorPicker, Radio } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [format, setFormat] = useState('hex');

  return (
    <div>
      <Radio.Group
        type="button"
        mode="fill"
        name="size"
        value={format}
        onChange={setFormat}
        style={{ marginBottom: 24 }}
      >
        {['hex', 'rgb'].map((x) => {
          return (
            <Radio key={x} value={x}>
              {x}
            </Radio>
          );
        })}
      </Radio.Group>
      <div style={{ marginTop: 10 }} />
      <ColorPicker defaultValue={'#165DFF'} showText format={format} />
    </div>
  );
}

// packages/docs/site/src/demos/color-picker/color-format.vue
<template>
  <Space direction="vertical">
    <RadioGroup type="button" v-model="format">
      <Radio v-for="item in formatList" :value="item">{{ item }}</Radio>
    </RadioGroup>
    <ColorPicker defaultValue="#165DFF" :format="format" showText />
  </Space>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const format = ref('hex');
const formatList = ['hex', 'rgb'];
</script>
