// packages/docs/site/src/demos/button/button-status.vue
<template>
  <Space direction="vertical">
    <Space>
      <Button type="primary" status="success">Primary</Button>
      <Button status="success">Default</Button>
      <Button type="dashed" status="success">Dashed</Button>
      <Button type="outline" status="success">Outline</Button>
      <Button type="text" status="success">Text</Button>
    </Space>
    <Space>
      <Button type="primary" status="warning">Primary</Button>
      <Button status="warning">Default</Button>
      <Button type="dashed" status="warning">Dashed</Button>
      <Button type="outline" status="warning">Outline</Button>
      <Button type="text" status="warning">Text</Button>
    </Space>
    <Space>
      <Button type="primary" status="danger">Primary</Button>
      <Button status="danger">Default</Button>
      <Button type="dashed" status="danger">Dashed</Button>
      <Button type="outline" status="danger">Outline</Button>
      <Button type="text" status="danger">Text</Button>
    </Space>
  </Space>
</template>

// packages/docs/site/src/demos/button/button-status.tsx
import { Button } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 100px)',
        gridRowGap: 24,
        gridColumnGap: 24,
      }}
    >
      <Button type="primary" status="warning">
        Warning
      </Button>
      <Button status="warning">Warning</Button>
      <Button type="outline" status="warning">
        Warning
      </Button>
      <Button type="text" status="warning">
        Warning
      </Button>

      <Button type="primary" status="danger">
        Danger
      </Button>
      <Button status="danger">Danger</Button>
      <Button type="outline" status="danger">
        Danger
      </Button>
      <Button type="text" status="danger">
        Danger
      </Button>

      <Button type="primary" status="success">
        Success
      </Button>
      <Button status="success">Success</Button>
      <Button type="outline" status="success">
        Success
      </Button>
      <Button type="text" status="success">
        Success
      </Button>
    </div>
  );
}
