// packages/docs/site/src/demos/button/long.vue
<template>
  <Space class="wrapper" direction="vertical">
    <Button type="primary" long>Primary</Button>
    <Button long>Default</Button>
    <Button type="dashed" long>Dashed</Button>
    <Button type="outline" long>Outline</Button>
    <Button type="text" long>Text</Button>
  </Space>
</template>

<style scoped>
.wrapper {
  width: 400px;
  padding: 20px;
  border: 1px solid var(--color-border);
  border-radius: 4px;
}
</style>

// packages/docs/site/src/demos/button/long.tsx
import { Button, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space
      style={{
        width: 360,
        border: '1px solid var(--color-border)',
        borderRadius: 4,
        padding: 20,
      }}
      direction="vertical"
      size="large"
    >
      <Button type="primary" long>
        Primary
      </Button>
      <Button type="secondary" long>
        Secondary
      </Button>
      <Button type="dashed" long>
        Dashed
      </Button>
      <Button type="default" long>
        Default
      </Button>
      <Button type="text" long>
        Text
      </Button>
    </Space>
  );
}
