// packages/docs/site/src/demos/cascader/searchable.vue
<template>
  <Cascader
    :options="options"
    :style="{ width: '320px' }"
    placeholder="Please select ..."
    allow-search
  />
</template>

<script setup lang="ts">
const options = [
  {
    value: 'beijing',
    label: 'Beijing',
    children: [
      {
        value: 'chaoyang',
        label: 'ChaoYang',
        children: [
          {
            value: 'datunli',
            label: 'Datunli',
          },
        ],
      },
      {
        value: 'haidian',
        label: 'Haidian',
      },
      {
        value: 'dongcheng',
        label: 'Dongcheng',
      },
      {
        value: 'xicheng',
        label: 'Xicheng',
        children: [
          {
            value: 'jinrongjie',
            label: 'Jinrongjie',
          },
          {
            value: 'tianqiao',
            label: 'Tianqiao',
          },
        ],
      },
    ],
  },
  {
    value: 'shanghai',
    label: 'Shanghai',
    children: [
      {
        value: 'huangpu',
        label: 'Huangpu',
      },
    ],
  },
];
</script>

// packages/docs/site/src/demos/cascader/searchable.tsx
import { Cascader, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  const options = [
    {
      id: 'beijing',
      name: 'Beijing',
      child: [
        {
          id: 'Beijing',
          name: 'Beijing',
          child: [
            {
              id: 'chaoyang',
              name: 'Chaoyang',
              child: [
                {
                  id: 'datunli',
                  name: 'Datunli',
                },
              ],
            },
            {
              id: 'dongcheng',
              name: 'Dongcheng',
            },
            {
              id: 'xicheng',
              name: 'Xicheng',
            },
            {
              id: 'haidian',
              name: 'Haidian',
            },
            {
              id: 'fengtai',
              name: 'fengtai',
            },
            {
              id: 'shijingshan',
              name: 'Shijingshan',
            },
            {
              id: 'mentougou',
              name: 'Mentougou',
            },
            {
              id: 'fangshan',
              name: 'Fangshan',
            },
            {
              id: 'tongzhou',
              name: 'Tongzhou',
            },
            {
              id: 'shunyi',
              name: 'Shunyi',
            },
          ],
        },
      ],
    },
    {
      id: 'shanghai',
      name: 'Shanghai',
      child: [
        {
          id: 'shanghaishi',
          name: 'Shanghai',
          child: [
            {
              id: 'huangpu',
              name: 'Huangpu',
            },
          ],
        },
      ],
    },
  ];

  return (
    <Space size="large">
      <Cascader
        placeholder="Please select ..."
        style={{ width: 300, marginBottom: 20 }}
        options={options}
        defaultValue={['shanghai', 'shanghaishi', 'huangpu']}
        showSearch
        allowClear
        fieldNames={{
          children: 'child',
          label: 'name',
          value: 'id',
        }}
      />
      <Cascader
        mode="multiple"
        placeholder="Please select ..."
        style={{ width: 300, marginBottom: 20 }}
        onChange={(x, y) => {
          console.log(x, y);
        }}
        options={options}
        defaultValue={[['beijing', 'Beijing', 'chaoyang', 'datunli']]}
        showSearch={{ retainInputValueWhileSelect: false }}
        allowClear
        fieldNames={{
          children: 'child',
          label: 'name',
          value: 'id',
        }}
      />
    </Space>
  );
}
