// packages/starbucks-design-react/src/pro/form-layout/FormControlArea.tsx
import type { CSSProperties } from 'react'
import type { FormControlAreaProps } from './interface'

export function FormControlArea(props: FormControlAreaProps) {
  const { minHeight, align = 'center', children, className, style } = props

  return (
    <div
      className={[
        'sbux-pro-form-control-area',
        `sbux-pro-form-control-area-align-${align}`,
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={{ ...(minHeight === undefined ? {} : { minHeight }), ...style } as CSSProperties}
    >
      {children}
    </div>
  )
}

// packages/starbucks-design-vue/src/pro/form-layout/FormControlArea.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { FormControlAreaProps } from './interface'

defineOptions({ name: 'FormControlArea' })

const props = withDefaults(defineProps<FormControlAreaProps>(), { align: 'center' })

const areaStyle = computed(() => ({
  ...(props.minHeight === undefined
    ? {}
    : { minHeight: typeof props.minHeight === 'number' ? `${props.minHeight}px` : props.minHeight }),
}))
</script>

<template>
  <div
    :class="['sbux-pro-form-control-area', `sbux-pro-form-control-area-align-${props.align}`, props.class]"
    :style="[areaStyle, props.style]"
  >
    <slot />
  </div>
</template>
