// packages/starbucks-design-react/src/pro/form-layout/StepFormLayout.tsx
import { hasNode } from '../_utils/has-node'
import type { StepFormLayoutProps } from './interface'

export function StepFormLayout(props: StepFormLayoutProps) {
  const { steps, actions, stickyActions = false, children, className, style } = props

  return (
    <div
      className={[
        'sbux-pro-step-form-layout',
        stickyActions ? 'sbux-pro-step-form-layout-sticky-actions' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      style={style}
    >
      {hasNode(steps) && <div className="sbux-pro-step-form-layout-steps">{steps}</div>}
      <div className="sbux-pro-step-form-layout-content">{children}</div>
      {hasNode(actions) && <div className="sbux-pro-step-form-layout-actions">{actions}</div>}
    </div>
  )
}

// packages/starbucks-design-vue/src/pro/form-layout/StepFormLayout.vue
<script setup lang="ts">
import type { StepFormLayoutProps } from './interface'

defineOptions({ name: 'StepFormLayout' })

const props = withDefaults(defineProps<StepFormLayoutProps>(), { stickyActions: false })
</script>

<template>
  <div
    :class="[
      'sbux-pro-step-form-layout',
      { 'sbux-pro-step-form-layout-sticky-actions': props.stickyActions },
      props.class,
    ]"
    :style="props.style"
  >
    <div v-if="$slots.steps" class="sbux-pro-step-form-layout-steps"><slot name="steps" /></div>
    <div class="sbux-pro-step-form-layout-content"><slot /></div>
    <div v-if="$slots.actions" class="sbux-pro-step-form-layout-actions"><slot name="actions" /></div>
  </div>
</template>
