// packages/docs/site/src/demos/typography/ellipsis.tsx
import { Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  const mockText =
    'A design is a plan or specification for the construction of an object or system or for the implementation of an activity or process, or the result of that plan or specification in the form of a prototype, product or process. The verb to design expresses the process of developing a design. The verb to design expresses the process of developing a design. A design is a plan or specification for the construction of an object or system or for the implementation of an activity or process, or the result of that plan or specification in the form of a prototype, product or process. The verb to design expresses the process of developing a design. The verb to design expresses the process of developing a design.';
  const mockTitle =
    ' A design is a plan or specification for the construction of an object or system or for the implementation of an activity or process.';

  return (
    <div>
      <Typography.Title heading={4} ellipsis={{ wrapper: 'span' }}>
        {mockTitle}
      </Typography.Title>
      <Typography.Paragraph ellipsis={{ rows: 2, showTooltip: true, expandable: true, wrapper: 'span' }}>
        {mockText}
      </Typography.Paragraph>
      <Typography.Paragraph ellipsis={{ suffix: '---width: 100%', wrapper: 'span' }}>{mockTitle}</Typography.Paragraph>
    </div>
  );
}

// packages/docs/vue/components/general/demos/typography/ellipsis.vue
<template>
  <div>
    <TypographyTitle :heading="4" ellipsis>
      A design is a plan or specification for the construction of an object or
      system or for the implementation of an activity or process.
    </TypographyTitle>
    <TypographyParagraph
      :ellipsis="{
        rows: 2,
        showTooltip: true,
      }"
    >
      A design is a plan or specification for the construction of an object or
      system or for the implementation of an activity or process, or the result
      of that plan or specification in the form of a prototype, product or
      process. The verb to design expresses the process of developing a design.
      The verb to design expresses the process of developing a design.A design
      is a plan or specification for the construction of an object or system or
      for the implementation of an activity or process, or the result of that
      plan or specification in the form of a prototype, product or process. The
      verb to design expresses the process of developing a design. The verb to
      design expresses the process of developing a design.
    </TypographyParagraph>
    <TypographyParagraph
      :ellipsis="{
        rows: 2,
        showTooltip: true,
        css: true,
      }"
    >
      A design is a plan or specification for the construction of an object or
      system or for the implementation of an activity or process, or the result
      of that plan or specification in the form of a prototype, product or
      process. The verb to design expresses the process of developing a design.
      The verb to design expresses the process of developing a design.A design
      is a plan or specification for the construction of an object or system or
      for the implementation of an activity or process, or the result of that
      plan or specification in the form of a prototype, product or process. The
      verb to design expresses the process of developing a design. The verb to
      design expresses the process of developing a design.
    </TypographyParagraph>
    <TypographyParagraph
      :ellipsis="{
        suffix: '--Arco Design',
        rows: 2,
        expandable: true,
        showTooltip: {
          type: 'popover',
          props: {
            style: { maxWidth: `500px` },
          },
        },
      }"
    >
      <template #expand-node="{ expanded }">
        {{ expanded ? '' : 'More' }}
      </template>
      A design is a plan or specification for the construction of an object or
      system or for the implementation of an activity or process, or the result
      of that plan or specification in the form of a prototype, product or
      process. The verb to design expresses the process of developing a design.
      The verb to design expresses the process of developing a design.A design
      is a plan or specification for the construction of an object or system or
      for the implementation of an activity or process, or the result of that
      plan or specification in the form of a prototype, product or process. The
      verb to design expresses the process of developing a design. The verb to
      design expresses the process of developing a design.
    </TypographyParagraph>
    <TypographyParagraph
      :ellipsis="{
        suffix: '--Arco Design',
        rows: 3,
        expandable: true,
      }"
    >
      A design is a plan or specification for the construction of an object or
      system or for the implementation of an activity or process, or the result
      of that plan or specification in the form of a prototype, product or
      process. The verb to design expresses the process of developing a design.
      The verb to design expresses the process of developing a design. A design
      is a plan or specification for the construction of an object or system or
      for the implementation of an activity or process, or the result of that
      plan or specification in the form of a prototype, product or process. The
      verb to design expresses the process of developing a design. The verb to
      design expresses the process of developing a design.
    </TypographyParagraph>
  </div>
</template>
