// packages/docs/site/src/demos/tabs/dynamic-tabs.tsx
import { useState } from 'react';
import { Tabs, Typography } from '@sbux/starbucks-design-react';

export default function Demo() {

  let count = 5;
  const style = {
    textAlign: 'center',
    marginTop: 20,
  };
  const initTabs = [...new Array(count)].map((x, i) => ({
    title: `Tab ${i + 1}`,
    key: `key${i + 1}`,
    content: `${i + 1}`,
  }));

  const [tabs, setTabs] = useState(initTabs);
  const [activeTab, setActiveTab] = useState('key2');

  const handleAddTab = () => {
    const newTab = {
      title: `New Tab${++count}`,
      key: `new key${count}`,
      content: `${count}`,
    };
    setTabs([...tabs, newTab]);
    setActiveTab(newTab.key);
  };

  const handleDeleteTab = (key) => {
    const index = tabs.findIndex((x) => x.key === key);
    const newTabs = tabs.slice(0, index).concat(tabs.slice(index + 1));

    if (key === activeTab && index > -1 && newTabs.length) {
      setActiveTab(newTabs[index] ? newTabs[index].key : newTabs[index - 1].key);
    }

    if (index > -1) {
      setTabs(newTabs);
    }
  };

  return (
    <Tabs
      editable
      type="card-gutter"
      activeTab={activeTab}
      onAddTab={handleAddTab}
      onDeleteTab={handleDeleteTab}
      onChange={setActiveTab}
    >
      {tabs.map((x, i) => (
        <Tabs.TabPane destroyOnHide key={x.key} title={x.title}>
          <Typography.Paragraph
            style={style}
          >{`Content of Tab Panel ${x.content}`}</Typography.Paragraph>
        </Tabs.TabPane>
      ))}
    </Tabs>
  );
}

// packages/docs/vue/components/data-display/demos/tabs/dynamic-tabs.vue
<template>
  <Tabs
    type="card-gutter"
    :editable="true"
    @add="handleAdd"
    @delete="handleDelete"
    show-add-button
    auto-switch
  >
    <TabPane
      v-for="(item, index) of data"
      :key="item.key"
      :title="item.title"
      :closable="index !== 2"
    >
      {{ item?.content }}
    </TabPane>
  </Tabs>
</template>

<script setup lang="ts">
import { ref } from 'vue';

let count = 5;

const data = ref([
  {
    key: '1',
    title: 'Tab 1',
    content: 'Content of Tab Panel 1',
  },
  {
    key: '2',
    title: 'Tab 2',
    content: 'Content of Tab Panel 2',
  },
  {
    key: '3',
    title: 'Tab 3',
    content: 'Content of Tab Panel 3',
  },
  {
    key: '4',
    title: 'Tab 4',
    content: 'Content of Tab Panel 4',
  },
]);

const handleAdd = () => {
  const number = count++;
  data.value = data.value.concat({
    key: `${number}`,
    title: `New Tab ${number}`,
    content: `Content of New Tab Panel ${number}`,
  });
};
const handleDelete = (key) => {
  data.value = data.value.filter((item) => item.key !== key);
};
</script>
