// packages/docs/site/src/demos/page-header/transparent-bg.vue
<template>
  <div style="margin-bottom: 20px">
    <RadioGroup type="button" default-value="large">
      <Radio value="mini">Mini</Radio>
      <Radio value="small">Small</Radio>
      <Radio value="large">Large</Radio>
    </RadioGroup>
  </div>
  <div
    :style="{
      backgroundImage:
        'radial-gradient(var(--color-fill-3) 1px, rgba(0, 0, 0, 0) 1px)',
      backgroundSize: '16px 16px',
      padding: '28px',
    }"
  >
    <PageHeader title="Starbucks" subtitle="Starbucks Vue 2.0">
      <template #breadcrumb>
        <Breadcrumb>
          <BreadcrumbItem>Home</BreadcrumbItem>
          <BreadcrumbItem>Channel</BreadcrumbItem>
          <BreadcrumbItem>News</BreadcrumbItem>
        </Breadcrumb>
      </template>
    </PageHeader>
  </div>
</template>

// packages/docs/site/src/demos/page-header/transparent-bg.tsx
import { PageHeader, Radio, Message } from '@sbux/starbucks-design-react';

export default function Demo() {
  const ghostBgStyle = {
    backgroundImage: 'radial-gradient(var(--color-fill-3) 1px, rgba(0, 0, 0, 0) 1px)',
    backgroundSize: '16px 16px',
    padding: 20,
  };

  return (
    <>
      <Radio.Group
        mode="fill"
        type="button"
        defaultValue="small"
        style={{ marginBottom: 20 }}
      >
        <Radio value="large">Large</Radio>
        <Radio value="medium">Medium</Radio>
        <Radio value="small">Small</Radio>
      </Radio.Group>
      <div style={ghostBgStyle}>
        <PageHeader
          title="Starbucks"
          subTitle="This is a description"
          backIcon
          onBack={() => Message.info('点击了返回按钮')}
        />
      </div>
    </>
  );
}
