// packages/docs/site/src/demos/page-header/with-breadcrumb.tsx
import { PageHeader, Radio } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <>
      <Radio.Group
        mode="fill"
        type="button"
        defaultValue="small"
        style={{ marginBottom: 20 }}
      >
        <Radio value="large">Large</Radio>
        <Radio value="medium">Medium</Radio>
        <Radio value="small">Small</Radio>
      </Radio.Group>
      <div style={{ background: 'var(--color-fill-2)', padding: 40 }}>
        <PageHeader
          style={{ background: 'var(--color-bg-2)' }}
          title="Starbucks"
          subTitle="This is a description"
          breadcrumb={{
            routes: [
              {
                path: '/',
                breadcrumbName: 'Home',
              },
              {
                path: '/channel',
                breadcrumbName: 'Channel',
              },
              {
                path: '/news',
                breadcrumbName: 'News',
              },
            ],
          }}
        />
      </div>
    </>
  );
}

// packages/docs/site/src/demos/page-header/with-breadcrumb.vue
<template>
  <div style="margin-bottom: 20px">
    <RadioGroup type="button" default-value="large">
      <Radio value="mini">Mini</Radio>
      <Radio value="small">Small</Radio>
      <Radio value="large">Large</Radio>
    </RadioGroup>
  </div>
  <div :style="{ background: 'var(--color-fill-2)', padding: '28px' }">
    <PageHeader
      :style="{ background: 'var(--color-bg-2)' }"
      title="Starbucks"
      subtitle="Starbucks Vue 2.0"
      :show-back="false"
    >
      <template #breadcrumb>
        <Breadcrumb>
          <BreadcrumbItem>Home</BreadcrumbItem>
          <BreadcrumbItem>Channel</BreadcrumbItem>
          <BreadcrumbItem>News</BreadcrumbItem>
        </Breadcrumb>
      </template>
    </PageHeader>
  </div>
</template>
