// packages/docs/site/src/demos/message/closable.vue
<template>
  <Button @click="handleClick">Closeable Message</Button>
</template>

<script setup lang="ts">
import { getCurrentInstance } from 'vue';
import { Message } from '@sbux/starbucks-design-vue';

// Capture this island's appContext so the imperative Message API inherits the
// `arco-v` prefix-cls from the ConfigProvider in VueDemoLoader.vue — see
// scripts/docs-migration/RULES.md rule 5 addendum for why this is required.
const appContext = getCurrentInstance()!.appContext;

const handleClick = () => {
  Message.info(
    {
      content: 'This is an info message!',
      closable: true,
    },
    appContext
  );
};
</script>

// packages/docs/site/src/demos/message/closable.tsx
import { Button, Message } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Button
      onClick={() => {
        Message.info({
          content: 'This is a message!',
          closable: true,
          duration: 10000
        })
      }}
      type="primary"
    >
      Open Message
    </Button>
  );
}
