// packages/docs/site/src/demos/anchor/affix-style.vue
<template>
  <Anchor :offset-bottom="40" :affix-style="affixStyle">
    <AnchorLink href="#basic">Basic</AnchorLink>
    <AnchorLink href="#static">Static</AnchorLink>
    <AnchorLink href="#line-less">LineLess Mode</AnchorLink>
    <AnchorLink href="#affix">Affix</AnchorLink>
    <AnchorLink href="#boundary">Scroll Boundary</AnchorLink>
    <AnchorLink href="#hash">Hash mode</AnchorLink>
  </Anchor>
</template>

<script setup lang="ts">
const affixStyle = {
  position: 'absolute',
  right: '-170px',
  top: '50%',
  zIndex: 1,
};
</script>

// packages/docs/site/src/demos/anchor/affix-style.tsx
import { Anchor } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Anchor
      offsetBottom={40}
      affixStyle={{
        position: 'absolute',
        right: -170,
        top: '50%',
        zIndex: 1,
      }}
    >
      <Anchor.Link href="#Basic" title="Basic" />
      <Anchor.Link href="#Static" title="Static" />
      <Anchor.Link href="#Lineless-mode" title="Lineless mode" />
      <Anchor.Link href="#Affix" title="Affix" />
      <Anchor.Link href="#Scroll-boundary" title="Scroll boundary" />
      <Anchor.Link href="#Hash-mode" title="Hash mode" />
    </Anchor>
  );
}
