// packages/starbucks-design-react/src/business/filter-bar/FilterBar.tsx
import { useId } from 'react'
import { Button } from '@arco-design/web-react'
import { IconDown, IconUp } from '@arco-design/web-react/icon/index.js'
import { resolveResponsiveFieldSpans } from './layout'
import type { FilterBarProps } from './interface'
import { renderFilterFieldControl } from './adapters'
import { useFilterBar } from './use-filter-bar'

const cx = (...classes: Array<string | false | undefined>) => classes.filter(Boolean).join(' ')

export const FilterBar = (props: FilterBarProps) => {
  const state = useFilterBar(props)
  const idPrefix = useId().replace(/:/g, '')

  if (state.layout.eligibleFields.length === 0) {
    return null
  }

  const showExpandToggle = state.layout.collapsible && props.collapsible !== false
  const describedByIds = (fieldName: string, help?: string, hasError?: boolean) =>
    [
      help ? `${idPrefix}-${fieldName}-help` : undefined,
      hasError ? `${idPrefix}-${fieldName}-error` : undefined,
    ]
      .filter(Boolean)
      .join(' ') || undefined

  return (
    <div
      className={cx('sbux-filter-bar', props.className)}
      style={props.style}
      data-expanded={state.expanded ? 'true' : 'false'}
      data-collapsible={state.layout.collapsible ? 'true' : 'false'}
      data-loading={props.loading ? 'true' : 'false'}
      data-disabled={props.disabled ? 'true' : 'false'}
    >
      <div
        className="sbux-filter-bar__fields"
        data-columns-xs={state.columns.xs}
        data-columns-sm={state.columns.sm}
        data-columns-md={state.columns.md}
        data-columns-lg={state.columns.lg}
        data-columns-xl={state.columns.xl}
        data-columns-xxl={state.columns.xxl}
      >
        {state.layout.renderedFields.map((field) => {
          const error = state.errorsByName.get(field.name)
          const controlId = `${idPrefix}-${field.name}-control`
          const helpId = `${idPrefix}-${field.name}-help`
          const errorId = `${idPrefix}-${field.name}-error`
          const describedBy = describedByIds(field.name, field.help, Boolean(error))
          const fieldSpans = resolveResponsiveFieldSpans(field.span, state.columns)

          return (
            <div
              key={field.name}
              className="sbux-filter-bar__field"
              data-field-name={field.name}
              data-field-type={field.type}
              data-span={fieldSpans.xxl}
              data-span-xs={fieldSpans.xs}
              data-span-sm={fieldSpans.sm}
              data-span-md={fieldSpans.md}
              data-span-lg={fieldSpans.lg}
              data-span-xl={fieldSpans.xl}
              data-span-xxl={fieldSpans.xxl}
            >
              <label className="sbux-filter-bar__label" htmlFor={controlId}>
                {field.required && <span className="sbux-filter-bar__required">*</span>}
                <span className="sbux-filter-bar__label-text">{field.label}</span>
              </label>
              <div
                className="sbux-filter-bar__control"
                ref={(element) => state.registerControlElement(field.name, element)}
                tabIndex={-1}
              >
                {renderFilterFieldControl({
                  field,
                  value: state.draftValues[field.name],
                  disabled: state.isFieldDisabled(field),
                  error,
                  controlId,
                  describedBy,
                  renderField: props.renderField,
                  onChange: (value) => state.handleFieldChange(field, value),
                })}
              </div>
              {field.help && (
                <div className="sbux-filter-bar__help" id={helpId}>
                  {field.help}
                </div>
              )}
              {error && (
                <div className="sbux-filter-bar__error" id={errorId} role="alert">
                  {error.message}
                </div>
              )}
            </div>
          )
        })}
      </div>
      <div className="sbux-filter-bar__actions">
        {!state.expanded && state.hiddenActiveSummaryCount > 0 && (
          <span className="sbux-filter-bar__hidden-summary" aria-live="polite">
            {state.texts.hiddenActiveSummary(state.hiddenActiveSummaryCount)}
          </span>
        )}
        <div className="sbux-filter-bar__buttons">
          {state.showSubmit && (
            <Button
              className="sbux-filter-bar__submit"
              type="primary"
              loading={props.loading}
              disabled={state.isInteractiveDisabled}
              onClick={state.handleSubmit}
            >
              {state.texts.submit}
            </Button>
          )}
          {state.showReset && (
            <Button
              className="sbux-filter-bar__reset"
              disabled={state.isInteractiveDisabled}
              onClick={state.handleReset}
            >
              {state.texts.reset}
            </Button>
          )}
          {showExpandToggle && (
            <Button
              className="sbux-filter-bar__expand"
              type="text"
              icon={state.expanded ? <IconUp /> : <IconDown />}
              aria-label={state.expanded ? state.texts.collapse : state.texts.expand}
              aria-expanded={state.expanded}
              disabled={props.disabled}
              onClick={() => state.handleExpandedChange(!state.expanded)}
            >
              {state.expanded ? state.texts.collapse : state.texts.expand}
            </Button>
          )}
        </div>
      </div>
    </div>
  )
}

// packages/starbucks-design-vue/src/business/filter-bar/FilterBar.vue
<script setup lang="ts">
import { computed, useId, useSlots } from 'vue'
import { Button as AButton } from '@arco-design/web-vue'
import { IconDown, IconUp } from '@arco-design/web-vue/es/icon'
import type {
  FilterBarEmits,
  FilterBarProps,
  FilterFieldSchema,
  FilterRenderFieldContext,
} from './interface'
import { resolveResponsiveFieldSpans } from './layout'
import { getFilterFieldAdapter } from './adapters'
import { useFilterBar } from './use-filter-bar'

defineOptions({ name: 'FilterBar' })

const props = withDefaults(defineProps<FilterBarProps>(), {
  fields: () => [],
  collapsible: undefined,
  expanded: undefined,
  submitMode: 'manual',
  debounceMs: 300,
  submitOnReset: true,
  defaultExpanded: false,
  loading: false,
  disabled: false,
  showSubmit: undefined,
  showReset: undefined,
})

const emit = defineEmits<FilterBarEmits>()
const slots = useSlots()
const state = useFilterBar(props, emit)
const idPrefix = useId().replace(/:/g, '')
const {
  columns,
  draftValues,
  expanded,
  layout,
  errorsByName,
  texts,
  showSubmit,
  showReset,
  hiddenActiveSummaryCount,
  isInteractiveDisabled,
  isFieldDisabled,
  registerControlElement,
  handleFieldChange,
  handleSubmit,
  handleReset,
  handleExpandedChange,
} = state

const showExpandToggle = computed(
  () => layout.value.collapsible && props.collapsible !== false,
)
const getResponsiveFieldSpans = (field: FilterFieldSchema) =>
  resolveResponsiveFieldSpans(field.span, columns.value)

const getControlId = (field: FilterFieldSchema) => `${idPrefix}-${field.name}-control`
const getHelpId = (field: FilterFieldSchema) => `${idPrefix}-${field.name}-help`
const getErrorId = (field: FilterFieldSchema) => `${idPrefix}-${field.name}-error`
const getDescribedBy = (field: FilterFieldSchema) => {
  const error = errorsByName.value.get(field.name)
  return [
    field.help ? getHelpId(field) : undefined,
    error ? getErrorId(field) : undefined,
  ].filter(Boolean).join(' ') || undefined
}
const getAdapter = (field: FilterFieldSchema) =>
  getFilterFieldAdapter({
    field,
    value: draftValues.value[field.name],
    disabled: isFieldDisabled(field),
    error: errorsByName.value.get(field.name),
    controlId: getControlId(field),
    describedBy: getDescribedBy(field),
    onChange: (value) => handleFieldChange(field, value),
  })
const getRenderFieldContext = (field: FilterFieldSchema): FilterRenderFieldContext => ({
  field,
  value: draftValues.value[field.name],
  disabled: isFieldDisabled(field),
  error: errorsByName.value.get(field.name),
  controlId: getControlId(field),
  onChange: (value) => handleFieldChange(field, value),
})
</script>

<template>
  <div
    v-if="layout.eligibleFields.length > 0"
    class="sbux-filter-bar"
    :data-expanded="expanded ? 'true' : 'false'"
    :data-collapsible="layout.collapsible ? 'true' : 'false'"
    :data-loading="loading ? 'true' : 'false'"
    :data-disabled="disabled ? 'true' : 'false'"
  >
    <div
      class="sbux-filter-bar__fields"
      :data-columns-xs="columns.xs"
      :data-columns-sm="columns.sm"
      :data-columns-md="columns.md"
      :data-columns-lg="columns.lg"
      :data-columns-xl="columns.xl"
      :data-columns-xxl="columns.xxl"
    >
      <div
        v-for="field in layout.renderedFields"
        :key="field.name"
        class="sbux-filter-bar__field"
        :data-field-name="field.name"
        :data-field-type="field.type"
        :data-span="getResponsiveFieldSpans(field).xxl"
        :data-span-xs="getResponsiveFieldSpans(field).xs"
        :data-span-sm="getResponsiveFieldSpans(field).sm"
        :data-span-md="getResponsiveFieldSpans(field).md"
        :data-span-lg="getResponsiveFieldSpans(field).lg"
        :data-span-xl="getResponsiveFieldSpans(field).xl"
        :data-span-xxl="getResponsiveFieldSpans(field).xxl"
      >
        <label class="sbux-filter-bar__label" :for="getControlId(field)">
          <span v-if="field.required" class="sbux-filter-bar__required">*</span>
          <span class="sbux-filter-bar__label-text">{{ field.label }}</span>
        </label>
        <div
          :ref="(element) => registerControlElement(field.name, element as HTMLElement | null)"
          class="sbux-filter-bar__control"
          tabindex="-1"
        >
          <slot
            v-if="slots.field"
            name="field"
            v-bind="getRenderFieldContext(field)"
          />
          <component
            :is="getAdapter(field).component"
            v-else
            v-bind="getAdapter(field).props"
            v-on="getAdapter(field).events"
          />
        </div>
        <div v-if="field.help" :id="getHelpId(field)" class="sbux-filter-bar__help">
          {{ field.help }}
        </div>
        <div
          v-if="errorsByName.get(field.name)"
          :id="getErrorId(field)"
          class="sbux-filter-bar__error"
          role="alert"
        >
          {{ errorsByName.get(field.name)?.message }}
        </div>
      </div>
    </div>
    <div class="sbux-filter-bar__actions">
      <span
        v-if="
          !expanded &&
          layout.collapsedFieldNames.length > 0 &&
          hiddenActiveSummaryCount > 0
        "
        class="sbux-filter-bar__hidden-summary"
        aria-live="polite"
      >
        {{ texts.hiddenActiveSummary(hiddenActiveSummaryCount) }}
      </span>
      <div class="sbux-filter-bar__buttons">
        <AButton
          v-if="showSubmit"
          class="sbux-filter-bar__submit"
          type="primary"
          :loading="loading"
          :disabled="isInteractiveDisabled"
          @click="handleSubmit"
        >
          {{ texts.submit }}
        </AButton>
        <AButton
          v-if="showReset"
          class="sbux-filter-bar__reset"
          :disabled="isInteractiveDisabled"
          @click="handleReset"
        >
          {{ texts.reset }}
        </AButton>
        <AButton
          v-if="showExpandToggle"
          class="sbux-filter-bar__expand"
          type="text"
          :disabled="disabled"
          :aria-label="expanded ? texts.collapse : texts.expand"
          :aria-expanded="expanded"
          @click="handleExpandedChange(!expanded)"
        >
          <template #icon>
            <IconUp v-if="expanded" />
            <IconDown v-else />
          </template>
          {{ expanded ? texts.collapse : texts.expand }}
        </AButton>
      </div>
    </div>
  </div>
</template>
