// packages/docs/site/src/demos/transfer/tree-transfer.tsx
import { useState } from 'react';
import { Transfer, Tree } from '@sbux/starbucks-design-react';

export default function Demo() {
  const treeData = [
    {
      key: '1',
      title: 'Trunk 1',
      children: [
        {
          key: '1-1',
          title: 'Branch',
          children: [
            {
              key: '1-1-1',
              title: 'Leaf',
            },
            {
              key: '1-1-2',
              title: 'Leaf',
            },
          ],
        },
      ],
    },
    {
      key: '2',
      title: 'Trunk 2',
      children: [
        {
          key: '2-1',
          title: 'Trunk 2-1',
        },
        {
          key: '2-2',
          title: 'Trunk 2-2',
        },
        {
          key: '2-3',
          title: 'Trunk 2-3',
        },
      ],
    },
    {
      key: '3',
      title: 'Trunk 3',
    },
    {
      key: '4',
      title: 'Trunk 4',
    },
  ];

  const TreeTransfer = ({ dataSource, targetKeys, ...restProps }) => {
    const generateTreeData = (treeNodes = [], checkedKeys = []) => {
      return treeNodes.map(({ children, ...props }) => ({
        ...props,
        disabled: checkedKeys.includes(props.key),
        children: generateTreeData(children, checkedKeys),
      }));
    };

    const generateTransferData = (list = [], transferDataSource = []) => {
      list.forEach((item) => {
        transferDataSource.push(item);
        generateTransferData(item.children, transferDataSource);
      });
      return transferDataSource;
    };

    const transferDataSource = generateTransferData(dataSource);
    const treeData = generateTreeData(dataSource, targetKeys);
    return (
      <Transfer
        targetKeys={targetKeys}
        dataSource={transferDataSource}
        render={(item) => item.title}
        {...restProps}
      >
        {({ listType, onItemSelect, selectedKeys }) => {
          if (listType === 'source') {
            const checkedKeys = [...selectedKeys, ...targetKeys];
            return (
              <Tree
                style={{
                  padding: '0 14px',
                }}
                blockNode
                checkable
                checkStrictly
                treeData={treeData}
                checkedKeys={checkedKeys}
                onCheck={(_, { node: { key } }) => {
                  onItemSelect(key, checkedKeys.indexOf(key) === -1);
                }}
                onSelect={(_, { node: { key } }) => {
                  onItemSelect(key, checkedKeys.indexOf(key) === -1);
                }}
              />
            );
          }
        }}
      </Transfer>
    );
  };

  const [targetKeys, setTargetKeys] = useState(['2-1', '2-2', '2-3', '4']);

  const onChange = (keys) => {
    setTargetKeys(keys);
  };

  return (
    <TreeTransfer
      dataSource={treeData}
      defaultSelectedKeys={['1-1-1']}
      targetKeys={targetKeys}
      onChange={onChange}
    />
  );
}

// packages/docs/vue/components/data-entry/demos/transfer/tree-transfer.vue
<template>
  <Transfer :data="transferData" :default-value="value">
    <template #source="{ data, selectedKeys, handleSelect }">
      <Tree
        :checkable="true"
        checked-strategy="child"
        :checked-keys="selectedKeys"
        :data="getTreeData(data)"
        @check="handleSelect"
      />
    </template>
  </Transfer>
</template>

<script setup lang="ts">
const treeData = [
  {
    title: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Leaf 0-0-1',
        key: '0-0-1',
      },
      {
        title: 'Branch 0-0-2',
        key: '0-0-2',
        children: [
          {
            title: 'Leaf 0-0-2-1',
            key: '0-0-2-1',
          },
          {
            title: 'Leaf 0-0-2-2',
            key: '0-0-2-2',
          },
        ],
      },
    ],
  },
  {
    title: 'Trunk 0-1',
    key: '0-1',
    children: [
      {
        title: 'Branch 0-1-1',
        key: '0-1-1',
        children: [
          {
            title: 'Leaf 0-1-1-1',
            key: '0-1-1-1',
          },
          {
            title: 'Leaf 0-1-1-2',
            key: '0-1-1-2',
          },
        ],
      },
      {
        title: 'Leaf 0-1-2',
        key: '0-1-2',
      },
    ],
  },
];

const getTransferData = (treeData = [], transferDataSource = []) => {
  treeData.forEach((item) => {
    if (item.children) getTransferData(item.children, transferDataSource);
    else transferDataSource.push({ label: item.title, value: item.key });
  });
  return transferDataSource;
};

const getTreeData = (data = []) => {
  const values = data.map((item) => item.value);

  const travel = (_treeData = []) => {
    const treeDataSource = [];
    _treeData.forEach((item) => {
      if (item.children || values.includes(item.key)) {
        treeDataSource.push({
          title: item.title,
          key: item.key,
          children: travel(item.children),
        });
      }
    });
    return treeDataSource;
  };

  return travel(treeData);
};

const transferData = getTransferData(treeData);

const value = ['0-0-2-1'];
</script>
