// packages/docs/site/src/demos/list/basic-usage.tsx
import { List } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <List
      style={{ width: 622 }}
      size="small"
      header="List title"
      dataSource={[
        'Beijing Bytedance Technology Co., Ltd.',
        'Bytedance Technology Co., Ltd.',
        'Beijing Toutiao Technology Co., Ltd.',
        'Beijing Volcengine Technology Co., Ltd.',
        'China Beijing Bytedance Technology Co., Ltd.',
      ]}
      render={(item, index) => <List.Item key={index}>{item}</List.Item>}
    />
  );
}

// packages/docs/vue/components/data-display/demos/list/basic-usage.vue
<template>
  <List>
    <template #header> List title </template>
    <ListItem>Beijing Bytedance Technology Co., Ltd.</ListItem>
    <ListItem>Bytedance Technology Co., Ltd.</ListItem>
    <ListItem>Beijing Toutiao Technology Co., Ltd.</ListItem>
    <ListItem>Beijing Volcengine Technology Co., Ltd.</ListItem>
    <ListItem>China Beijing Bytedance Technology Co., Ltd.</ListItem>
  </List>
</template>
