// packages/docs/site/src/demos/alert/closable.tsx
import { Alert, Grid } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Grid.Row gutter={40}>
        <Grid.Col span={12}>
          <Alert closable style={{ marginBottom: 20 }} type="info" content="Here is an info text" />
          <Alert
            closable
            style={{ marginBottom: 20 }}
            type="warning"
            title="Warning"
            content="Here is a warning text"
          />
        </Grid.Col>
        <Grid.Col span={12}>
          <Alert closable style={{ marginBottom: 20 }} type="success" content="Here is a success text" />
          <Alert closable style={{ marginBottom: 20 }} type="error" title="Error" content="Here is an error text" />
        </Grid.Col>
      </Grid.Row>
    </div>
  );
}

// packages/docs/vue/components/feedback/demos/alert/closable.vue
<template>
  <Row :gutter="[40, 20]">
    <Col :span="12">
      <Alert closable>This is an info alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="success" closable>This is an success alert.</Alert>
    </Col>
    <Col :span="12">
      <Alert type="warning" closable>
        <template #title> Warning </template>
        This is an warning alert.
      </Alert>
    </Col>
    <Col :span="12">
      <Alert type="error" closable>
        <template #title> Error </template>
        This is an error alert.
      </Alert>
    </Col>
  </Row>
</template>
