// packages/docs/vue/components/feedback/demos/modal/confirm-dialog.vue
<template>
  <Button type="primary" @click="handleClick">Confirm</Button>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { Modal } from '@arco-design/web-vue';

const handleClick = () => {
  Modal.confirm({
    title: 'Confirm deletion',
    content:
      'Are you sure you want to delete the 3 selected items? Once you press the delete button, the items will be deleted immediately. You can’t undo this action.',
    okButtonProps: {
      status: 'danger',
    },
  });
};
</script>

// packages/docs/site/src/demos/modal/confirm-dialog.tsx
import { Button, Modal, Message } from '@sbux/starbucks-design-react';

export default function Demo() {
  function confirm() {
    Modal.confirm({
      title: 'Confirm deletion',
      content:
        'Are you sure you want to delete the 3 selected items? Once you press the delete button, the items will be deleted immediately. You can’t undo this action.',
      okButtonProps: {
        status: 'danger'
      },
      onOk: () => {
        return new Promise((resolve, reject) => {
          setTimeout(Math.random() > 0.5 ? resolve : reject, 1000)
        }).catch((e) => {
          Message.error({
            content: 'Error occurs!'
          })
          throw e
        })
      }
    })
  }
  return (
    <Button type="primary" onClick={confirm}>
      Confirm
    </Button>
  )
}
