// packages/docs/vue/components/data-display/demos/tree/dynamic-load.vue
<template>
  <Tree :data="treeData" :load-more="loadMore" />
</template>
<script setup lang="ts">
import { ref } from 'vue';

const treeData = ref([
  {
    title: 'Trunk 0-0',
    key: '0-0',
  },
  {
    title: 'Trunk 0-1',
    key: '0-1',
    children: [
      {
        title: 'Branch 0-1-1',
        key: '0-1-1',
      },
    ],
  },
]);

const loadMore = (nodeData) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      nodeData.children = [
        { title: `leaf`, key: `${nodeData.key}-1`, isLeaf: true },
      ];
      resolve();
    }, 1000);
  });
};
</script>

// packages/docs/site/src/demos/tree/dynamic-load.tsx
import React from 'react';
import { Tree } from '@sbux/starbucks-design-react';

export default function Demo() {
  const defaultTreeData = [
    {
      title: 'Trunk 0-0',
      key: '0-0',
    },
    {
      title: 'Trunk 0-1',
      key: '0-1',
      children: [
        {
          title: 'Branch 0-1-1',
          key: '0-1-1',
        },
      ],
    },
  ];

  const [treeData, setTreeData] = React.useState(defaultTreeData);

  const loadMore = (treeNode) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        treeNode.props.dataRef.children = [
          {
            title: `leaf`,
            key: `${treeNode.props._key}-1`,
            isLeaf: true,
          },
        ];
        setTreeData([...treeData]);
        resolve();
      }, 1000);
    });
  };

  return <Tree defaultSelectedKeys={['node1']} loadMore={loadMore} treeData={treeData}></Tree>;
}
