// packages/docs/site/src/demos/tree/set-fill-mode.tsx
import { useState } from 'react';
import { Radio, Tree, Typography } from '@sbux/starbucks-design-react';

export default function Demo() {
  const TreeData = [
    {
      title: 'Trunk 0-0',
      key: '0-0',
      children: [
        {
          title: 'Leaf',
          key: '0-0-1',
        },
        {
          title: 'Branch 0-0-2',
          key: '0-0-2',
          children: [
            {
              title: 'Leaf',
              key: '0-0-2-1',
            },
          ],
        },
      ],
    },
    {
      title: 'Trunk 0-1',
      key: '0-1',
      children: [
        {
          title: 'Branch 0-1-1',
          key: '0-1-1',
          children: [
            {
              title: 'Leaf',
              key: '0-1-1-1',
            },
            {
              title: 'Leaf',
              key: '0-1-1-2',
            },
          ],
        },
        {
          title: 'Leaf',
          key: '0-1-2',
        },
      ],
    },
  ];

  const [checkedKeys, setCheckedKeys] = useState(['0-0', '0-1']);
  const [checkedStrategy, setCheckedStrategy] = useState(Tree.SHOW_ALL);
  return (
    <div>
      <Radio.Group
        type="button"
        value={checkedStrategy}
        onChange={(value) => {
          setCheckedStrategy(value);
          setCheckedKeys([]);
        }}
        options={[
          {
            value: Tree.SHOW_ALL,
            label: 'show all',
          },
          {
            value: Tree.SHOW_PARENT,
            label: 'show parent',
          },
          {
            value: Tree.SHOW_CHILD,
            label: 'show child',
          },
        ]}
      />
      <div style={{ margin: '20px 0' }}>
        <Typography.Text>Current: {checkedKeys.join(' , ')}</Typography.Text>
      </div>
      <Tree
        checkedStrategy={checkedStrategy}
        checkable
        checkedKeys={checkedKeys}
        onCheck={(value, extra) => {
          setCheckedKeys(value);
        }}
        treeData={TreeData}
      ></Tree>
    </div>
  );
}

// packages/docs/site/src/demos/tree/set-fill-mode.vue
<template>
  <RadioGroup
    type="button"
    v-model="checkedStrategy"
    @change="
      (value) => {
        checkedKeys = [];
      }
    "
  >
    <Radio
      v-for="item in strategyOptions"
      :key="item?.value"
      :value="item?.value"
    >
      {{ item?.label }}
    </Radio>
  </RadioGroup>
  <br />
  <TypographyText style="margin: 24px 0; display: inline-block;">
    Current: {{ checkedKeys?.join(' , ') }}
  </TypographyText>
  <br />
  <Tree
    :checkable="true"
    v-model:checked-keys="checkedKeys"
    :checked-strategy="checkedStrategy"
    :data="treeData"
  />
</template>
<script setup lang="ts">
import { ref } from 'vue';

const treeData = [
  {
    title: 'Trunk 0-0',
    key: '0-0',
    children: [
      {
        title: 'Leaf',
        key: '0-0-1',
      },
      {
        title: 'Branch 0-0-2',
        key: '0-0-2',
        children: [
          {
            title: 'Leaf',
            key: '0-0-2-1',
          },
        ],
      },
    ],
  },
  {
    title: 'Trunk 0-1',
    key: '0-1',
    children: [
      {
        title: 'Branch 0-1-1',
        key: '0-1-1',
        children: [
          {
            title: 'Leaf',
            key: '0-1-1-1',
          },
          {
            title: 'Leaf',
            key: '0-1-1-2',
          },
        ],
      },
      {
        title: 'Leaf',
        key: '0-1-2',
      },
    ],
  },
];

const strategyOptions = [
  {
    value: 'all',
    label: 'show all',
  },
  {
    value: 'parent',
    label: 'show parent',
  },
  {
    value: 'child',
    label: 'show child',
  },
];

const checkedKeys = ref([]);
const checkedStrategy = ref('all');
</script>
