// packages/docs/site/src/demos/drawer/drawer-position.tsx
import React from 'react';
import { Button, Drawer, Radio } from '@sbux/starbucks-design-react';

export default function Demo() {
  const [visible, setVisible] = React.useState()
  const [placement, setPlacement] = React.useState('right')
  return (
    <div>
      <Radio.Group name="placement" defaultValue={placement} onChange={setPlacement}>
        <Radio value="top">Top</Radio>
        <Radio value="bottom">Bottom</Radio>
        <Radio value="left">Left</Radio>
        <Radio value="right">Right</Radio>
      </Radio.Group>
      <br />
      <Button
        onClick={() => {
          setVisible(true)
        }}
        type="primary"
        style={{ marginTop: 20 }}
      >
        Open Drawer
      </Button>
      <Drawer
        width={332}
        height={332}
        title={<span>Basic Information </span>}
        visible={visible}
        placement={placement}
        onOk={() => {
          setVisible(false)
        }}
        onCancel={() => {
          setVisible(false)
        }}
      >
        <div>Here is an example text. </div>
        <div>Here is an example text.</div>
      </Drawer>
    </div>
  )
}

// packages/docs/vue/components/feedback/demos/drawer/drawer-position.vue
<template>
  <RadioGroup v-model="position">
    <Radio value="top">Top</Radio>
    <Radio value="right">Right</Radio>
    <Radio value="bottom">Bottom</Radio>
    <Radio value="left">Left</Radio>
  </RadioGroup>
  <div :style="{ marginTop: '20px' }">
    <Button type="primary" @click="handleClick">Open Drawer</Button>
  </div>
  <Drawer
    :width="340"
    :height="340"
    :visible="visible"
    :placement="position"
    @ok="handleOk"
    @cancel="handleCancel"
    unmountOnClose
  >
    <template #title> Title </template>
    <div
      >You can customize modal body text by the current situation. This modal
      will be closed immediately once you press the OK button.</div
    >
  </Drawer>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const visible = ref(false);
const position = ref('right');

const handleClick = () => {
  visible.value = true;
};
const handleOk = () => {
  visible.value = false;
};
const handleCancel = () => {
  visible.value = false;
};
</script>
