// packages/docs/site/src/demos/image/extra-actions.tsx
import React from 'react';
import { Image, Tooltip } from '@sbux/starbucks-design-react';
import { IconEye, IconDownload, IconInfoCircle } from '@sbux/starbucks-design-react/icon';

export default function Demo(props = {}) {
  const [visible, setVisible] = React.useState(false);
  return (
    <Image
      src="//p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/a8c8cdb109cb051163646151a4a5083b.png~tplv-uwbnlip3yd-webp.webp"
      title="A user’s avatar"
      description="Present by Arco Design"
      actions={[
        <button
          key="1"
          className="image-demo-action-item"
          onClick={(e) => {
            setVisible(true);
          }}
        >
          <IconEye />
        </button>,
        <button
          key="2"
          className="image-demo-action-item"
          onClick={(e) => {
            console.log('download');
          }}
        >
          <IconDownload />
        </button>,
        <Tooltip key="3" content="A user’s avatar">
          <button className="image-demo-action-item">
            <IconInfoCircle />
          </button>
        </Tooltip>,
      ]}
      previewProps={{
        visible,
        onVisibleChange: (e) => {
          setVisible(false);
        },
      }}
      {...props}
    />
  );
}

// packages/docs/vue/components/data-display/demos/image/extra-actions.vue
<template>
  <Image
    src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/a8c8cdb109cb051163646151a4a5083b.png~tplv-uwbnlip3yd-webp.webp"
    title="A user’s avatar"
    description="Present by Arco Design"
    width="260"
    style="margin-right: 67px; vertical-align: top;"
    :preview-visible="visible1"
    @preview-visible-change="
      () => {
        visible1 = false;
      }
    "
  >
    <template #extra>
      <div class="actions">
        <span
          class="action"
          @click="
            () => {
              visible1 = true;
            }
          "
          ><icon-eye
        /></span>
        <span class="action" @click="handleDownLoad"><icon-download /></span>
        <Tooltip content="A user’s avatar">
          <span class="action"><icon-info-circle /></span>
        </Tooltip>
      </div>
    </template>
  </Image>
  <Image
    src="https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/a8c8cdb109cb051163646151a4a5083b.png~tplv-uwbnlip3yd-webp.webp"
    title="A user’s avatar"
    description="Present by Arco Design"
    width="260"
    footer-position="outer"
    :preview-visible="visible2"
    @preview-visible-change="
      () => {
        visible2 = false;
      }
    "
  >
    <template #extra>
      <div class="actions actions-outer">
        <span
          class="action"
          @click="
            () => {
              visible2 = true;
            }
          "
          ><icon-eye
        /></span>
        <span class="action" @click="handleDownLoad"><icon-download /></span>
        <Tooltip content="A user’s avatar">
          <span class="action"><icon-info-circle /></span>
        </Tooltip>
      </div>
    </template>
  </Image>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import {
  IconEye,
  IconDownload,
  IconInfoCircle,
} from '@arco-design/web-vue/es/icon';

const visible1 = ref(false);
const visible2 = ref(false);
</script>
<style scoped>
.actions {
  display: flex;
  align-items: center;
}
.action {
  padding: 5px 4px;
  font-size: 14px;
  margin-left: 12px;
  border-radius: 2px;
  line-height: 1;
  cursor: pointer;
}
.action:first-child {
  margin-left: 0;
}

.action:hover {
  background: rgba(0, 0, 0, 0.5);
}
.actions-outer {
  .action {
    &:hover {
      color: #ffffff;
    }
  }
}
</style>
