// packages/docs/site/src/demos/upload/image-upload.vue
<template>
  <div class="sb-upload-demo">
    <Upload
      action="/"
      accept="image/*"
      list-type="picture-card"
      :show-file-list="false"
    >
      <template #upload-button>
        <Button class="sb-upload-image-trigger" type="dashed">点击上传图片</Button>
      </template>
    </Upload>
    <div class="sb-upload-tip">{{ tip }}</div>
  </div>
</template>

<script setup lang="ts">
import './showcase.css';

const tip = '额外提示语，文字过多时宽度折行';
</script>

// packages/docs/site/src/demos/upload/image-upload.tsx
import { Button, Upload } from '@sbux/starbucks-design-react';
import { IconPlus } from '@sbux/starbucks-design-react/icon';
import './showcase.css';

const tip = '额外提示语，文字过多时宽度折行';

export default function Demo() {
  return (
    <div className="sb-upload-demo">
      <Upload
        action="/"
        accept="image/*"
        listType="picture-card"
        showUploadList={false}
      >
        <Button className="sb-upload-image-trigger" type="dashed" icon={<IconPlus />}>
          点击上传图片
        </Button>
      </Upload>
      <div className="sb-upload-tip">{tip}</div>
    </div>
  );
}
