// packages/docs/site/src/demos/input-number/prefix-suffix.vue
<template>
  <Space direction="vertical" size="large">
    <InputNumber
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      allow-clear
    >
      <template #prefix>
        <icon-user />
      </template>
    </InputNumber>
    <InputNumber
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      allow-clear
      hide-button
    >
      <template #suffix>
        <icon-info-circle />
      </template>
    </InputNumber>
  </Space>
</template>

<script setup lang="ts">
import { IconUser, IconInfoCircle } from '@sbux/starbucks-design-vue/icon';
</script>

// packages/docs/site/src/demos/input-number/prefix-suffix.tsx
import { InputNumber } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <InputNumber
        min={0}
        defaultValue={50}
        suffix="%"
        step={1}
        style={{ width: 160, margin: '10px 24px 10px 0' }}
      />
      <InputNumber
        min={0}
        defaultValue={500}
        prefix="¥"
        step={100}
        style={{ width: 160, margin: '10px 24px 10px 0' }}
      />
      <InputNumber
        mode="button"
        min={0}
        defaultValue={500}
        prefix="¥"
        step={100}
        style={{ width: 160, margin: '10px 24px 10px 0' }}
      />
    </div>
  );
}
