// packages/docs/site/src/demos/timeline/custom-tag.vue
<template>
  <Timeline>
    <TimelineItem>
      Code Review
      <template #label>
        <Tag>
          <template #icon>
            <icon-check-circle-fill />
          </template>
          Passed
        </Tag>
      </template>
    </TimelineItem>
  </Timeline>
</template>

<script setup lang="ts">
import { IconCheckCircleFill } from '@sbux/starbucks-design-vue/icon';
</script>

// packages/docs/site/src/demos/timeline/custom-tag.tsx
import { Timeline, Tag } from '@sbux/starbucks-design-react';
import { IconCheckCircleFill } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <Timeline>
      <Timeline.Item label={<Tag icon={<IconCheckCircleFill />}>Passed</Tag>}>
        Code Review
      </Timeline.Item>
    </Timeline>
  );
}
