// packages/docs/site/src/demos/timeline/label-position.vue
<template>
  <div>
    <Row align="center">
      <TypographyText>labelPosition: &nbsp; &nbsp;</TypographyText>
      <RadioGroup @change="handleLabelPositionChange" :modelValue="pos">
        <Radio value="same">same</Radio>
        <Radio value="relative">relative</Radio>
      </RadioGroup>
    </Row>
    <Row align="center" :style="{ margin: '20px 0px 24px' }">
      <TypographyText>mode: &nbsp; &nbsp;</TypographyText>
      <RadioGroup @change="handleModeChange" :modelValue="mode">
        <Radio value="left">left</Radio>
        <Radio value="right">right</Radio>
        <Radio value="alternate">alternate</Radio>
      </RadioGroup>
    </Row>
    <Timeline :mode="mode" :labelPosition="pos">
      <TimelineItem label="2017-03-10" dotColor="#52C419">
        The first milestone
      </TimelineItem>
      <TimelineItem
        label="2018-05-12"
        dotColor="#F5222D"
        labelPosition="same"
      >
        The second milestone
      </TimelineItem>
      <TimelineItem label="2020-09-30" position="bottom">
        The third milestone
      </TimelineItem>
    </Timeline>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const mode = ref('left');
const pos = ref('same');

const handleLabelPositionChange = (_pos) => {
  pos.value = _pos;
};

const handleModeChange = (_mode) => {
  mode.value = _mode;
};
</script>

// packages/docs/site/src/demos/timeline/label-position.tsx
import React from 'react';
import { Grid, Typography, Radio, Timeline } from '@sbux/starbucks-design-react';

export default function Demo() {

  const [mode, setMode] = React.useState('left');
  const [pos, setLabelPos] = React.useState('same');
  return (
    <div>
      <Grid.Row align="center">
        <Typography.Text>labelPosition: &nbsp; &nbsp;</Typography.Text>
        <Radio.Group
          value={pos}
          onChange={setLabelPos}
          options={[
            {
              label: 'same',
              value: 'same',
            },
            {
              label: 'relative',
              value: 'relative',
            },
          ]}
        />
      </Grid.Row>
      <Grid.Row align="center" style={{ margin: '20px 0 24px' }}>
        <Typography.Text>mode: &nbsp; &nbsp;</Typography.Text>
        <Radio.Group
          value={mode}
          onChange={setMode}
          options={[
            {
              label: 'left',
              value: 'left',
            },
            {
              label: 'right',
              value: 'right',
            },
            {
              label: 'alternate',
              value: 'alternate',
            },
          ]}
        />
      </Grid.Row>
      <Timeline mode={mode} labelPosition={pos}>
        <Timeline.Item label="2017-03-10" dotColor="#52C419">
          The first milestone
        </Timeline.Item>
        <Timeline.Item label="2018-05-12" dotColor="#F5222D" labelPosition="same">
          The second milestone
        </Timeline.Item>
        <Timeline.Item label="2020-09-30">
          The third milestone
        </Timeline.Item>
      </Timeline>
    </div>
  );
}
