// packages/docs/site/src/demos/template-pages/step-form.vue
<template>
  <div class="sb-step-form-page sb-template-page-surface">
    <FormPageLayout>
      <Form ref="formRef" :model="form" layout="vertical" :rules="rules" :disabled="submitting">
        <StepFormLayout :sticky-actions="true">
          <template #steps>
            <Steps :current="currentStep">
              <Step>活动基础信息</Step>
              <Step>活动准入规则</Step>
              <Step>活动任务内容</Step>
            </Steps>
          </template>

          <FormSection v-if="currentStep === 1">
            <FormGrid>
              <FormGridItem>
                <FormItem field="activityName" label="活动名称" required>
                  <Input v-model="form.activityName" :max-length="80" placeholder="请输入活动名称" />
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="activityTime" label="活动时间" required>
                  <RangePicker v-model="form.activityTime" show-time format="YYYY-MM-DD HH:mm:ss" style="width: 100%" />
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="team" label="所属团队" required>
                  <Select v-model="form.team" :options="ACTIVITY_TEAM_OPTIONS" placeholder="请选择所属团队" />
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="deadlineDays" label="活动完成期限" required>
                  <div class="sb-step-form-page__inline-field">
                    <span>用户在准入后的 T+</span>
                    <Input v-model.number="form.deadlineDays" type="number" :min="-1" style="width: 120px" />
                    <span>天结束活动</span>
                  </div>
                </FormItem>
              </FormGridItem>
            </FormGrid>
          </FormSection>

          <FormSection v-else-if="currentStep === 2">
            <FormGrid>
              <FormGridItem :span="2">
                <FormItem field="memberLimit" label="参与限制" required>
                  <FormControlArea>
                    <RadioGroup v-model="form.memberLimit" :options="ACTIVITY_MEMBER_LIMIT_OPTIONS" />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>

              <FormGridItem :span="2">
                <FormItem field="memberLevels" label="会员等级" required>
                  <FormControlArea>
                    <CheckboxGroup v-model="form.memberLevels" :options="ACTIVITY_MEMBER_LEVEL_OPTIONS" />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>

              <FormGridItem :span="2">
                <FormItem field="cities" label="选择活动城市" required>
                  <FormControlArea>
                    <Select
                      v-model="form.cities"
                      multiple
                      :options="ACTIVITY_CITY_OPTIONS"
                      placeholder="请选择活动城市"
                      style="width: 100%"
                    />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>

              <FormGridItem :span="2">
                <FormItem field="targetAudience" label="指定人群" required>
                  <FormControlArea>
                    <RadioGroup v-model="form.targetAudience" :options="ACTIVITY_TARGET_AUDIENCE_OPTIONS" />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>
            </FormGrid>
          </FormSection>

          <FormSection v-else>
            <FormGrid>
              <FormGridItem>
                <FormItem field="taskType" label="任务类型" required>
                  <Select v-model="form.taskType" :options="ACTIVITY_TASK_TYPE_OPTIONS" placeholder="请选择任务类型" />
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="eventFilter" label="事件是否过滤" required>
                  <FormControlArea>
                    <RadioGroup v-model="form.eventFilter" :options="[
                      { label: '过滤', value: 'filter' },
                      { label: '不过滤', value: 'no-filter' },
                    ]" />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="couponType" label="券类型" required>
                  <Select v-model="form.couponType" :options="ACTIVITY_COUPON_TYPE_OPTIONS" placeholder="请选择券类型" />
                </FormItem>
              </FormGridItem>

              <FormGridItem>
                <FormItem field="couponScope" label="券号与券名" required>
                  <FormControlArea>
                    <RadioGroup v-model="form.couponScope" :options="[
                      { label: '不限', value: 'all' },
                      { label: '选择指定券', value: 'specified' },
                    ]" />
                  </FormControlArea>
                </FormItem>
              </FormGridItem>

              <FormGridItem :span="2">
                <FormItem field="selectedCoupons" label="选择活动券" required>
                  <Select
                    v-model="form.selectedCoupons"
                    multiple
                    :options="ACTIVITY_COUPON_SELECT_OPTIONS"
                    placeholder="请选择活动券"
                    style="width: 100%"
                  />
                </FormItem>
              </FormGridItem>

              <FormGridItem :span="2">
                <div class="sb-step-form-page__output-divider" />
              </FormGridItem>

              <FormGridItem :span="2">
                <div class="sb-step-form-page__dynamic-results">
                  <div v-for="(result, index) in form.outputResults" :key="index" class="sb-step-form-page__dynamic-result">
                    <FormItem :field="`outputResults[${index}]`" :label="`输出结果${index + 1}`" required>
                      <div class="sb-step-form-page__inline-field">
                        <span>用户核销</span>
                        <Input v-model.number="form.outputResults[index]" type="number" style="width: 120px" />
                        <span>张</span>
                      </div>
                    </FormItem>
                    <Button v-if="form.outputResults.length > 1" type="text" status="danger" @click="removeOutputResult(index)">删除</Button>
                  </div>
                  <Button type="text" @click="addOutputResult">＋新增输出结果</Button>
                </div>
              </FormGridItem>
            </FormGrid>
          </FormSection>

          <template #actions>
            <FormActions align="between">
              <Button html-type="button" :disabled="submitting" @click="handleCancel">取消</Button>
              <Space>
                <Button html-type="button" :disabled="currentStep === 1 || submitting" @click="handlePrevious">上一步</Button>
                <Button html-type="button" type="primary" :loading="submitting" @click="handleNext">
                  {{ currentStep === STEP_FIELDS.length ? '提交' : '下一步' }}
                </Button>
              </Space>
            </FormActions>
          </template>
        </StepFormLayout>
      </Form>

      <div v-if="submitSuccess" class="sb-step-form-page__success" role="status">活动创建成功</div>
    </FormPageLayout>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import {
  Button,
  CheckboxGroup,
  Form,
  FormItem,
  Input,
  Message,
  RadioGroup,
  RangePicker,
  Select,
  Space,
  Step,
  Steps,
} from '@sbux/starbucks-design-vue'
import { FormActions, FormControlArea, FormGrid, FormGridItem, FormPageLayout, FormSection, StepFormLayout } from '@sbux/starbucks-design-vue/pro'
import {
  ACTIVITY_COUPON_SELECT_OPTIONS,
  ACTIVITY_COUPON_TYPE_OPTIONS,
  ACTIVITY_CITY_OPTIONS,
  ACTIVITY_MEMBER_LEVEL_OPTIONS,
  ACTIVITY_MEMBER_LIMIT_OPTIONS,
  ACTIVITY_MESSAGES,
  ACTIVITY_TARGET_AUDIENCE_OPTIONS,
  ACTIVITY_TASK_TYPE_OPTIONS,
  ACTIVITY_TEAM_OPTIONS,
  createStepFormBaseline,
} from './grouped-step-form.shared'

const STEP_FIELDS = [
  ['activityName', 'activityTime', 'team', 'deadlineDays'],
  ['memberLimit', 'memberLevels', 'cities', 'targetAudience'],
  ['taskType', 'eventFilter', 'couponType', 'couponScope', 'selectedCoupons', 'outputResults'],
] as const

const formRef = ref()
const form = reactive(createStepFormBaseline())
const currentStep = ref(1)
const submitting = ref(false)
const submitSuccess = ref(false)

const rules = {
  activityName: [{ required: true, message: ACTIVITY_MESSAGES.activityName }],
  activityTime: [{ required: true, message: ACTIVITY_MESSAGES.activityTime }],
  team: [{ required: true, message: ACTIVITY_MESSAGES.team }],
  deadlineDays: [{ required: true, message: ACTIVITY_MESSAGES.deadlineDays }],
  memberLimit: [{ required: true, message: ACTIVITY_MESSAGES.memberLimit }],
  memberLevels: [{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.memberLevels }],
  cities: [{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.city }],
  targetAudience: [{ required: true, message: ACTIVITY_MESSAGES.targetAudience }],
  taskType: [{ required: true, message: ACTIVITY_MESSAGES.taskType }],
  eventFilter: [{ required: true, message: ACTIVITY_MESSAGES.eventFilter }],
  couponType: [{ required: true, message: ACTIVITY_MESSAGES.couponType }],
  couponScope: [{ required: true, message: ACTIVITY_MESSAGES.couponScope }],
  selectedCoupons: [{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.selectedCoupons }],
  outputResults: [{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.outputResults }],
}

const addOutputResult = () => {
  form.outputResults.push(1)
}

const removeOutputResult = (index: number) => {
  if (form.outputResults.length > 1) form.outputResults.splice(index, 1)
}

const handleNext = async () => {
  if (submitting.value) return
  const errors = await formRef.value?.validateField(STEP_FIELDS[currentStep.value - 1])
  if (errors) return

  if (currentStep.value < STEP_FIELDS.length) {
    currentStep.value += 1
    return
  }

  submitting.value = true
  await new Promise((resolve) => setTimeout(resolve, 500))
  Message.success('活动创建成功')
  submitSuccess.value = true
  submitting.value = false
}

const handlePrevious = () => {
  if (!submitting.value) currentStep.value = Math.max(1, currentStep.value - 1)
}

const handleCancel = () => {
  formRef.value?.resetFields()
  currentStep.value = 1
  submitSuccess.value = false
}
</script>

// packages/docs/site/src/demos/template-pages/step-form.tsx
import { useState } from 'react'
import {
  Button,
  Checkbox,
  DatePicker,
  Form,
  Input,
  Message,
  Radio,
  Select,
  Space,
  Steps,
} from '@sbux/starbucks-design-react'
import {
  FormActions,
  FormControlArea,
  FormGrid,
  FormGridItem,
  FormPageLayout,
  FormSection,
  StepFormLayout,
} from '@sbux/starbucks-design-react/pro'
import {
  ACTIVITY_COUPON_SELECT_OPTIONS,
  ACTIVITY_COUPON_TYPE_OPTIONS,
  ACTIVITY_CITY_OPTIONS,
  ACTIVITY_MEMBER_LEVEL_OPTIONS,
  ACTIVITY_MEMBER_LIMIT_OPTIONS,
  ACTIVITY_MESSAGES,
  ACTIVITY_TARGET_AUDIENCE_OPTIONS,
  ACTIVITY_TASK_TYPE_OPTIONS,
  ACTIVITY_TEAM_OPTIONS,
  createStepFormBaseline,
  type StepFormValues,
} from './grouped-step-form.shared'

const stepFields: Array<Array<keyof StepFormValues>> = [
  ['activityName', 'activityTime', 'team', 'deadlineDays'],
  ['memberLimit', 'memberLevels', 'cities', 'targetAudience'],
  ['taskType', 'eventFilter', 'couponType', 'couponScope', 'selectedCoupons', 'outputResults'],
]

export default function Demo() {
  const [form] = Form.useForm<StepFormValues>()
  const [currentStep, setCurrentStep] = useState(1)
  const [submitting, setSubmitting] = useState(false)
  const [submitSuccess, setSubmitSuccess] = useState(false)

  const validateCurrentStep = async () => {
    await form.validate(stepFields[currentStep - 1])
  }

  const handleNext = async () => {
    if (submitting) return

    try {
      await validateCurrentStep()
    } catch {
      return
    }

    if (currentStep < stepFields.length) {
      setCurrentStep((step) => step + 1)
      return
    }

    setSubmitting(true)
    await new Promise((resolve) => setTimeout(resolve, 500))
    Message.success('活动创建成功')
    setSubmitSuccess(true)
    setSubmitting(false)
  }

  const handlePrevious = () => {
    if (!submitting) setCurrentStep((step) => Math.max(1, step - 1))
  }

  const handleCancel = () => {
    form.resetFields()
    setCurrentStep(1)
    setSubmitSuccess(false)
  }

  const stepContent = () => {
    if (currentStep === 1) {
      return (
        <FormSection>
          <FormGrid>
            <FormGridItem>
              <Form.Item label="活动名称" field="activityName" required rules={[{ required: true, message: ACTIVITY_MESSAGES.activityName }]}>
                <Input maxLength={80} placeholder="请输入活动名称" />
              </Form.Item>
            </FormGridItem>

            <FormGridItem>
              <Form.Item label="活动时间" field="activityTime" required rules={[{ required: true, message: ACTIVITY_MESSAGES.activityTime }]}>
                <DatePicker.RangePicker showTime format="YYYY-MM-DD HH:mm:ss" style={{ width: '100%' }} />
              </Form.Item>
            </FormGridItem>

            <FormGridItem>
              <Form.Item label="所属团队" field="team" required rules={[{ required: true, message: ACTIVITY_MESSAGES.team }]}>
                <Select options={ACTIVITY_TEAM_OPTIONS} placeholder="请选择所属团队" />
              </Form.Item>
            </FormGridItem>

            <FormGridItem>
              <Form.Item label="活动完成期限" required>
                <div className="sb-step-form-page__inline-field">
                  <span>用户在准入后的 T+</span>
                  <Form.Item field="deadlineDays" noStyle rules={[{ required: true, message: ACTIVITY_MESSAGES.deadlineDays }]}>
                    <Input type="number" min={-1} style={{ width: 120 }} />
                  </Form.Item>
                  <span>天结束活动</span>
                </div>
              </Form.Item>
            </FormGridItem>
          </FormGrid>
        </FormSection>
      )
    }

    if (currentStep === 2) {
      return (
        <FormSection>
          <FormGrid>
            <FormGridItem span={2}>
              <Form.Item label="参与限制" required>
                <FormControlArea>
                  <Form.Item field="memberLimit" noStyle rules={[{ required: true, message: ACTIVITY_MESSAGES.memberLimit }]}>
                    <Radio.Group>
                      {ACTIVITY_MEMBER_LIMIT_OPTIONS.map((option) => (
                        <Radio key={option.value} value={option.value}>{option.label}</Radio>
                      ))}
                    </Radio.Group>
                  </Form.Item>
                </FormControlArea>
              </Form.Item>
            </FormGridItem>

            <FormGridItem span={2}>
              <Form.Item label="会员等级" required>
                <FormControlArea>
                  <Form.Item field="memberLevels" noStyle rules={[{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.memberLevels }]}>
                    <Checkbox.Group>
                      {ACTIVITY_MEMBER_LEVEL_OPTIONS.map((option) => (
                        <Checkbox key={option.value} value={option.value}>{option.label}</Checkbox>
                      ))}
                    </Checkbox.Group>
                  </Form.Item>
                </FormControlArea>
              </Form.Item>
            </FormGridItem>

            <FormGridItem span={2}>
              <Form.Item label="选择活动城市" required>
                <FormControlArea>
                  <Form.Item field="cities" noStyle rules={[{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.city }]}>
                    <Select
                      mode="multiple"
                      options={ACTIVITY_CITY_OPTIONS}
                      placeholder="请选择活动城市"
                      style={{ width: '100%' }}
                    />
                  </Form.Item>
                </FormControlArea>
              </Form.Item>
            </FormGridItem>

            <FormGridItem span={2}>
              <Form.Item label="指定人群" required>
                <FormControlArea>
                  <Form.Item field="targetAudience" noStyle rules={[{ required: true, message: ACTIVITY_MESSAGES.targetAudience }]}>
                    <Radio.Group>
                      {ACTIVITY_TARGET_AUDIENCE_OPTIONS.map((option) => (
                        <Radio key={option.value} value={option.value}>{option.label}</Radio>
                      ))}
                    </Radio.Group>
                  </Form.Item>
                </FormControlArea>
              </Form.Item>
            </FormGridItem>
          </FormGrid>
        </FormSection>
      )
    }

    return (
      <FormSection>
        <FormGrid>
          <FormGridItem>
            <Form.Item label="任务类型" field="taskType" required rules={[{ required: true, message: ACTIVITY_MESSAGES.taskType }]}>
              <Select options={ACTIVITY_TASK_TYPE_OPTIONS} placeholder="请选择任务类型" />
            </Form.Item>
          </FormGridItem>

          <FormGridItem>
            <Form.Item label="事件是否过滤" required>
              <FormControlArea>
                <Form.Item field="eventFilter" noStyle rules={[{ required: true, message: ACTIVITY_MESSAGES.eventFilter }]}>
                  <Radio.Group>
                    <Radio value="filter">过滤</Radio>
                    <Radio value="no-filter">不过滤</Radio>
                  </Radio.Group>
                </Form.Item>
              </FormControlArea>
            </Form.Item>
          </FormGridItem>

          <FormGridItem>
            <Form.Item label="券类型" field="couponType" required rules={[{ required: true, message: ACTIVITY_MESSAGES.couponType }]}>
              <Select options={ACTIVITY_COUPON_TYPE_OPTIONS} placeholder="请选择券类型" />
            </Form.Item>
          </FormGridItem>

          <FormGridItem>
            <Form.Item label="券号与券名" required>
              <FormControlArea>
                <Form.Item field="couponScope" noStyle rules={[{ required: true, message: ACTIVITY_MESSAGES.couponScope }]}>
                  <Radio.Group>
                    <Radio value="all">不限</Radio>
                    <Radio value="specified">选择指定券</Radio>
                  </Radio.Group>
                </Form.Item>
              </FormControlArea>
            </Form.Item>
          </FormGridItem>

          <FormGridItem span={2}>
            <Form.Item label="选择活动券" required>
              <Form.Item field="selectedCoupons" noStyle rules={[{ required: true, minLength: 1, message: ACTIVITY_MESSAGES.selectedCoupons }]}>
                <Select
                  mode="multiple"
                  options={ACTIVITY_COUPON_SELECT_OPTIONS}
                  placeholder="请选择活动券"
                  style={{ width: '100%' }}
                />
              </Form.Item>
            </Form.Item>
          </FormGridItem>

          <FormGridItem span={2}>
            <div className="sb-step-form-page__output-divider" />
          </FormGridItem>

          <FormGridItem span={2}>
            <Form.List
              field="outputResults"
              rules={[{
                validator: (value, callback) => {
                  if (!value?.length) {
                    callback(ACTIVITY_MESSAGES.outputResults)
                    return
                  }
                  callback()
                },
              }]}
            >
              {(fields, { add, remove }) => (
                <div className="sb-step-form-page__dynamic-results">
                  {fields.map((field, index) => (
                    <div className="sb-step-form-page__dynamic-result" key={field.key}>
                      <Form.Item label={`输出结果${index + 1}`} required>
                        <div className="sb-step-form-page__inline-field">
                          <span>用户核销</span>
                          <Form.Item field={field.field} noStyle rules={[{ required: true, message: '请输入核销数量' }]}>
                            <Input type="number" style={{ width: 120 }} />
                          </Form.Item>
                          <span>张</span>
                        </div>
                      </Form.Item>
                      {fields.length > 1 && <Button type="text" status="danger" onClick={() => remove(index)}>删除</Button>}
                    </div>
                  ))}
                  <Button type="text" onClick={() => add(1)}>＋新增输出结果</Button>
                </div>
              )}
            </Form.List>
          </FormGridItem>
        </FormGrid>
      </FormSection>
    )
  }

  return (
    <div className="sb-step-form-page sb-template-page-surface">
      <FormPageLayout>
        <Form form={form} layout="vertical" initialValues={createStepFormBaseline()} autoComplete="off" disabled={submitting}>
          <StepFormLayout
            steps={
              <Steps current={currentStep}>
                <Steps.Step title="活动基础信息" />
                <Steps.Step title="活动准入规则" />
                <Steps.Step title="活动任务内容" />
              </Steps>
            }
            stickyActions
            actions={
              <FormActions align="between">
                <Button htmlType="button" disabled={submitting} onClick={handleCancel}>取消</Button>
                <Space>
                  <Button htmlType="button" disabled={currentStep === 1 || submitting} onClick={handlePrevious}>上一步</Button>
                  <Button htmlType="button" type="primary" loading={submitting} onClick={handleNext}>
                    {currentStep === stepFields.length ? '提交' : '下一步'}
                  </Button>
                </Space>
              </FormActions>
            }
          >
            {stepContent()}
          </StepFormLayout>
        </Form>

        {submitSuccess && <div className="sb-step-form-page__success" role="status">活动创建成功</div>}
      </FormPageLayout>
    </div>
  )
}
