// packages/docs/site/src/demos/collapse/nested-panel.vue
<template>
  <Collapse :default-active-key="['1', 2]" destroy-on-hide>
    <CollapseItem header="Beijing Toutiao Technology Co., Ltd." key="1">
      <Collapse :default-active-key="['1.1']" destroy-on-hide>
        <CollapseItem
          header="Beijing Toutiao Technology Co., Ltd."
          key="1.1"
        >
          <div>Beijing Toutiao Technology Co., Ltd.</div>
        </CollapseItem>
        <CollapseItem
          header="Beijing Toutiao Technology Co., Ltd."
          key="1.2"
        >
          <div>Beijing Toutiao Technology Co., Ltd.</div>
        </CollapseItem>
      </Collapse>
    </CollapseItem>
    <CollapseItem header="Beijing Toutiao Technology Co., Ltd." :key="2">
      <div>Beijing Toutiao Technology Co., Ltd.</div>
    </CollapseItem>
    <CollapseItem header="Beijing Toutiao Technology Co., Ltd." key="3">
      <div>Beijing Toutiao Technology Co., Ltd.</div>
    </CollapseItem>
  </Collapse>
</template>

// packages/docs/site/src/demos/collapse/nested-panel.tsx
import { Collapse } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Collapse defaultActiveKey={['1', '2']} style={{ maxWidth: 1180 }}>
      <Collapse.Item header="Beijing Toutiao Technology Co., Ltd." name="1">
        <Collapse defaultActiveKey={'1.1'}>
          <Collapse.Item header="Beijing Toutiao Technology Co., Ltd." name="1.1">
            Beijing Toutiao Technology Co., Ltd.
          </Collapse.Item>
          <Collapse.Item header="Beijing Toutiao Technology Co., Ltd." name="1.2">
            Beijing Toutiao Technology Co., Ltd.
          </Collapse.Item>
        </Collapse>
      </Collapse.Item>
      <Collapse.Item header="Beijing Toutiao Technology Co., Ltd." name="2">
        Beijing Toutiao Technology Co., Ltd.
      </Collapse.Item>
      <Collapse.Item header="Beijing Toutiao Technology Co., Ltd." name="3">
        Beijing Toutiao Technology Co., Ltd.
      </Collapse.Item>
    </Collapse>
  );
}
