// packages/docs/site/src/demos/input/input-status.tsx
import { Input, Space } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <Space wrap>
      <Input style={{ width: 350 }} status="error" placeholder="error status" />
      <Input style={{ width: 350 }} status="warning" placeholder="warning status" />
      <Input style={{ width: 350 }} disabled placeholder="disabled input" />
    </Space>
  );
}

// packages/docs/vue/components/data-entry/demos/input/input-status.vue
<template>
  <Space direction="vertical" size="large">
    <Input
      :style="{ width: '320px' }"
      placeholder="Disabled status"
      disabled
    />
    <Input
      :style="{ width: '320px' }"
      default-value="Disabled"
      placeholder="Disabled status"
      disabled
    />
    <Input :style="{ width: '320px' }" placeholder="Error status" error />
  </Space>
</template>
