// packages/docs/site/src/demos/input/prefix-suffix.tsx
import { Input, Space } from '@sbux/starbucks-design-react';
import { IconUser, IconInfoCircle, IconSearch } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  return (
    <Space direction="vertical">
      <Space wrap>
        <Input style={{ width: 350 }} prefix={<IconUser />} placeholder="Enter something" />
        <Input
          allowClear
          style={{ width: 350 }}
          suffix={<IconInfoCircle />}
          placeholder="Enter something"
        />
      </Space>
      <Space wrap>
        <Input
          style={{ width: 350 }}
          prefix={<IconUser />}
          suffix={<IconInfoCircle />}
          placeholder="Enter something"
        />
        <Input
          style={{ width: 350 }}
          addBefore="+86"
          addAfter={<IconSearch />}
          prefix={<IconUser />}
          suffix={<IconInfoCircle />}
          allowClear
          placeholder="Enter something"
        />
      </Space>
    </Space>
  );
}

// packages/docs/vue/components/data-entry/demos/input/prefix-suffix.vue
<template>
  <Space direction="vertical" size="large">
    <Input
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      allow-clear
    >
      <template #prefix>
        <icon-user />
      </template>
    </Input>
    <Input
      :style="{ width: '320px' }"
      placeholder="Please enter something"
      allow-clear
    >
      <template #suffix>
        <icon-info-circle />
      </template>
    </Input>
  </Space>
</template>
