// packages/docs/site/src/demos/badge/color.vue
<template>
  <div>
    <Badge
      v-for="color in colors"
      :key="color"
      :color="color"
      :text="color"
      :style="{ marginRight: '24px' }"
    />
  </div>
  <br />
  <div>
    <Badge
      v-for="color in customColors"
      :key="color"
      :color="color"
      :text="color"
      :style="{ marginRight: '24px' }"
    />
  </div>
</template>

<script setup lang="ts">
import { reactive, toRefs } from 'vue';
const COLORS = [
  'red',
  'orangered',
  'orange',
  'gold',
  'lime',
  'green',
  'cyan',
  'arcoblue',
  'purple',
  'pinkpurple',
  'magenta',
  'gray',
];

const COLORS_CUSTOM = [
  '#F53F3F',
  '#7816FF',
  '#00B42A',
  '#165DFF',
  '#FF7D00',
  '#EB0AA4',
  '#7BC616',
  '#86909C',
  '#B71DE8',
  '#0FC6C2',
  '#FFB400',
  '#168CFF',
  '#FF5722',
];

const state = reactive({
  colors: COLORS,
  customColors: COLORS_CUSTOM,
});

const { colors, customColors } = toRefs(state);
</script>

// packages/docs/site/src/demos/badge/color.tsx
import { Badge } from '@sbux/starbucks-design-react';

export default function Demo() {
  const COLORS = [
    'red',
    'orangered',
    'orange',
    'gold',
    'lime',
    'green',
    'cyan',
    'arcoblue',
    'purple',
    'pinkpurple',
    'magenta',
    'gray'
  ];
  const COLORS_CUSTOM = [
    '#F53F3F',
    '#7816FF',
    '#00B42A',
    '#165DFF',
    '#FF7D00',
    '#EB0AA4',
    '#7BC616',
    '#86909C',
    '#B71DE8',
    '#0FC6C2',
    '#FFB400',
    '#168CFF',
    '#FF5722'
  ];

  return (
    <div>
      <div>
        {COLORS.map((color) => {
          return (
            <Badge key={color} color={color} text={color} style={{ marginRight: 24 }}>
              {' '}
            </Badge>
          );
        })}
      </div>
      <br />
      <div>
        {COLORS_CUSTOM.map((color) => {
          return (
            <Badge key={color} color={color} text={color} style={{ marginRight: 24 }}>
              {' '}
            </Badge>
          );
        })}
      </div>
    </div>
  );
}
