// packages/docs/site/src/demos/steps/custom-node.vue
<template>
  <div>
    <Steps
      changeable
      label-placement="vertical"
      :current="current"
      @change="handleSetCurrent"
    >
      <Step description="This is a description">
        Succeeded
        <template v-slot:node="slotProps">
          <Popover content="step tip" :popup-visible="current === 1">
            <span>{{ slotProps.step }}</span>
          </Popover>
        </template>
      </Step>
      <Step description="This is a description">
        Processing Succeeded
        <template v-slot:node="slotProps">
          <Popover content="step tip" :popup-visible="current === 2">
            <span>{{ slotProps.step }}</span>
          </Popover>
        </template>
      </Step>
      <Step description="This is a description"
        >Pending
        <template v-slot:node="slotProps">
          <Popover content="step tip" :popup-visible="current === 3">
            <span>{{ slotProps.step }}</span>
          </Popover>
        </template>
      </Step>
    </Steps>
    <div style="margin-top: 20px; text-align: center;">
      <Space size="large">
        <Button type="secondary" :disabled="current <= 1" @click="handlePrev">
          <IconLeft />
          Back
        </Button>
        <Button type="primary" :disabled="current >= 3" @click="handleNext">
          Next
          <IconRight />
        </Button>
      </Space>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { IconLeft, IconRight } from '@sbux/starbucks-design-vue/icon';

const current = ref(1);

const handlePrev = () => {
  current.value = Math.max(1, current.value - 1);
};

const handleNext = () => {
  current.value = Math.min(3, current.value + 1);
};

const handleSetCurrent = (current) => {
  current.value = current;
};
</script>

// packages/docs/site/src/demos/steps/custom-node.tsx
import { useState } from 'react';
import { Steps, Popover, Button } from '@sbux/starbucks-design-react';
import { IconLeft, IconRight } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const [current, setCurrent] = useState(2);

  const customDot = (dot, { status, index, title, description }) => {
    const visible = index === current;
    return (
      <Popover popupVisible={visible} content={<span>Step: {index}</span>}>
        {dot}
      </Popover>
    );
    return dot;
  };

  return (
    <div style={{ overflow: 'hidden', textAlign: 'center' }}>
      <Steps type="dot" current={current} customDot={customDot} style={{ marginTop: 20 }}>
        <Steps.Step title="Succeeded" description="This is a description" />
        <Steps.Step title="Processing" description="This is a description" />
        <Steps.Step title="Pending" description="This is a description" />
      </Steps>
      <div style={{ marginTop: 40 }}>
        <Button
          type="secondary"
          disabled={current <= 1}
          onClick={() => setCurrent(current - 1)}
          style={{ paddingLeft: 8 }}
        >
          <IconLeft />
          Back
        </Button>
        <Button
          disabled={current >= 3}
          onClick={() => setCurrent(current + 1)}
          style={{ marginLeft: 20, paddingRight: 8 }}
          type="primary"
        >
          Next
          <IconRight />
        </Button>
      </div>
    </div>
  );
}
