// packages/docs/site/src/demos/steps/mini-arrow-steps.vue
<template>
  <div>
    <Steps type="arrow" :current="2" small style="margin-bottom: 20px;">
      <Step description="This is a description">Succeeded</Step>
      <Step description="This is a description">Processing</Step>
      <Step description="This is a description">Pending</Step>
    </Steps>
    <Steps type="arrow" :current="2" small status="error">
      <Step description="This is a description">Succeeded</Step>
      <Step description="This is a description">Processing</Step>
      <Step description="This is a description">Pending</Step>
    </Steps>
  </div>
</template>

// packages/docs/site/src/demos/steps/mini-arrow-steps.tsx
import { Steps } from '@sbux/starbucks-design-react';

export default function Demo() {
  return (
    <div>
      <Steps type="arrow" size="small" current={2} style={{ maxWidth: 780, marginBottom: 20 }}>
        <Steps.Step title="Succeeded" />
        <Steps.Step title="Processing" />
        <Steps.Step title="Pending" />
      </Steps>
      <Steps type="arrow" size="small" status="error" current={2} style={{ maxWidth: 780 }}>
        <Steps.Step title="Succeeded" />
        <Steps.Step title="Processing" />
        <Steps.Step title="Pending" />
      </Steps>
    </div>
  );
}
