// packages/docs/site/src/demos/steps/vertical-steps.tsx
import { useState } from 'react';
import { Steps, Divider, Button } from '@sbux/starbucks-design-react';
import { IconLeft, IconRight } from '@sbux/starbucks-design-react/icon';

export default function Demo() {
  const [current, setCurrent] = useState(1);

  function renderContent(step) {
    return (
      <div
        style={{
          width: '100%',
          height: 272,
          textAlign: 'center',
          background: 'var(--color-bg-2)',
          color: '#C2C7CC',
        }}
      >
        <div style={{ lineHeight: '200px' }}>Step{step} Content</div>

        <div>
          <Button
            type="secondary"
            disabled={current <= 1}
            onClick={() => setCurrent(current - 1)}
            style={{ paddingLeft: 8 }}
          >
            <IconLeft />
            Back
          </Button>
          <Button
            disabled={current >= 3}
            onClick={() => setCurrent(current + 1)}
            style={{ marginLeft: 20, paddingRight: 8 }}
            type="primary"
          >
            Next
            <IconRight />
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div
      style={{
        display: 'flex',
        maxWidth: 780,
        padding: 40,
        background: 'var(--color-fill-2)',
      }}
    >
      <div
        style={{
          background: 'var(--color-bg-2)',
          padding: 24,
          height: 272,
          boxSizing: 'border-box',
        }}
      >
        <Steps direction="vertical" current={current} style={{ width: 170 }}>
          <Steps.Step title="Succeeded" description="This is a description" />
          <Steps.Step title="Processing" description="This is a description" />
          <Steps.Step title="Pending" description="This is a description" />
        </Steps>
      </div>
      <Divider type="vertical" style={{ display: "block", height: "auto" }}/>
      {renderContent(current)}
    </div>
  );
}

// packages/docs/site/src/demos/steps/vertical-steps.vue
<template>
  <div class="frame-bg">
    <div class="frame-body">
      <div class="frame-aside">
        <Steps :current="current" direction="vertical">
          <Step>Succeeded</Step>
          <Step>Processing</Step>
          <Step>Pending</Step>
        </Steps>
      </div>
      <div class="frame-main">
        <div class="main-content">The content of this step.</div>
        <div class="main-bottom">
          <Button :disabled="current === 1" @click="handlePrev">
            <icon-left />
            Back
          </Button>
          <Button :disabled="current === 3" @click="handleNext">
            Next
            <icon-right />
          </Button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { IconLeft, IconRight } from '@sbux/starbucks-design-vue/icon';

const current = ref(1);

const handlePrev = () => {
  current.value = Math.max(1, current.value - 1);
};

const handleNext = () => {
  current.value = Math.min(3, current.value + 1);
};
</script>

<style scoped>
.frame-bg {
  max-width: 780px;
  padding: 40px;
  background: var(--color-fill-2);
}

.frame-body {
  display: flex;
  background: var(--color-bg-2);
}

.frame-aside {
  padding: 24px;
  height: 272px;
  border-right: 1px solid var(--color-border);
}

.frame-main {
  width: 100%;
}

.main-content {
  text-align: center;
  line-height: 200px;
}

.main-bottom {
  display: flex;
  justify-content: center;
}

.main-bottom button {
  margin: 0 20px;
}
</style>
